В этом ноутбуке мы будем работать над моделью предсказания движеняи цены акций по новостям, чтобы выявить важность признаков, а также актуальность бизнес-задачи.

In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("finhub+theguardian_raw_7.5k.csv", index_col=0)
df = df.dropna(subset=["fields.trailText"])
df.shape

(7353, 48)

В нашем датасете есть новости для которых есть краткая сводка, а есть новости для которых есть и краткая сводка и полный текст статьи. Для удобства будет обозначать их как short и full (или же s и f)

In [3]:
df["fields.trailText"]

0       Google, Amazon, Apple and Samsung control oper...
1       CMA intends to force tech firms to make change...
2       National Association of Cider Makers says warm...
3       First penalties under landmark Digital Markets...
4       CMA examining impact of tech firms’ operating ...
                              ...
7374     Cisco, 3M share gains lead Dow's 160-point climb
7375    A key trading signal flashed for Caterpillar s...
7376    Caterpillar and Walmart have been highlighted ...
7377    Atlas Energy Solutions Inc. (NYSE:AESI) (&#34;...
7378    Macroeconomic and sector-specific issues vary ...
Name: fields.trailText, Length: 7353, dtype: str

In [4]:
df["fields.bodyText"]

0       The world’s largest broadcasters have pushed f...
1       A UK watchdog has said it intends to take acti...
2       “If you love cider, this is cider to the power...
3       The European Commission has fined Apple €500m ...
4       The UK’s competition watchdog has launched inv...
                              ...
7374                                                  NaN
7375                                                  NaN
7376                                                  NaN
7377                                                  NaN
7378                                                  NaN
Name: fields.bodyText, Length: 7353, dtype: str

Ячейками ниже преобразуем наши текста в эмбеддинги. Код ниже был запущен в ноутубке на kaggle, поскольку на CPU данная операция работает очень медленно. Код был перенесен сюда и закомментирован, чтобы он не выполнялся при нажатии на "Run All".

In [5]:
# from sentence_transformers import SentenceTransformer

# model = SentenceTransformer("intfloat/multilingual-e5-small")

# texts = ["passage: " + x for x in df["fields.bodyText"]]

# embeddings_full = model.encode(
#     texts,
#     normalize_embeddings=True,
#     show_progress_bar=True
# )

In [6]:
# model = SentenceTransformer("intfloat/multilingual-e5-small")

# texts = ["passage: " + x for x in df["fields.trailText"]]

# embeddings_short = model.encode(
#     texts,
#     normalize_embeddings=True,
#     show_progress_bar=True
# )

Сохраняем наши эмбеддинги в файлы

In [7]:
# np.save("embeddings_f.npy", embeddings_full)

In [8]:
# np.save("embeddings_s.npy", embeddings_short)

Сразу же подгрузим и преобразуем в DataFrame

In [9]:
np_embeddings_full = np.load('embeddings_f.npy')
np_embeddings_short = np.load('embeddings_s.npy')

In [10]:
embeddings_full = pd.DataFrame(np_embeddings_full)
embeddings_short = pd.DataFrame(np_embeddings_short)

In [11]:
embeddings_full.shape

(5549, 384)

In [12]:

embeddings_short.shape

(7353, 384)

Соединим эмбеддинги с исходным датасетом, из которого оставим только то что пригодится для нашей модели - дата публикации, тикеры которые были указаны экспертами в статье, компании для которых эта новость была найдена, и источник новости.

In [13]:
embeddings_full.columns = [f"emb_f_{i}" for i in range(embeddings_full.shape[1])]
embeddings_short.columns = [f"emb_s_{i}" for i in range(embeddings_short.shape[1])]

In [14]:
df = df[["webPublicationDate", "stocks", "company", "source"]]

In [15]:
data = pd.concat(
    [
        df.reset_index(drop=True),
        embeddings_full.reset_index(drop=True),
        embeddings_short.reset_index(drop=True)
    ],
    axis=1
)

В столбце company для статей из FinHub есть пропуски, зато в тикерах пропусков нет. Восстановим компании по тикерам:

In [16]:
mapping = {
    "AAPL": "Apple",
    "TSLA": "Tesla",
    "CAT": "Caterpillar",
    "JPM": "JPMorgan",
    "NFLX": "Netflix",
    "PFE": "Pfizer",
    "XOM": "Exxon",
    "WMT": "Walmart"
}

In [17]:
data.loc[data["company"].isna(), "company"] = data.loc[data["company"].isna(), "stocks"].str.split(";").apply(lambda x: ";".join(mapping[i] for i in x if i in mapping))

In [18]:
data.isna().sum(axis=0)

webPublicationDate       0
stocks                4152
company                  0
source                   0
emb_f_0               1804
                      ...
emb_s_379                0
emb_s_380                0
emb_s_381                0
emb_s_382                0
emb_s_383                0
Length: 772, dtype: int64

Для столбца stocks сделаем OHE оставив только нужные нам тикеры:

In [19]:
stocks = (data["stocks"].fillna("").str.get_dummies(sep=";"))[["AAPL", "TSLA", "CAT", "JPM", "NFLX", "PFE", "XOM", "WMT"]]

In [20]:
data = pd.concat([stocks, data], axis=1)

Аналогично сделаем OHE для столбца source:

In [21]:
source = data["source"].str.get_dummies()

In [22]:
data = pd.concat([source, data], axis=1)

In [23]:
data = data.drop(columns=["stocks", "source"])

Сохраним наш датасет под названием data_model

In [24]:
# data.to_csv("data_model.csv", index=False)

Разделим его на новости у которых есть полное содержимое и у которых нет:

In [33]:
common_cols = [c for c in data.columns if not c.startswith("emb_f_") and not c.startswith("emb_s_")]
f_cols = [c for c in data.columns if c.startswith("emb_f_")]
s_cols = [c for c in data.columns if c.startswith("emb_s_")]

data_f = data[common_cols + f_cols].copy()
data_s = data[common_cols + s_cols].copy()

In [34]:
data_f = data_f.dropna()
data_s = data_s.dropna()

In [ ]:
# data_f.to_csv("data_f.csv", index=False)
# data_s.to_csv("data_s.csv", index=False)

In [326]:
data_f = pd.read_csv("data_f.csv")
data_s = pd.read_csv("data_s.csv")

In [327]:
data_f["webPublicationDate"] = pd.to_datetime(data_f["webPublicationDate"])
data_s["webPublicationDate"] = pd.to_datetime(data_s["webPublicationDate"])

В столбце company у нас несколько компаний для одной и той же новости. Рзаделим их так, чтобы одна строка с несколькими компаниями превратилась в несколько разных строк, каждая с одной компанией. Так будет легче выделять нужные нам строки:

In [328]:
data_f["company"] = data_f["company"].str.split(";")
data_f = data_f.explode("company", ignore_index=True)

In [329]:
data_s["company"] = data_s["company"].str.split(";")
data_s = data_s.explode("company", ignore_index=True)

In [330]:
data_f.head()

,Benzinga,CNBC,ChartMill,DowJones,MarketWatch,SeekingAlpha,The Guardian,Yahoo,AAPL,TSLA,CAT,JPM,NFLX,PFE,XOM,WMT,webPublicationDate,company,emb_f_0,emb_f_1,emb_f_2,emb_f_3,emb_f_4,emb_f_5,emb_f_6,emb_f_7,emb_f_8,emb_f_9,emb_f_10,emb_f_11,emb_f_12,emb_f_13,emb_f_14,emb_f_15,emb_f_16,emb_f_17,emb_f_18,emb_f_19,emb_f_20,emb_f_21,emb_f_22,emb_f_23,emb_f_24,emb_f_25,emb_f_26,emb_f_27,emb_f_28,emb_f_29,emb_f_30,emb_f_31,emb_f_32,emb_f_33,emb_f_34,emb_f_35,emb_f_36,emb_f_37,emb_f_38,emb_f_39,emb_f_40,emb_f_41,emb_f_42,emb_f_43,emb_f_44,emb_f_45,emb_f_46,emb_f_47,emb_f_48,emb_f_49,emb_f_50,emb_f_51,emb_f_52,emb_f_53,emb_f_54,emb_f_55,emb_f_56,emb_f_57,emb_f_58,emb_f_59,emb_f_60,emb_f_61,emb_f_62,emb_f_63,emb_f_64,emb_f_65,emb_f_66,emb_f_67,emb_f_68,emb_f_69,emb_f_70,emb_f_71,emb_f_72,emb_f_73,emb_f_74,emb_f_75,emb_f_76,emb_f_77,emb_f_78,emb_f_79,emb_f_80,emb_f_81,emb_f_82,emb_f_83,emb_f_84,emb_f_85,emb_f_86,emb_f_87,emb_f_88,emb_f_89,emb_f_90,emb_f_91,emb_f_92,emb_f_93,emb_f_94,emb_f_95,emb_f_96,emb_f_97,emb_f_98,emb_f_99,emb_f_100,emb_f_101,emb_f_102,emb_f_103,emb_f_104,emb_f_105,emb_f_106,emb_f_107,emb_f_108,emb_f_109,emb_f_110,emb_f_111,emb_f_112,emb_f_113,emb_f_114,emb_f_115,emb_f_116,emb_f_117,emb_f_118,emb_f_119,emb_f_120,emb_f_121,emb_f_122,emb_f_123,emb_f_124,emb_f_125,emb_f_126,emb_f_127,emb_f_128,emb_f_129,emb_f_130,emb_f_131,emb_f_132,emb_f_133,emb_f_134,emb_f_135,emb_f_136,emb_f_137,emb_f_138,emb_f_139,emb_f_140,emb_f_141,emb_f_142,emb_f_143,emb_f_144,emb_f_145,emb_f_146,emb_f_147,emb_f_148,emb_f_149,emb_f_150,emb_f_151,emb_f_152,emb_f_153,emb_f_154,emb_f_155,emb_f_156,emb_f_157,emb_f_158,emb_f_159,emb_f_160,emb_f_161,emb_f_162,emb_f_163,emb_f_164,emb_f_165,emb_f_166,emb_f_167,emb_f_168,emb_f_169,emb_f_170,emb_f_171,emb_f_172,emb_f_173,emb_f_174,emb_f_175,emb_f_176,emb_f_177,emb_f_178,emb_f_179,emb_f_180,emb_f_181,emb_f_182,emb_f_183,emb_f_184,emb_f_185,emb_f_186,emb_f_187,emb_f_188,emb_f_189,emb_f_190,emb_f_191,emb_f_192,emb_f_193,emb_f_194,emb_f_195,emb_f_196,emb_f_197,emb_f_198,emb_f_199,emb_f_200,emb_f_201,emb_f_202,emb_f_203,emb_f_204,emb_f_205,emb_f_206,emb_f_207,emb_f_208,emb_f_209,emb_f_210,emb_f_211,emb_f_212,emb_f_213,emb_f_214,emb_f_215,emb_f_216,emb_f_217,emb_f_218,emb_f_219,emb_f_220,emb_f_221,emb_f_222,emb_f_223,emb_f_224,emb_f_225,emb_f_226,emb_f_227,emb_f_228,emb_f_229,emb_f_230,emb_f_231,emb_f_232,emb_f_233,emb_f_234,emb_f_235,emb_f_236,emb_f_237,emb_f_238,emb_f_239,emb_f_240,emb_f_241,emb_f_242,emb_f_243,emb_f_244,emb_f_245,emb_f_246,emb_f_247,emb_f_248,emb_f_249,emb_f_250,emb_f_251,emb_f_252,emb_f_253,emb_f_254,emb_f_255,emb_f_256,emb_f_257,emb_f_258,emb_f_259,emb_f_260,emb_f_261,emb_f_262,emb_f_263,emb_f_264,emb_f_265,emb_f_266,emb_f_267,emb_f_268,emb_f_269,emb_f_270,emb_f_271,emb_f_272,emb_f_273,emb_f_274,emb_f_275,emb_f_276,emb_f_277,emb_f_278,emb_f_279,emb_f_280,emb_f_281,emb_f_282,emb_f_283,emb_f_284,emb_f_285,emb_f_286,emb_f_287,emb_f_288,emb_f_289,emb_f_290,emb_f_291,emb_f_292,emb_f_293,emb_f_294,emb_f_295,emb_f_296,emb_f_297,emb_f_298,emb_f_299,emb_f_300,emb_f_301,emb_f_302,emb_f_303,emb_f_304,emb_f_305,emb_f_306,emb_f_307,emb_f_308,emb_f_309,emb_f_310,emb_f_311,emb_f_312,emb_f_313,emb_f_314,emb_f_315,emb_f_316,emb_f_317,emb_f_318,emb_f_319,emb_f_320,emb_f_321,emb_f_322,emb_f_323,emb_f_324,emb_f_325,emb_f_326,emb_f_327,emb_f_328,emb_f_329,emb_f_330,emb_f_331,emb_f_332,emb_f_333,emb_f_334,emb_f_335,emb_f_336,emb_f_337,emb_f_338,emb_f_339,emb_f_340,emb_f_341,emb_f_342,emb_f_343,emb_f_344,emb_f_345,emb_f_346,emb_f_347,emb_f_348,emb_f_349,emb_f_350,emb_f_351,emb_f_352,emb_f_353,emb_f_354,emb_f_355,emb_f_356,emb_f_357,emb_f_358,emb_f_359,emb_f_360,emb_f_361,emb_f_362,emb_f_363,emb_f_364,emb_f_365,emb_f_366,emb_f_367,emb_f_368,emb_f_369,emb_f_370,emb_f_371,emb_f_372,emb_f_373,emb_f_374,emb_f_375,emb_f_376,emb_f_377,emb_f_378,emb_f_379,emb_f_380,emb_f_381,emb_f_382,emb_f_383
0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2026-03-23 13:31:06+00:00,Apple,0.038025,0.018858,-0.086595,0.008641,0.034031,-0.018835,0.076140,0.012036,0.033506,0.011971,0.063189,0.016846,0.076012,-0.084967,-0.045191,0.040121,0.061898,-0.002628,-0.024180,-0.058232,0.025985,-0.023125,-0.056735,0.033251,0.064188,0.080117,-0.064643,0.014658,-0.027111,-0.049216,-0.059584,-0.063907,0.061834,-0.099122,0.044907,0.019759,-0.036929,-0.049866,0.058166,-0.033384,-0.035382,0.026429,0.025998,0.103433,0.055798,0.024773,-0.017467,0.031075,-0.056646,-0.020733,-0.065451,0.031899,0.045822,0.057932,0.054153,-0.039517,-0.090263,-0.080082,-0.020314,-0.00266,0.092827,-0.051519,0.036129,-0.014263,0.040663,0.033581,-0.004201,0.033415,-0.060745,0.014824,-0.009569,0.043846,0.015037,-0.065885,0.031751,0.10263,0.049452,-0.019729,0.023484,0.011308,-0.059146,-0.077472,-0.029474,0.047105,-0.028209,0.081943,0.071144,-0.072979,0.081368,-0.023541,-0.024118,0.047241,-0.065265,-0.035430,-0.048655,-0.049407,-0.033535,0.096568,0.070078,-0.018527,0.082767,-0.074878,0.046550,-0.021118,-0.063131,0.019430,0.040776,-0.055604,0.085321,-0.074215,-0.028909,0.018009,0.069572,0.016697,-0.081627,-0.068889,-0.028755,-0.072625,0.012519,-0.044597,0.093571,-0.033167,-0.016155,-0.096866,-0.072974,-0.035678,0.016550,0.034578,0.063297,0.020400,0.015024,0.044000,0.056340,0.077235,0.081252,0.103822,-0.085244,-0.002350,-0.043159,-0.062273,-0.025932,0.095033,-0.035358,0.051496,0.056035,0.040303,0.051378,-0.028961,0.037197,-0.007587,0.035918,-0.060254,0.078566,0.034235,0.062392,-0.075872,-0.053853,-0.032895,0.033365,0.066921,-0.027530,-0.036516,-0.102985,0.014247,-0.028739,-0.022980,0.021429,0.064870,0.003385,-0.005851,-0.065104,0.047444,-0.039536,0.057797,0.012176,0.053917,-0.094062,-0.008078,0.057595,0.050228,-0.064663,-0.03288,-0.073867,-0.063811,-0.034164,-0.065423,-0.040367,0.063859,0.00845,-0.015013,0.024284,0.017185,-0.066683,-0.073007,-0.046892,0.071188,-0.052892,0.045286,0.020603,0.016777,-0.028692,-0.011352,0.048107,0.056427,0.016846,0.023313,-0.029326,0.067730,-0.037509,0.052975,0.067621,-0.068742,-0.074349,0.082270,-0.039638,-0.025498,0.021231,0.035030,-0.077371,0.030676,0.089377,-0.049328,0.047179,-0.072956,-0.005441,0.043417,0.080251,-0.047452,-0.053972,0.011236,-0.054727,-0.007871,-0.051056,-0.008326,-0.062684,-0.055155,-0.009197,0.060596,-0.000216,-0.038149,-0.075700,-0.015891,0.013155,-0.060592,0.071692,-0.032164,-0.054593,0.040430,0.021232,0.042799,0.047348,-0.058623,-0.070587,-0.003159,-0.044039,0.103689,0.067558,0.058313,-0.087304,0.038223,0.048917,-0.036565,0.045964,0.022143,0.047641,0.045015,-0.003066,-0.062033,-0.035443,-0.028948,-0.057692,0.036809,0.023672,0.003128,-0.054957,-0.045523,-0.010000,0.073081,-0.044362,-0.039034,0.045809,0.021007,0.022405,0.077515,0.060358,-0.021224,-0.01532,0.054028,-0.081312,-0.049697,-0.053018,-0.056819,0.063424,-0.021582,0.046387,0.056845,0.004724,0.062874,-0.041765,0.002014,-0.008127,-0.011316,0.035344,0.064695,-0.068760,0.012563,0.039127,0.043441,0.002915,0.023517,0.062379,0.050161,-0.030371,-0.025255,0.013294,0.069298,-0.033984,0.030053,-0.053445,-0.084558,-0.038507,-0.053299,-0.072722,-0.047565,-0.008606,0.040937,-0.037393,-0.038561,0.026209,-0.028136,0.013004,-0.038102,-0.030115,0.055816,-0.075088,-0.012603,0.014443,0.055649,-0.086399,-0.108251,0.007392,-0.012850,-0.034204,0.034605,-0.000295,-0.010119,0.033695,-0.067820,-0.021389,0.022009,0.055020,-0.094434,0.013761,0.056713,-0.049651,0.048126,-0.099841,-0.022538,0.077094,0.070519,-0.098684,-0.011535,0.026741,0.060796,0.073505,0.072355,-0.047605,0.001703,0.088197,-0.030249,0.029592,0.043072,-0.026665,0.007139,-0.053185,-0.053847,-0.034330,0.014471,-0.056053,-0.058262,0.029631,0.054520,0.027139,0.047965
1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2026-03-23 13:31:06+00:00,JPMorgan,0.038025,0.018858,-0.086595,0.008641,0.034031,-0.018835,0.076140,0.012036,0.033506,0.011971,0.063189,0.016846,0.076012,-0.084967,-0.045191,0.040121,0.061898,-0.002628,-0.024180,-0.058232,0.025985,-0.023125,-0.056735,0.033251,0.064188,0.080117,-0.064643,0.014658,-0.027111,-0.049216,-0.059584,-0.063907,0.061834,-0.099122,0.044907,0.019759,-0.036929,-0.049866,0.058166,-0.033384,-0.035382,0.026429,0.025998,0.103433,0.055798,0.024773,-0.017467,0.031075,-0.056646,-0.020733,-0.065451,0.031899,0.045822,0.057932,0.054153,-0.039517,-0.090263,-0.080082,-0.020314,-0.00266,0.092827,-0.051519,0.036129,-0.014263,0.040663,0.033581,-0.004201,0.033415,-0.060745,0.014824,-0.009569,0.043846,0.015037,-0.065885,0.031751,0.10263,0.049452,-0.019729,0.023484,0.011308,-0.059146,-0.077472,-0.029474,0.047105,-0.028209,0.081943,0.071144,-0.072979,0.081368,-0.023541,-0.024118,0.047241,-0.065265,-0.035430,-0.048655,-0.049407,-0.033535,0.096568,0.070078,-0.018527,0.082767,-0.074878,0.046550,-0.021118,-0.063131,0.019430,0.040776,-0.055604,0.085321,-0.074215,-0.028909,0.018009,0.069572,0.016697,-0.081627,-0.068889,-0.028755,-0.072625,0.012519,-0.044597,0.093571,-0.033167,-0.016155,-0.096866,-0.072974,-0.035678,0.016550,0.034578,0.063297,0.020400,0.015024,0.044000,0.056340,0.077235,0.081252,0.103822,-0.085244,-0.002350,-0.043159,-0.062273,-0.025932,0.095033,-0.035358,0.051496,0.056035,0.040303,0.051378,-0.028961,0.037197,-0.007587,0.035918,-0.060254,0.078566,0.034235,0.062392,-0.075872,-0.053853,-0.032895,0.033365,0.066921,-0.027530,-0.036516,-0.102985,0.014247,-0.028739,-0.022980,0.021429,0.064870,0.003385,-0.005851,-0.065104,0.047444,-0.039536,0.057797,0.012176,0.053917,-0.094062,-0.008078,0.057595,0.050228,-0.064663,-0.03288,-0.073867,-0.063811,-0.034164,-0.065423,-0.040367,0.063859,0.00845,-0.015013,0.024284,0.017185,-0.066683,-0.073007,-0.046892,0.071188,-0.052892,0.045286,0.020603,0.016777,-0.028692,-0.011352,0.048107,0.056427,0.016846,0.023313,-0.029326,0.067730,-0.037509,0.052975,0.067621,-0.068742,-0.074349,0.082270,-0.039638,-0.025498,0.021231,0.035030,-0.077371,0.030676,0.089377,-0.049328,0.047179,-0.072956,-0.005441,0.043417,0.080251,-0.047452,-0.053972,0.011236,-0.054727,-0.007871,-0.051056,-0.008326,-0.062684,-0.055155,-0.009197,0.060596,-0.000216,-0.038149,-0.075700,-0.015891,0.013155,-0.060592,0.071692,-0.032164,-0.054593,0.040430,0.021232,0.042799,0.047348,-0.058623,-0.070587,-0.003159,-0.044039,0.103689,0.067558,0.058313,-0.087304,0.038223,0.048917,-0.036565,0.045964,0.022143,0.047641,0.045015,-0.003066,-0.062033,-0.035443,-0.028948,-0.057692,0.036809,0.023672,0.003128,-0.054957,-0.045523,-0.010000,0.073081,-0.044362,-0.039034,0.045809,0.021007,0.022405,0.077515,0.060358,-0.021224,-0.01532,0.054028,-0.081312,-0.049697,-0.053018,-0.056819,0.063424,-0.021582,0.046387,0.056845,0.004724,0.062874,-0.041765,0.002014,-0.008127,-0.011316,0.035344,0.064695,-0.068760,0.012563,0.039127,0.043441,0.002915,0.023517,0.062379,0.050161,-0.030371,-0.025255,0.013294,0.069298,-0.033984,0.030053,-0.053445,-0.084558,-0.038507,-0.053299,-0.072722,-0.047565,-0.008606,0.040937,-0.037393,-0.038561,0.026209,-0.028136,0.013004,-0.038102,-0.030115,0.055816,-0.075088,-0.012603,0.014443,0.055649,-0.086399,-0.108251,0.007392,-0.012850,-0.034204,0.034605,-0.000295,-0.010119,0.033695,-0.067820,-0.021389,0.022009,0.055020,-0.094434,0.013761,0.056713,-0.049651,0.048126,-0.099841,-0.022538,0.077094,0.070519,-0.098684,-0.011535,0.026741,0.060796,0.073505,0.072355,-0.047605,0.001703,0.088197,-0.030249,0.029592,0.043072,-0.026665,0.007139,-0.053185,-0.053847,-0.034330,0.014471,-0.056053,-0.058262,0.029631,0.054520,0.027139,0.047965
2,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2026-03-23 13:31:06+00:00,Netflix,0.038025,0.018858,-0.086595,0.008641,0.034031,-0.018835,0.076140,0.012036,0.033506,0.011971,0.063189,0.016846,0.076012,-0.084967,-0.045191,0.040121,0.061898,-0.002628,-0.024180,-0.058232,0.025985,-0.023125,-0.056735,0.033251,0.064188,0.080117,-0.064643,0.014658,-0.027111,-0.049216,-0.059584,-0.063907,0.061834,-0.099122,0.044907,0.019759,-0.036929,-0.049866,0.058166,-0.033384,-0.035382,0.026429,0.025998,0.103433,0.055798,0.024773,-0.017467,0.031075,-0.056646,-0.020733,-0.065451,0.031899,0.045822,0.057932,0.054153,-0.039517,-0.090263,-0.080082,-0.020314,-0.00266,0.092827,-0.051519,0.036129,-0.014263,0.040663,0.033581,-0.004201,0.033415,-0.060745,0.014824,-0.009569,0.043846,0.015037,-0.065885,0.031751,0.10263,0.049452,-0.019729,0.023484,0.011308,-0.059146,-0.077472,-0.029474,0.047105,-0.028209,0.081943,0.071144,-0.072979,0.081368,-0.023541,-0.024118,0.047241,-0.065265,-0.035430,-0.048655,-0.049407,-0.033535,0.096568,0.070078,-0.018527,0.082767,-0.074878,0.046550,-0.021118,-0.063131,0.019430,0.040776,-0.055604,0.085321,-0.074215,-0.028909,0.018009,0.069572,0.016697,-0.081627,-0.068889,-0.028755,-0.072625,0.012519,-0.044597,0.093571,-0.033167,-0.016155,-0.096866,-0.072974,-0.035678,0.016550,0.034578,0.063297,0.020400,0.015024,0.044000,0.056340,0.077235,0.081252,0.103822,-0.085244,-0.002350,-0.043159,-0.062273,-0.025932,0.095033,-0.035358,0.051496,0.056035,0.040303,0.051378,-0.028961,0.037197,-0.007587,0.035918,-0.060254,0.078566,0.034235,0.062392,-0.075872,-0.053853,-0.032895,0.033365,0.066921,-0.027530,-0.036516,-0.102985,0.014247,-0.028739,-0.022980,0.021429,0.064870,0.003385,-0.005851,-0.065104,0.047444,-0.039536,0.057797,0.012176,0.053917,-0.094062,-0.008078,0.057595,0.050228,-0.064663,-0.03288,-0.073867,-0.063811,-0.034164,-0.065423,-0.040367,0.063859,0.00845,-0.015013,0.024284,0.017185,-0.066683,-0.073007,-0.046892,0.071188,-0.052892,0.045286,0.020603,0.016777,-0.028692,-0.011352,0.048107,0.056427,0.016846,0.023313,-0.029326,0.067730,-0.037509,0.052975,0.067621,-0.068742,-0.074349,0.082270,-0.039638,-0.025498,0.021231,0.035030,-0.077371,0.030676,0.089377,-0.049328,0.047179,-0.072956,-0.005441,0.043417,0.080251,-0.047452,-0.053972,0.011236,-0.054727,-0.007871,-0.051056,-0.008326,-0.062684,-0.055155,-0.009197,0.060596,-0.000216,-0.038149,-0.075700,-0.015891,0.013155,-0.060592,0.071692,-0.032164,-0.054593,0.040430,0.021232,0.042799,0.047348,-0.058623,-0.070587,-0.003159,-0.044039,0.103689,0.067558,0.058313,-0.087304,0.038223,0.048917,-0.036565,0.045964,0.022143,0.047641,0.045015,-0.003066,-0.062033,-0.035443,-0.028948,-0.057692,0.036809,0.023672,0.003128,-0.054957,-0.045523,-0.010000,0.073081,-0.044362,-0.039034,0.045809,0.021007,0.022405,0.077515,0.060358,-0.021224,-0.01532,0.054028,-0.081312,-0.049697,-0.053018,-0.056819,0.063424,-0.021582,0.046387,0.056845,0.004724,0.062874,-0.041765,0.002014,-0.008127,-0.011316,0.035344,0.064695,-0.068760,0.012563,0.039127,0.043441,0.002915,0.023517,0.062379,0.050161,-0.030371,-0.025255,0.013294,0.069298,-0.033984,0.030053,-0.053445,-0.084558,-0.038507,-0.053299,-0.072722,-0.047565,-0.008606,0.040937,-0.037393,-0.038561,0.026209,-0.028136,0.013004,-0.038102,-0.030115,0.055816,-0.075088,-0.012603,0.014443,0.055649,-0.086399,-0.108251,0.007392,-0.012850,-0.034204,0.034605,-0.000295,-0.010119,0.033695,-0.067820,-0.021389,0.022009,0.055020,-0.094434,0.013761,0.056713,-0.049651,0.048126,-0.099841,-0.022538,0.077094,0.070519,-0.098684,-0.011535,0.026741,0.060796,0.073505,0.072355,-0.047605,0.001703,0.088197,-0.030249,0.029592,0.043072,-0.026665,0.007139,-0.053185,-0.053847,-0.034330,0.014471,-0.056053,-0.058262,0.029631,0.054520,0.027139,0.047965
3,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2026-03-23 13:31:06+00:00,Pfizer,0.038025,0.018858,-0.086595,0.008641,0.034031,-0.018835,0.076140,0.012036,0.033506,0.011971,0.063189,0.016846,0.076012,-0.084967,-0.045191,0.040121,0.061898,-0.002628,-0.024180,-0.058232,0.025985,-0.023125,-0.056735,0.033251,0.064188,0.080117,-0.064643,0.014658,-0.027111,-0.049216,-0.059584,-0.063907,0.061834,-0.099122,0.044907,0.019759,-0.036929,-0.049866,0.058166,-0.033384,-0.035382,0.026429,0.025998,0.103433,0.055798,0.024773,-0.017467,0.031075,-0.056646,-0.020733,-0.065451,0.031899,0.045822,0.057932,0.054153,-0.039517,-0.090263,-0.080082,-0.020314,-0.00266,0.092827,-0.051519,0.036129,-0.014263,0.040663,0.033581,-0.004201,0.033415,-0.060745,0.014824,-0.009569,0.043846,0.015037,-0.065885,0.031751,0.10263,0.049452,-0.019729,0.023484,0.011308,-0.059146,-0.077472,-0.029474,0.047105,-0.028209,0.081943,0.071144,-0.072979,0.081368,-0.023541,-0.024118,0.047241,-0.065265,-0.035430,-0.048655,-0.049407,-0.033535,0.096568,0.070078,-0.018527,0.082767,-0.074878,0.046550,-0.021118,-0.063131,0.019430,0.040776,-0.055604,0.085321,-0.074215,-0.028909,0.018009,0.069572,0.016697,-0.081627,-0.068889,-0.028755,-0.072625,0.012519,-0.044597,0.093571,-0.033167,-0.016155,-0.096866,-0.072974,-0.035678,0.016550,0.034578,0.063297,0.020400,0.015024,0.044000,0.056340,0.077235,0.081252,0.103822,-0.085244,-0.002350,-0.043159,-0.062273,-0.025932,0.095033,-0.035358,0.051496,0.056035,0.040303,0.051378,-0.028961,0.037197,-0.007587,0.035918,-0.060254,0.078566,0.034235,0.062392,-0.075872,-0.053853,-0.032895,0.033365,0.066921,-0.027530,-0.036516,-0.102985,0.014247,-0.028739,-0.022980,0.021429,0.064870,0.003385,-0.005851,-0.065104,0.047444,-0.039536,0.057797,0.012176,0.053917,-0.094062,-0.008078,0.057595,0.050228,-0.064663,-0.03288,-0.073867,-0.063811,-0.034164,-0.065423,-0.040367,0.063859,0.00845,-0.015013,0.024284,0.017185,-0.066683,-0.073007,-0.046892,0.071188,-0.052892,0.045286,0.020603,0.016777,-0.028692,-0.011352,0.048107,0.056427,0.016846,0.023313,-0.029326,0.067730,-0.037509,0.052975,0.067621,-0.068742,-0.074349,0.082270,-0.039638,-0.025498,0.021231,0.035030,-0.077371,0.030676,0.089377,-0.049328,0.047179,-0.072956,-0.005441,0.043417,0.080251,-0.047452,-0.053972,0.011236,-0.054727,-0.007871,-0.051056,-0.008326,-0.062684,-0.055155,-0.009197,0.060596,-0.000216,-0.038149,-0.075700,-0.015891,0.013155,-0.060592,0.071692,-0.032164,-0.054593,0.040430,0.021232,0.042799,0.047348,-0.058623,-0.070587,-0.003159,-0.044039,0.103689,0.067558,0.058313,-0.087304,0.038223,0.048917,-0.036565,0.045964,0.022143,0.047641,0.045015,-0.003066,-0.062033,-0.035443,-0.028948,-0.057692,0.036809,0.023672,0.003128,-0.054957,-0.045523,-0.010000,0.073081,-0.044362,-0.039034,0.045809,0.021007,0.022405,0.077515,0.060358,-0.021224,-0.01532,0.054028,-0.081312,-0.049697,-0.053018,-0.056819,0.063424,-0.021582,0.046387,0.056845,0.004724,0.062874,-0.041765,0.002014,-0.008127,-0.011316,0.035344,0.064695,-0.068760,0.012563,0.039127,0.043441,0.002915,0.023517,0.062379,0.050161,-0.030371,-0.025255,0.013294,0.069298,-0.033984,0.030053,-0.053445,-0.084558,-0.038507,-0.053299,-0.072722,-0.047565,-0.008606,0.040937,-0.037393,-0.038561,0.026209,-0.028136,0.013004,-0.038102,-0.030115,0.055816,-0.075088,-0.012603,0.014443,0.055649,-0.086399,-0.108251,0.007392,-0.012850,-0.034204,0.034605,-0.000295,-0.010119,0.033695,-0.067820,-0.021389,0.022009,0.055020,-0.094434,0.013761,0.056713,-0.049651,0.048126,-0.099841,-0.022538,0.077094,0.070519,-0.098684,-0.011535,0.026741,0.060796,0.073505,0.072355,-0.047605,0.001703,0.088197,-0.030249,0.029592,0.043072,-0.026665,0.007139,-0.053185,-0.053847,-0.034330,0.014471,-0.056053,-0.058262,0.029631,0.054520,0.027139,0.047965

In [331]:
data_f["webPublicationDate"]

0      2026-03-23 13:31:06+00:00
1      2026-03-23 13:31:06+00:00
2      2026-03-23 13:31:06+00:00
3      2026-03-23 13:31:06+00:00
4      2025-07-23 10:56:43+00:00
                  ...
8919   2025-04-22 08:42:26+00:00
8920   2025-07-23 18:40:37+00:00
8921   2025-02-10 06:17:04+00:00
8922   2025-03-28 05:00:12+00:00
8923   2025-04-17 17:21:57+00:00
Name: webPublicationDate, Length: 8924, dtype: datetime64[us, UTC]

Нам нужно вывести таргет для нашей модели. У нас в качестве таргета будет являться логарифм от процентного изменения цен. Изменение цен будем считать относительно последней цены, на которую текущая новость не повлияла - назовем такую цену P0. P1 - это цена закрытия в следующую торговую сессию. Pn - цена закрытия на n-ный торговую сессию после P0. А таргет соотвественно - log(Pn/P0) который мы будем считать для разных n с целью выявить лучший.

Чтобы получить последнюю цену закрытия, на которую текущая новость не повлияла, надо добавить само время закрытия в датасет котировок. В США это 20:00 для летнего времени и 21:00 для обычного:

In [332]:
quotes = pd.read_csv("quotes_all.csv", index_col=0)

In [333]:
quotes["Date"] = pd.to_datetime(quotes["Date"], utc=True)

In [334]:
quotes["is_summer"] = quotes["Date"].apply(lambda x: (x.month > 3 or (x.month == 3 and x.day >= 8)) and (x.month < 11 or (x.month == 11 and x.day < 1)))

In [335]:
quotes["Date"] = quotes["Date"] + pd.to_timedelta(np.where(quotes["is_summer"], "20:00:00", "21:00:00"))

In [336]:
quotes.head()

,ticker,Date,Open,High,Low,Close,Adj Close,Volume,is_summer
0,AAPL,2026-04-08 20:00:00+00:00,258.45,259.75,256.53,258.90,258.90,41008200.0,True
1,AAPL,2026-04-07 20:00:00+00:00,256.16,256.20,245.70,253.50,253.50,62148000.0,True
2,AAPL,2026-04-06 20:00:00+00:00,256.51,262.16,256.46,258.86,258.86,29329900.0,True
3,AAPL,2026-04-02 20:00:00+00:00,254.20,256.13,250.65,255.92,255.92,31289400.0,True
4,AAPL,2026-04-01 20:00:00+00:00,254.08,256.18,253.33,255.63,255.63,40059400.0,True

Приведем тикеры к названиям компаний

In [337]:
quotes["company"] = quotes["ticker"].map(mapping)

In [338]:
quotes.head()

,ticker,Date,Open,High,Low,Close,Adj Close,Volume,is_summer,company
0,AAPL,2026-04-08 20:00:00+00:00,258.45,259.75,256.53,258.90,258.90,41008200.0,True,Apple
1,AAPL,2026-04-07 20:00:00+00:00,256.16,256.20,245.70,253.50,253.50,62148000.0,True,Apple
2,AAPL,2026-04-06 20:00:00+00:00,256.51,262.16,256.46,258.86,258.86,29329900.0,True,Apple
3,AAPL,2026-04-02 20:00:00+00:00,254.20,256.13,250.65,255.92,255.92,31289400.0,True,Apple
4,AAPL,2026-04-01 20:00:00+00:00,254.08,256.18,253.33,255.63,255.63,40059400.0,True,Apple

Отсортируем все по дате

In [339]:
quotes = quotes.sort_values(["Date", "ticker"]).reset_index(drop=True)
data_f = data_f.sort_values(["webPublicationDate", "company"]).reset_index(drop=True)

Теперь создадим колонку с номером котировки для каждого тикера:

In [340]:
quotes["q_idx"] = quotes.groupby("ticker").cumcount()

In [341]:
quotes.head()

,ticker,Date,Open,High,Low,Close,Adj Close,Volume,is_summer,company,q_idx
0,AAPL,2020-12-31 21:00:00+00:00,134.08,134.74,131.72,132.69,129.05,99116600.0,False,Apple,0
1,CAT,2020-12-31 21:00:00+00:00,180.25,182.10,178.75,182.02,165.13,1717800.0,False,Caterpillar,0
2,JPM,2020-12-31 21:00:00+00:00,125.09,127.33,124.82,127.07,110.54,8580200.0,False,JPMorgan,0
3,NFLX,2020-12-31 21:00:00+00:00,52.55,54.55,52.31,54.07,54.07,53923000.0,False,Netflix,0
4,PFE,2020-12-31 21:00:00+00:00,36.66,36.92,36.29,36.81,28.37,30796500.0,False,Pfizer,0

Сначала найдем P0 - это самая поздняя цена закрытия на которую не повлияла новость. С этим нам поможет pd.merge_asof который делает мердж по ближайшему значению ключа.

In [342]:
data_f = pd.merge_asof(
    data_f,
    quotes,
    left_on="webPublicationDate",
    right_on="Date",
    by="company",
    direction="backward"
)

In [343]:
data_f.head()

,Benzinga,CNBC,ChartMill,DowJones,MarketWatch,SeekingAlpha,The Guardian,Yahoo,AAPL,TSLA,CAT,JPM,NFLX,PFE,XOM,WMT,webPublicationDate,company,emb_f_0,emb_f_1,emb_f_2,emb_f_3,emb_f_4,emb_f_5,emb_f_6,emb_f_7,emb_f_8,emb_f_9,emb_f_10,emb_f_11,emb_f_12,emb_f_13,emb_f_14,emb_f_15,emb_f_16,emb_f_17,emb_f_18,emb_f_19,emb_f_20,emb_f_21,emb_f_22,emb_f_23,emb_f_24,emb_f_25,emb_f_26,emb_f_27,emb_f_28,emb_f_29,emb_f_30,emb_f_31,emb_f_32,emb_f_33,emb_f_34,emb_f_35,emb_f_36,emb_f_37,emb_f_38,emb_f_39,emb_f_40,emb_f_41,emb_f_42,emb_f_43,emb_f_44,emb_f_45,emb_f_46,emb_f_47,emb_f_48,emb_f_49,emb_f_50,emb_f_51,emb_f_52,emb_f_53,emb_f_54,emb_f_55,emb_f_56,emb_f_57,emb_f_58,emb_f_59,emb_f_60,emb_f_61,emb_f_62,emb_f_63,emb_f_64,emb_f_65,emb_f_66,emb_f_67,emb_f_68,emb_f_69,emb_f_70,emb_f_71,emb_f_72,emb_f_73,emb_f_74,emb_f_75,emb_f_76,emb_f_77,emb_f_78,emb_f_79,emb_f_80,emb_f_81,emb_f_82,emb_f_83,emb_f_84,emb_f_85,emb_f_86,emb_f_87,emb_f_88,emb_f_89,emb_f_90,emb_f_91,emb_f_92,emb_f_93,emb_f_94,emb_f_95,emb_f_96,emb_f_97,emb_f_98,emb_f_99,emb_f_100,emb_f_101,emb_f_102,emb_f_103,emb_f_104,emb_f_105,emb_f_106,emb_f_107,emb_f_108,emb_f_109,emb_f_110,emb_f_111,emb_f_112,emb_f_113,emb_f_114,emb_f_115,emb_f_116,emb_f_117,emb_f_118,emb_f_119,emb_f_120,emb_f_121,emb_f_122,emb_f_123,emb_f_124,emb_f_125,emb_f_126,emb_f_127,emb_f_128,emb_f_129,emb_f_130,emb_f_131,emb_f_132,emb_f_133,emb_f_134,emb_f_135,emb_f_136,emb_f_137,emb_f_138,emb_f_139,emb_f_140,emb_f_141,emb_f_142,emb_f_143,emb_f_144,emb_f_145,emb_f_146,emb_f_147,emb_f_148,emb_f_149,emb_f_150,emb_f_151,emb_f_152,emb_f_153,emb_f_154,emb_f_155,emb_f_156,emb_f_157,emb_f_158,emb_f_159,emb_f_160,emb_f_161,emb_f_162,emb_f_163,emb_f_164,emb_f_165,emb_f_166,emb_f_167,emb_f_168,emb_f_169,emb_f_170,emb_f_171,emb_f_172,emb_f_173,emb_f_174,emb_f_175,emb_f_176,emb_f_177,emb_f_178,emb_f_179,emb_f_180,emb_f_181,emb_f_182,emb_f_183,emb_f_184,emb_f_185,emb_f_186,emb_f_187,emb_f_188,emb_f_189,emb_f_190,emb_f_191,emb_f_192,emb_f_193,emb_f_194,emb_f_195,emb_f_196,emb_f_197,emb_f_198,emb_f_199,emb_f_200,emb_f_201,emb_f_202,emb_f_203,emb_f_204,emb_f_205,emb_f_206,emb_f_207,emb_f_208,emb_f_209,emb_f_210,emb_f_211,emb_f_212,emb_f_213,emb_f_214,emb_f_215,emb_f_216,emb_f_217,emb_f_218,emb_f_219,emb_f_220,emb_f_221,emb_f_222,emb_f_223,emb_f_224,emb_f_225,emb_f_226,emb_f_227,emb_f_228,emb_f_229,emb_f_230,emb_f_231,emb_f_232,emb_f_233,emb_f_234,emb_f_235,emb_f_236,emb_f_237,emb_f_238,emb_f_239,emb_f_240,emb_f_241,emb_f_242,emb_f_243,emb_f_244,emb_f_245,emb_f_246,emb_f_247,emb_f_248,emb_f_249,emb_f_250,emb_f_251,emb_f_252,emb_f_253,emb_f_254,emb_f_255,emb_f_256,emb_f_257,emb_f_258,emb_f_259,emb_f_260,emb_f_261,emb_f_262,emb_f_263,emb_f_264,emb_f_265,emb_f_266,emb_f_267,emb_f_268,emb_f_269,emb_f_270,emb_f_271,emb_f_272,emb_f_273,emb_f_274,emb_f_275,emb_f_276,emb_f_277,emb_f_278,emb_f_279,emb_f_280,emb_f_281,emb_f_282,emb_f_283,emb_f_284,emb_f_285,emb_f_286,emb_f_287,emb_f_288,emb_f_289,emb_f_290,emb_f_291,emb_f_292,emb_f_293,emb_f_294,emb_f_295,emb_f_296,emb_f_297,emb_f_298,emb_f_299,emb_f_300,emb_f_301,emb_f_302,emb_f_303,emb_f_304,emb_f_305,emb_f_306,emb_f_307,emb_f_308,emb_f_309,emb_f_310,emb_f_311,emb_f_312,emb_f_313,emb_f_314,emb_f_315,emb_f_316,emb_f_317,emb_f_318,emb_f_319,emb_f_320,emb_f_321,emb_f_322,emb_f_323,emb_f_324,emb_f_325,emb_f_326,emb_f_327,emb_f_328,emb_f_329,emb_f_330,emb_f_331,emb_f_332,emb_f_333,emb_f_334,emb_f_335,emb_f_336,emb_f_337,emb_f_338,emb_f_339,emb_f_340,emb_f_341,emb_f_342,emb_f_343,emb_f_344,emb_f_345,emb_f_346,emb_f_347,emb_f_348,emb_f_349,emb_f_350,emb_f_351,emb_f_352,emb_f_353,emb_f_354,emb_f_355,emb_f_356,emb_f_357,emb_f_358,emb_f_359,emb_f_360,emb_f_361,emb_f_362,emb_f_363,emb_f_364,emb_f_365,emb_f_366,emb_f_367,emb_f_368,emb_f_369,emb_f_370,emb_f_371,emb_f_372,emb_f_373,emb_f_374,emb_f_375,emb_f_376,emb_f_377,emb_f_378,emb_f_379,emb_f_380,emb_f_381,emb_f_382,emb_f_383,ticker,Date,Open,High,Low,Close,Adj Close,Volume,is_summer,q_idx
0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021-01-01 13:00:51+00:00,Pfizer,0.059259,0.007487,-0.015668,-0.033080,0.075632,-0.043089,0.019307,0.035065,0.086168,-0.037493,0.055310,-0.009229,0.020876,-0.041060,-0.051384,0.080537,0.041877,-0.047560,-0.036163,-0.067759,0.003214,-0.004591,-0.025903,0.070868,0.049142,0.030289,-0.022079,-0.023458,0.060156,-0.090634,-0.053467,-0.043340,0.051362,-0.077349,0.031359,0.026728,-0.062109,-0.026018,0.081156,-0.052151,-0.043801,0.028645,0.020251,0.019834,0.080234,0.101874,-0.040118,0.060692,-0.037284,-0.047517,-0.074298,0.046549,0.039127,0.064814,0.067755,-0.061942,-0.086951,-0.058722,-0.075449,-0.009116,0.040136,-0.023694,0.042480,-0.005916,0.031794,0.082296,0.041507,0.039278,-0.102692,0.009944,-0.080504,0.039860,0.002057,-0.046410,0.066772,0.077178,0.026318,-0.037205,-0.031945,-0.049189,-0.070447,-0.077271,-0.041977,0.027611,-0.032297,0.075406,0.013831,-0.027618,0.043985,-0.004773,0.052411,0.016621,-0.030603,-0.038357,-0.053032,-0.084565,-0.042974,0.056633,0.040291,-0.042638,0.086704,-0.033583,0.070181,-0.022533,-0.053057,0.028202,0.018244,-0.039241,0.080705,-0.064698,-0.034769,0.046594,0.088182,0.047870,-0.062175,-0.073869,-0.028711,-0.027327,0.027037,-0.018626,0.059993,-0.057527,-0.039575,-0.082970,0.002779,0.034996,0.024955,0.058642,0.055786,-0.017115,0.007560,-0.002168,0.039379,0.022467,0.029455,0.083271,-0.024401,-0.004629,0.002424,-0.051231,-0.056002,0.065297,-0.020013,0.053318,0.061074,0.037349,0.067930,-0.019716,0.028043,-0.021097,0.022654,-0.048810,0.041925,-0.002896,0.043243,-0.035451,-0.075326,-0.041178,0.062578,0.050314,-0.036748,-0.034540,-0.077390,0.026180,-0.043121,-0.032361,0.024274,0.078871,-0.025995,-0.039805,-0.084107,0.036652,-0.098446,0.043535,-0.013199,0.044927,-0.054895,0.043257,0.019599,0.060143,-0.030433,-0.049232,-0.035526,-0.049454,-0.019861,-0.076021,-0.065607,0.041095,0.030341,0.014283,-0.056163,0.019752,-0.023515,-0.115443,-0.076642,0.010703,-0.060189,0.058464,0.015167,0.064163,-0.038649,-0.035009,0.033631,-0.003436,0.056266,0.004122,-0.015648,0.086866,-0.011702,0.045643,0.087957,-0.103093,-0.040813,0.016909,-0.050846,-0.000367,0.045517,0.049095,-0.036942,-0.014557,0.078155,-0.036174,0.033394,-0.064987,-0.018063,0.072469,0.044985,-0.030032,-0.061983,0.049594,-0.018554,-0.039772,-0.067975,-0.070110,-0.051068,-0.029293,-0.030862,0.037163,0.030010,-0.028889,-0.065460,-0.080835,0.077682,-0.086807,0.059088,-0.035246,-0.019072,0.030222,0.017273,0.065512,0.048751,-0.044164,-0.092447,-0.040366,-0.033785,0.041950,0.049359,0.086718,-0.113315,0.029333,0.022693,-0.012057,0.053425,0.055019,0.042695,0.071169,-0.034693,-0.002139,-0.065493,-0.016012,-0.069802,-0.007156,0.026445,-0.032349,-0.053463,-0.010422,-0.028300,0.112380,-0.073993,-0.081621,0.018824,0.047590,0.046295,0.041758,0.060232,0.011339,0.004216,0.046284,-0.050860,-0.082921,-0.041224,-0.091418,0.066058,-0.068348,0.091411,0.060748,-0.002516,0.082841,-0.045633,0.005532,-0.007642,-0.007469,0.078847,0.048250,-0.055685,0.006922,0.017805,0.037996,0.046008,0.023376,0.072609,0.028178,-0.042616,-0.036118,0.049493,0.045052,-0.052018,0.075940,-0.018811,-0.041187,-0.020276,-0.081327,-0.009940,-0.062511,-0.016888,0.064350,-0.008552,-0.010235,0.058184,0.019092,0.013183,-0.062677,-0.048732,0.068378,-0.053413,0.018226,0.020913,0.047004,-0.058330,-0.054102,0.005416,0.049701,-0.022220,0.016774,-0.023674,-0.029289,0.024439,-0.054443,-0.000524,0.035793,0.098039,-0.068576,-0.024366,0.042030,-0.023828,0.065074,-0.063265,-0.004079,0.047761,0.061015,-0.036344,-0.048766,0.067247,0.067159,0.069621,0.078849,-0.052437,-0.000602,0.075515,-0.029524,0.026727,0.083919,-0.073693,0.008715,-0.044979,-0.086176,-0.045433,0.035090,-0.071654,-0.063774,-0.016626,0.084948,-0.014749,0.077559,PFE,2020-12-31 21:00:00+00:00,36.66,36.92,36.29,36.81,28.37,30796500.0,False,0
1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021-01-04 00:01:21+00:00,Netflix,0.047792,0.001445,-0.040080,-0.078188,0.051086,-0.042682,0.013318,0.021551,0.064057,-0.012542,0.046625,-0.015098,0.067895,-0.055858,-0.027249,0.058310,0.025683,-0.043965,0.001967,-0.080565,0.029981,-0.008118,-0.058046,0.044832,0.066267,0.045458,-0.039336,-0.013071,0.046407,-0.087848,-0.053547,-0.017041,0.049360,-0.095884,0.065934,0.000356,-0.066844,-0.030714,0.073850,-0.000586,-0.012952,0.032946,0.022286,0.052035,0.058404,0.035929,0.012128,0.042769,-0.050692,-0.052416,-0.038813,0.087970,0.043304,0.144777,0.026967,-0.037466,-0.059154,-0.032794,-0.045162,-0.005729,0.102240,-0.071083,0.019851,0.038313,0.079179,0.069405,-0.023638,0.013692,-0.048353,-0.022775,-0.073731,0.055153,-0.013319,-0.077790,0.037887,0.059537,0.028230,-0.048096,0.027970,-0.065839,-0.083016,-0.052382,-0.025358,0.034937,-0.048567,0.064688,0.058386,-0.049928,0.082000,-0.028214,0.092065,0.048937,-0.060865,-0.050065,-0.077946,-0.088079,-0.069240,0.080889,0.098905,-0.062196,0.041758,-0.037153,0.063818,-0.018500,-0.022303,0.041997,0.045471,-0.080012,0.062347,-0.032986,-0.055952,0.030109,0.035471,0.009633,-0.037719,-0.060897,-0.033644,-0.016514,0.029652,-0.013280,0.027338,-0.065058,-0.068274,-0.092191,-0.057694,0.006463,0.023347,0.038662,0.067247,-0.002600,0.009079,0.021124,0.049594,0.044533,0.052880,0.079063,-0.064305,-0.009487,-0.022871,-0.010447,-0.048508,0.060738,-0.018608,0.076706,0.050534,0.066188,0.068096,-0.040877,0.067553,-0.035680,0.093134,-0.028115,0.070485,0.052714,0.060768,-0.059337,-0.060383,-0.088482,0.052204,0.057898,-0.052930,-0.064668,-0.076554,0.006188,-0.080752,-0.054653,0.061772,0.084223,-0.015264,-0.034264,-0.082969,0.064493,-0.045631,0.027776,-0.021610,0.061397,-0.096151,0.007184,0.037133,0.006587,-0.042629,-0.061104,-0.045008,-0.036378,-0.042893,-0.063835,-0.050367,0.003728,0.022595,-0.005866,-0.034486,0.052833,-0.054716,-0.050817,-0.018723,0.071100,-0.027076,0.069523,0.018684,0.023263,-0.038151,-0.020998,0.048143,0.008673,0.074800,0.014647,-0.065626,0.120862,-0.020183,0.034883,0.019383,-0.128053,-0.049995,0.057253,-0.060028,-0.030201,0.004291,0.035400,-0.048186,0.009235,0.048681,-0.035821,0.050747,-0.094488,-0.037466,0.041805,0.089367,-0.047273,-0.028192,0.058658,-0.082337,0.002733,-0.058980,-0.064370,-0.017112,-0.012253,-0.023510,0.019539,-0.008512,-0.004581,-0.058151,-0.034106,0.028757,-0.059656,0.044554,-0.033982,-0.009663,-0.002616,-0.012164,0.018048,0.052853,-0.041034,-0.040566,-0.054692,-0.061545,0.029659,0.085421,0.056420,-0.029607,0.043360,0.057405,-0.030946,0.065672,0.004534,0.024049,0.062804,-0.040162,-0.060229,-0.064951,-0.047519,-0.068916,0.036946,0.015951,-0.026038,-0.058720,-0.041866,-0.007710,0.101009,-0.040098,-0.005335,0.047577,0.023763,-0.002431,0.031709,0.025012,0.018573,-0.032784,0.087172,-0.067739,-0.052579,0.013876,-0.056487,0.071549,-0.030634,0.065407,0.055548,-0.047788,0.056984,-0.054578,-0.026309,-0.001502,0.003553,0.023502,0.037263,-0.065122,-0.003780,-0.006991,0.040262,0.014069,0.002477,0.089288,0.012848,-0.012951,-0.040793,0.099930,0.033918,-0.053577,0.035380,-0.019360,-0.053224,-0.051774,-0.052262,-0.040525,-0.043103,0.038138,0.036570,-0.035359,-0.041915,0.042328,0.034480,0.051483,-0.097394,-0.072801,0.075454,-0.084328,-0.004500,0.030548,0.039575,-0.043761,-0.085080,0.036278,0.028949,-0.030944,0.004584,-0.029347,-0.018310,0.032665,-0.052470,-0.044237,0.014714,0.016143,-0.070779,0.020871,0.035204,-0.024469,0.071300,-0.029881,-0.023685,0.010325,0.065242,-0.062330,0.021950,0.085265,0.077098,0.068979,0.077064,0.000470,-0.007379,0.067449,-0.010152,0.069533,0.114299,-0.052543,0.008099,-0.033814,-0.039121,0.000907,0.046109,-0.018527,-0.066928,-0.008529,0.044927,0.002228,0.055057,NFLX,2020-12-31 21:00:00+00:00,52.55,54.55,52.31,54.07,54.07,53923000.0,False,0
2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021-01-04 20:49:54+00:00,Pfizer,0.036805,-0.027506,-0.048388,-0.040726,0.040053,-0.006731,0.081135,0.008891,0.075858,0.014055,0.074672,0.029109,0.076591,-0.043322,-0.064973,0.068652,0.025357,-0.041616,-0.035701,-0.077821,0.000456,-0.021876,-0.039561,0.051064,0.057590,0.061622,-0.066996,0.015509,0.034123,-0.009054,-0.067450,-0.026688,0.032115,-0.095022,0.049261,0.017475,-0.039234,-0.072958,0.040455,-0.059622,-0.037896,0.029887,0.030661,0.095122,0.053451,0.061516,-0.029177,0.018639,-0.049888,-0.040357,-0.046010,0.072490,0.033571,0.054400,0.036722,-0.019873,-0.097126,-0.090899,-0.073045,0.034678,0.020068,-0.058582,0.024871,0.008448,0.042339,0.057344,0.031088,0.066256,-0.079391,0.008321,-0.074428,0.043484,0.020874,-0.026803,0.027917,0.054116,0.017360,-0.016600,0.032667,-0.008850,-0.080521,-0.055549,-0.026288,-0.000810,-0.022667,0.048786,0.042327,-0.054137,0.103502,-0.032193,-0.002719,0.028224,-0.073313,-0.062403,-0.047794,-0.068902,-0.090807,0.062189,0.087045,-0.029851,0.076648,-0.093838,0.050008,-0.013476,-0.054428,0.056168,-0.023001,-0.065126,0.092232,-0.077231,-0.001900,0.035070,0.024325,0.025107,-0.062669,-0.012852,-0.032900,-0.060606,0.039650,-0.031311,0.035329,-0.022410,-0.043565,-0.119826,-0.051872,-0.011683,0.003541,0.042145,0.060390,0.013529,0.032518,-0.000265,0.055520,0.021559,0.036222,0.102320,-0.061064,-0.029183,-0.002803,-0.017822,-0.043875,0.079351,-0.073118,0.059235,0.052028,0.082007,0.082527,-0.034164,0.056269,0.017795,0.030285,-0.103270,0.043168,0.018351,0.058859,-0.072924,-0.060295,-0.026471,0.035466,0.047334,-0.041739,-0.044487,-0.059543,0.018080,-0.063768,0.027510,0.039074,0.037864,-0.006257,-0.018784,-0.010361,0.085946,-0.068684,0.100764,-0.033956,0.027580,-0.065664,0.039798,0.078443,0.042805,-0.074347,-0.052344,-0.094733,-0.044154,-0.041340,0.001137,-0.041041,-0.006888,0.072732,-0.041070,-0.022663,0.054498,-0.068665,-0.050721,-0.075087,-0.006067,-0.030962,0.073286,0.071611,0.053888,-0.016479,-0.055896,0.044512,0.040838,0.029861,0.007483,-0.041284,0.085835,-0.025272,0.051915,0.034464,-0.094259,-0.051513,0.033495,-0.015682,-0.033285,0.010765,0.059418,-0.028976,0.044939,0.087140,-0.009401,0.030354,-0.051312,-0.026916,0.053288,0.074892,-0.054872,-0.039904,0.050897,-0.000941,-0.056355,-0.039955,-0.058512,-0.049086,-0.032905,-0.024052,0.043195,0.032334,-0.065705,-0.061025,-0.046714,0.060284,-0.063991,0.037242,-0.070329,-0.049430,0.019549,-0.045577,0.033325,0.058467,-0.073713,-0.076606,-0.038997,-0.024900,0.086982,0.022154,0.114401,-0.071691,0.013226,0.029465,0.024323,0.047010,0.057251,0.028921,0.016031,-0.009130,-0.012833,-0.083526,-0.080207,-0.094836,0.067800,0.002916,-0.011863,-0.057935,-0.014379,0.010808,0.092447,-0.048974,-0.069911,0.060663,0.010711,0.011420,0.050975,0.036483,-0.043400,-0.046667,0.113614,-0.058746,-0.029529,-0.043023,-0.050210,0.064698,-0.021284,0.068554,0.031574,-0.019458,0.063015,-0.061215,0.025430,0.028496,-0.033692,0.033615,0.021906,-0.079536,0.020031,0.000547,0.054006,0.042085,0.016515,0.038001,0.055986,-0.036938,-0.032942,0.034612,0.021597,-0.035925,0.056889,-0.032938,-0.091962,-0.048716,-0.050860,-0.019910,-0.050751,0.009988,0.046199,-0.043971,-0.078462,0.066558,0.014105,0.033329,-0.034367,-0.078884,0.057800,-0.060036,-0.025674,0.027141,-0.006239,-0.047979,-0.045784,-0.009838,0.035673,-0.022711,0.067075,-0.013000,-0.013152,0.031424,-0.052962,-0.014834,0.026812,0.081459,-0.101403,-0.009793,0.060702,-0.031667,0.067724,-0.055758,0.013436,0.040733,0.028071,-0.071255,-0.011857,0.045139,0.031231,0.062167,0.039153,-0.012582,0.022815,0.061133,0.000866,0.061504,0.104487,-0.015751,0.010918,-0.025938,-0.045824,-0.079215,0.041629,-0.035795,-0.002819,0.094213,0.021634,-0.008866,0.035121,PFE,2020-12-31 21:00:00+00:00,36.66,36.92,36.29,36.81,28.37,30796500.0,False,0
3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021-01-05 15:54:23+00:00,JPMorgan,0.029022,-0.016270,-0.066375,-0.066625,0.064859,-0.033808,0.044932,0.011742,0.087957,0.012203,0.062685,-0.031317,0.068230,-0.066987,-0.036981,0.069115,0.009701,-0.062004,-0.030296,-0.062517,0.003003,-0.015636,-0.043285,0.052388,0.026851,0.055437,-0.044009,0.001738,0.029191,-0.067376,-0.053348,-0.009064,0.051702,-0.071396,0.022669,0.028637,-0.064904,-0.031397,0.068926,-0.083838,-0.002352,0.024613,0.035272,0.082471,0.055671,0.061462,-0.015167,0.009224,-0.038014,-0.062918,-0.021883,0.069536,0.010240,0.082714,0.042624,-0.032025,-0.102738,-0.069957,-0.096355,-0.000149,0.060537,-0.074194,0.006531,0.059349,0.099153,0.061784,0.012862,-0.003770,-0.073383,-0.022838,-0.060146,0.035002,-0.015519,-0.010176,0.047379,0.005680,0.045569,-0.033581,0.019958,-0.027030,-0.070458,-0.060288,-0.032470,0.058552,-0.075034,0.044682,0.068279,-0.030000,0.088509,-0.045743,0.055654,0.065439,-0.043458,-0.055266,-0.032108,-0.083046,-0.071972,0.073941,0.096345,-0.028362,0.063371,-0.047657,0.051805,-0.029768,-0.063940,-0.013781,0.011770,-0.033152,0.082323,-0.056371,-0.057948,0.041430,0.099079,0.032905,-0.035256,-0.019486,0.000414,-0.037507,0.047708,-0.047281,0.043285,-0.056768,-0.062146,-0.076288,-0.076663,0.009534,-0.002518,0.036098,0.064538,-0.022784,0.037298,-0.006229,0.068474,-0.007193,0.069562,0.072963,-0.044376,-0.022996,-0.006723,-0.064453,-0.049166,0.084476,-0.029053,0.041853,0.068594,0.079118,0.062922,-0.025013,0.061369,-0.010847,0.046556,-0.046484,0.047522,0.039016,0.049876,-0.081303,-0.042686,-0.056342,0.043192,0.061678,-0.083921,-0.071968,-0.110361,-0.007301,-0.093663,-0.055478,0.047985,0.071981,-0.021376,0.001776,-0.094216,0.036546,-0.024116,0.065709,-0.016084,0.103263,-0.059913,0.032380,0.043096,-0.003029,-0.035088,-0.051549,-0.030527,-0.024928,-0.062951,-0.024719,-0.057951,0.022463,0.037687,-0.030386,-0.020927,0.050022,-0.035025,-0.064035,-0.032578,0.069251,-0.028669,0.030994,0.022243,0.011806,-0.020707,-0.056799,0.063038,0.014189,0.072400,0.045622,-0.030111,0.079326,-0.005963,0.047177,0.066473,-0.109442,-0.069669,0.049918,0.006148,0.001105,-0.019101,0.042769,-0.076884,0.044486,0.047289,-0.039315,0.035306,-0.055436,-0.018868,0.059469,0.084390,-0.038684,-0.030422,0.059389,-0.028114,-0.011845,-0.049515,-0.062076,-0.035260,-0.038838,-0.056301,0.061553,0.048747,-0.022103,-0.056002,-0.056529,0.027511,-0.048716,0.026068,-0.020409,-0.007035,-0.039333,-0.027490,0.003200,0.039522,-0.016430,-0.088547,-0.070166,-0.029898,0.074799,0.075844,0.068458,-0.048245,0.045105,0.068603,0.004150,0.063756,0.081880,0.040008,0.050947,0.014974,-0.001117,-0.046869,-0.021069,-0.041040,0.058100,0.043013,-0.018521,-0.096580,-0.033299,-0.020267,0.096931,-0.063156,-0.021678,0.071228,0.042267,-0.000213,0.045175,0.022208,-0.008374,-0.027624,0.090635,-0.014417,-0.031268,-0.023322,-0.086649,0.075811,-0.016766,0.075227,0.066027,-0.016511,0.049635,-0.099077,0.014663,0.005002,-0.032600,0.008073,0.026475,-0.071074,0.011986,0.013823,0.002524,0.047870,-0.005482,0.040105,0.043364,-0.032887,-0.060117,0.080142,0.061581,-0.043363,0.064902,-0.039642,-0.035594,-0.054732,-0.054155,0.009874,-0.071179,0.001093,0.064999,0.016972,-0.031374,0.053309,-0.000351,0.037263,-0.066626,-0.076712,0.052555,-0.057472,-0.010476,0.039801,0.014742,-0.027424,-0.053057,-0.008642,-0.002359,-0.018012,0.011740,-0.015720,-0.032374,0.006010,-0.051030,-0.061374,0.038956,0.025524,-0.066950,0.011525,0.004070,-0.043926,0.057184,-0.062861,-0.038186,-0.003104,0.049269,-0.082682,-0.036356,0.046726,0.059852,0.067382,0.075083,-0.039401,0.006332,0.064130,-0.042416,0.075016,0.076891,-0.068939,0.027721,-0.070832,-0.078999,-0.026664,0.060119,-0.035614,-0.053950,0.030930,0.080632,-0.010865,0.060700,JPM,2021-01-04 21:00:00+00:00,127.50,127.86,124.78,125.87,109.49,16819900.0,False,1

Собственно Adj Close в самом конце это и есть наша P0. Как получить P1, P2 и следующие? Поскольку датафрейм уже отсортирован в рамках тикера, то мы пройтись по ним и построить матрицу будущих цен:

In [344]:
for k in range(31):
    quotes[f"P{k}"] = quotes.groupby("ticker")["Adj Close"].shift(-k)

In [345]:
quotes.head()

,ticker,Date,Open,High,Low,Close,Adj Close,Volume,is_summer,company,q_idx,P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30
0,AAPL,2020-12-31 21:00:00+00:00,134.08,134.74,131.72,132.69,129.05,99116600.0,False,Apple,0,129.05,125.86,127.41,123.12,127.33,128.42,125.44,125.26,127.30,125.37,123.65,124.32,128.40,133.11,135.25,139.00,139.23,138.16,133.33,128.34,130.46,131.28,130.26,133.62,133.20,133.35,132.47,131.87,131.62,131.85,129.73
1,CAT,2020-12-31 21:00:00+00:00,180.25,182.10,178.75,182.02,165.13,1717800.0,False,Caterpillar,0,165.13,165.24,166.60,175.87,176.20,176.23,175.87,179.20,177.71,179.08,176.56,176.98,175.42,175.28,175.05,170.86,170.74,164.74,168.12,166.75,168.47,175.56,174.60,174.79,176.02,180.08,179.92,180.32,180.90,180.57,184.57
2,JPM,2020-12-31 21:00:00+00:00,125.09,127.33,124.82,127.07,110.54,8580200.0,False,JPMorgan,0,110.54,109.49,110.09,115.26,119.04,119.17,120.95,122.85,122.97,123.69,121.47,120.94,119.13,118.13,117.22,115.76,115.28,112.02,113.99,112.73,113.57,117.06,118.40,121.13,120.89,122.78,122.29,122.36,122.02,123.76,126.73
3,NFLX,2020-12-31 21:00:00+00:00,52.55,54.55,52.31,54.07,54.07,53923000.0,False,Netflix,0,54.07,52.29,52.08,50.05,50.89,51.04,49.91,49.42,50.78,50.09,49.80,50.18,58.63,57.98,56.52,55.68,56.19,52.33,53.86,53.24,53.90,54.82,53.94,55.22,55.08,54.79,55.91,56.36,55.76,55.65,55.73
4,PFE,2020-12-31 21:00:00+00:00,36.66,36.92,36.29,36.81,28.37,30796500.0,False,Pfizer,0,28.37,28.37,28.66,28.41,28.56,28.61,29.11,28.65,28.41,28.32,28.28,28.31,28.13,28.11,28.17,28.73,28.75,27.93,27.94,27.97,27.89,27.26,27.14,27.18,27.20,27.13,27.24,27.06,26.82,27.05,27.02

Осталось только присоединить эти значения к исходному датасету:

In [346]:
data_f = data_f.merge(
    quotes[["company", "q_idx"] + [f"P{k}" for k in range(31)]],
    on=["company", "q_idx"],
    how="left"
)

In [347]:
data_f.head()

,Benzinga,CNBC,ChartMill,DowJones,MarketWatch,SeekingAlpha,The Guardian,Yahoo,AAPL,TSLA,CAT,JPM,NFLX,PFE,XOM,WMT,webPublicationDate,company,emb_f_0,emb_f_1,emb_f_2,emb_f_3,emb_f_4,emb_f_5,emb_f_6,emb_f_7,emb_f_8,emb_f_9,emb_f_10,emb_f_11,emb_f_12,emb_f_13,emb_f_14,emb_f_15,emb_f_16,emb_f_17,emb_f_18,emb_f_19,emb_f_20,emb_f_21,emb_f_22,emb_f_23,emb_f_24,emb_f_25,emb_f_26,emb_f_27,emb_f_28,emb_f_29,emb_f_30,emb_f_31,emb_f_32,emb_f_33,emb_f_34,emb_f_35,emb_f_36,emb_f_37,emb_f_38,emb_f_39,emb_f_40,emb_f_41,emb_f_42,emb_f_43,emb_f_44,emb_f_45,emb_f_46,emb_f_47,emb_f_48,emb_f_49,emb_f_50,emb_f_51,emb_f_52,emb_f_53,emb_f_54,emb_f_55,emb_f_56,emb_f_57,emb_f_58,emb_f_59,emb_f_60,emb_f_61,emb_f_62,emb_f_63,emb_f_64,emb_f_65,emb_f_66,emb_f_67,emb_f_68,emb_f_69,emb_f_70,emb_f_71,emb_f_72,emb_f_73,emb_f_74,emb_f_75,emb_f_76,emb_f_77,emb_f_78,emb_f_79,emb_f_80,emb_f_81,emb_f_82,emb_f_83,emb_f_84,emb_f_85,emb_f_86,emb_f_87,emb_f_88,emb_f_89,emb_f_90,emb_f_91,emb_f_92,emb_f_93,emb_f_94,emb_f_95,emb_f_96,emb_f_97,emb_f_98,emb_f_99,emb_f_100,emb_f_101,emb_f_102,emb_f_103,emb_f_104,emb_f_105,emb_f_106,emb_f_107,emb_f_108,emb_f_109,emb_f_110,emb_f_111,emb_f_112,emb_f_113,emb_f_114,emb_f_115,emb_f_116,emb_f_117,emb_f_118,emb_f_119,emb_f_120,emb_f_121,emb_f_122,emb_f_123,emb_f_124,emb_f_125,emb_f_126,emb_f_127,emb_f_128,emb_f_129,emb_f_130,emb_f_131,emb_f_132,emb_f_133,emb_f_134,emb_f_135,emb_f_136,emb_f_137,emb_f_138,emb_f_139,emb_f_140,emb_f_141,emb_f_142,emb_f_143,emb_f_144,emb_f_145,emb_f_146,emb_f_147,emb_f_148,emb_f_149,emb_f_150,emb_f_151,emb_f_152,emb_f_153,emb_f_154,emb_f_155,emb_f_156,emb_f_157,emb_f_158,emb_f_159,emb_f_160,emb_f_161,emb_f_162,emb_f_163,emb_f_164,emb_f_165,emb_f_166,emb_f_167,emb_f_168,emb_f_169,emb_f_170,emb_f_171,emb_f_172,emb_f_173,emb_f_174,emb_f_175,emb_f_176,emb_f_177,emb_f_178,emb_f_179,emb_f_180,emb_f_181,emb_f_182,emb_f_183,emb_f_184,emb_f_185,emb_f_186,emb_f_187,emb_f_188,emb_f_189,emb_f_190,emb_f_191,emb_f_192,emb_f_193,emb_f_194,emb_f_195,emb_f_196,emb_f_197,emb_f_198,emb_f_199,emb_f_200,emb_f_201,emb_f_202,emb_f_203,emb_f_204,emb_f_205,emb_f_206,emb_f_207,emb_f_208,emb_f_209,emb_f_210,emb_f_211,emb_f_212,emb_f_213,emb_f_214,emb_f_215,emb_f_216,emb_f_217,emb_f_218,emb_f_219,emb_f_220,emb_f_221,emb_f_222,emb_f_223,emb_f_224,emb_f_225,emb_f_226,emb_f_227,emb_f_228,emb_f_229,emb_f_230,emb_f_231,emb_f_232,emb_f_233,emb_f_234,emb_f_235,emb_f_236,emb_f_237,emb_f_238,emb_f_239,emb_f_240,emb_f_241,emb_f_242,emb_f_243,emb_f_244,emb_f_245,emb_f_246,emb_f_247,emb_f_248,emb_f_249,emb_f_250,emb_f_251,emb_f_252,emb_f_253,emb_f_254,emb_f_255,emb_f_256,emb_f_257,emb_f_258,emb_f_259,emb_f_260,emb_f_261,emb_f_262,emb_f_263,emb_f_264,emb_f_265,emb_f_266,emb_f_267,emb_f_268,emb_f_269,emb_f_270,emb_f_271,emb_f_272,emb_f_273,emb_f_274,emb_f_275,emb_f_276,emb_f_277,emb_f_278,emb_f_279,emb_f_280,emb_f_281,emb_f_282,emb_f_283,emb_f_284,emb_f_285,emb_f_286,emb_f_287,emb_f_288,emb_f_289,emb_f_290,emb_f_291,emb_f_292,emb_f_293,emb_f_294,emb_f_295,emb_f_296,emb_f_297,emb_f_298,emb_f_299,emb_f_300,emb_f_301,emb_f_302,emb_f_303,emb_f_304,emb_f_305,emb_f_306,emb_f_307,emb_f_308,emb_f_309,emb_f_310,emb_f_311,emb_f_312,emb_f_313,emb_f_314,emb_f_315,emb_f_316,emb_f_317,emb_f_318,emb_f_319,emb_f_320,emb_f_321,emb_f_322,emb_f_323,emb_f_324,emb_f_325,emb_f_326,emb_f_327,emb_f_328,emb_f_329,emb_f_330,emb_f_331,emb_f_332,emb_f_333,emb_f_334,emb_f_335,emb_f_336,emb_f_337,emb_f_338,emb_f_339,emb_f_340,emb_f_341,emb_f_342,emb_f_343,emb_f_344,emb_f_345,emb_f_346,emb_f_347,emb_f_348,emb_f_349,emb_f_350,emb_f_351,emb_f_352,emb_f_353,emb_f_354,emb_f_355,emb_f_356,emb_f_357,emb_f_358,emb_f_359,emb_f_360,emb_f_361,emb_f_362,emb_f_363,emb_f_364,emb_f_365,emb_f_366,emb_f_367,emb_f_368,emb_f_369,emb_f_370,emb_f_371,emb_f_372,emb_f_373,emb_f_374,emb_f_375,emb_f_376,emb_f_377,emb_f_378,emb_f_379,emb_f_380,emb_f_381,emb_f_382,emb_f_383,ticker,Date,Open,High,Low,Close,Adj Close,Volume,is_summer,q_idx,P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30
0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021-01-01 13:00:51+00:00,Pfizer,0.059259,0.007487,-0.015668,-0.033080,0.075632,-0.043089,0.019307,0.035065,0.086168,-0.037493,0.055310,-0.009229,0.020876,-0.041060,-0.051384,0.080537,0.041877,-0.047560,-0.036163,-0.067759,0.003214,-0.004591,-0.025903,0.070868,0.049142,0.030289,-0.022079,-0.023458,0.060156,-0.090634,-0.053467,-0.043340,0.051362,-0.077349,0.031359,0.026728,-0.062109,-0.026018,0.081156,-0.052151,-0.043801,0.028645,0.020251,0.019834,0.080234,0.101874,-0.040118,0.060692,-0.037284,-0.047517,-0.074298,0.046549,0.039127,0.064814,0.067755,-0.061942,-0.086951,-0.058722,-0.075449,-0.009116,0.040136,-0.023694,0.042480,-0.005916,0.031794,0.082296,0.041507,0.039278,-0.102692,0.009944,-0.080504,0.039860,0.002057,-0.046410,0.066772,0.077178,0.026318,-0.037205,-0.031945,-0.049189,-0.070447,-0.077271,-0.041977,0.027611,-0.032297,0.075406,0.013831,-0.027618,0.043985,-0.004773,0.052411,0.016621,-0.030603,-0.038357,-0.053032,-0.084565,-0.042974,0.056633,0.040291,-0.042638,0.086704,-0.033583,0.070181,-0.022533,-0.053057,0.028202,0.018244,-0.039241,0.080705,-0.064698,-0.034769,0.046594,0.088182,0.047870,-0.062175,-0.073869,-0.028711,-0.027327,0.027037,-0.018626,0.059993,-0.057527,-0.039575,-0.082970,0.002779,0.034996,0.024955,0.058642,0.055786,-0.017115,0.007560,-0.002168,0.039379,0.022467,0.029455,0.083271,-0.024401,-0.004629,0.002424,-0.051231,-0.056002,0.065297,-0.020013,0.053318,0.061074,0.037349,0.067930,-0.019716,0.028043,-0.021097,0.022654,-0.048810,0.041925,-0.002896,0.043243,-0.035451,-0.075326,-0.041178,0.062578,0.050314,-0.036748,-0.034540,-0.077390,0.026180,-0.043121,-0.032361,0.024274,0.078871,-0.025995,-0.039805,-0.084107,0.036652,-0.098446,0.043535,-0.013199,0.044927,-0.054895,0.043257,0.019599,0.060143,-0.030433,-0.049232,-0.035526,-0.049454,-0.019861,-0.076021,-0.065607,0.041095,0.030341,0.014283,-0.056163,0.019752,-0.023515,-0.115443,-0.076642,0.010703,-0.060189,0.058464,0.015167,0.064163,-0.038649,-0.035009,0.033631,-0.003436,0.056266,0.004122,-0.015648,0.086866,-0.011702,0.045643,0.087957,-0.103093,-0.040813,0.016909,-0.050846,-0.000367,0.045517,0.049095,-0.036942,-0.014557,0.078155,-0.036174,0.033394,-0.064987,-0.018063,0.072469,0.044985,-0.030032,-0.061983,0.049594,-0.018554,-0.039772,-0.067975,-0.070110,-0.051068,-0.029293,-0.030862,0.037163,0.030010,-0.028889,-0.065460,-0.080835,0.077682,-0.086807,0.059088,-0.035246,-0.019072,0.030222,0.017273,0.065512,0.048751,-0.044164,-0.092447,-0.040366,-0.033785,0.041950,0.049359,0.086718,-0.113315,0.029333,0.022693,-0.012057,0.053425,0.055019,0.042695,0.071169,-0.034693,-0.002139,-0.065493,-0.016012,-0.069802,-0.007156,0.026445,-0.032349,-0.053463,-0.010422,-0.028300,0.112380,-0.073993,-0.081621,0.018824,0.047590,0.046295,0.041758,0.060232,0.011339,0.004216,0.046284,-0.050860,-0.082921,-0.041224,-0.091418,0.066058,-0.068348,0.091411,0.060748,-0.002516,0.082841,-0.045633,0.005532,-0.007642,-0.007469,0.078847,0.048250,-0.055685,0.006922,0.017805,0.037996,0.046008,0.023376,0.072609,0.028178,-0.042616,-0.036118,0.049493,0.045052,-0.052018,0.075940,-0.018811,-0.041187,-0.020276,-0.081327,-0.009940,-0.062511,-0.016888,0.064350,-0.008552,-0.010235,0.058184,0.019092,0.013183,-0.062677,-0.048732,0.068378,-0.053413,0.018226,0.020913,0.047004,-0.058330,-0.054102,0.005416,0.049701,-0.022220,0.016774,-0.023674,-0.029289,0.024439,-0.054443,-0.000524,0.035793,0.098039,-0.068576,-0.024366,0.042030,-0.023828,0.065074,-0.063265,-0.004079,0.047761,0.061015,-0.036344,-0.048766,0.067247,0.067159,0.069621,0.078849,-0.052437,-0.000602,0.075515,-0.029524,0.026727,0.083919,-0.073693,0.008715,-0.044979,-0.086176,-0.045433,0.035090,-0.071654,-0.063774,-0.016626,0.084948,-0.014749,0.077559,PFE,2020-12-31 21:00:00+00:00,36.66,36.92,36.29,36.81,28.37,30796500.0,False,0,28.37,28.37,28.66,28.41,28.56,28.61,29.11,28.65,28.41,28.32,28.28,28.31,28.13,28.11,28.17,28.73,28.75,27.93,27.94,27.97,27.89,27.26,27.14,27.18,27.20,27.13,27.24,27.06,26.82,27.05,27.02
1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021-01-04 00:01:21+00:00,Netflix,0.047792,0.001445,-0.040080,-0.078188,0.051086,-0.042682,0.013318,0.021551,0.064057,-0.012542,0.046625,-0.015098,0.067895,-0.055858,-0.027249,0.058310,0.025683,-0.043965,0.001967,-0.080565,0.029981,-0.008118,-0.058046,0.044832,0.066267,0.045458,-0.039336,-0.013071,0.046407,-0.087848,-0.053547,-0.017041,0.049360,-0.095884,0.065934,0.000356,-0.066844,-0.030714,0.073850,-0.000586,-0.012952,0.032946,0.022286,0.052035,0.058404,0.035929,0.012128,0.042769,-0.050692,-0.052416,-0.038813,0.087970,0.043304,0.144777,0.026967,-0.037466,-0.059154,-0.032794,-0.045162,-0.005729,0.102240,-0.071083,0.019851,0.038313,0.079179,0.069405,-0.023638,0.013692,-0.048353,-0.022775,-0.073731,0.055153,-0.013319,-0.077790,0.037887,0.059537,0.028230,-0.048096,0.027970,-0.065839,-0.083016,-0.052382,-0.025358,0.034937,-0.048567,0.064688,0.058386,-0.049928,0.082000,-0.028214,0.092065,0.048937,-0.060865,-0.050065,-0.077946,-0.088079,-0.069240,0.080889,0.098905,-0.062196,0.041758,-0.037153,0.063818,-0.018500,-0.022303,0.041997,0.045471,-0.080012,0.062347,-0.032986,-0.055952,0.030109,0.035471,0.009633,-0.037719,-0.060897,-0.033644,-0.016514,0.029652,-0.013280,0.027338,-0.065058,-0.068274,-0.092191,-0.057694,0.006463,0.023347,0.038662,0.067247,-0.002600,0.009079,0.021124,0.049594,0.044533,0.052880,0.079063,-0.064305,-0.009487,-0.022871,-0.010447,-0.048508,0.060738,-0.018608,0.076706,0.050534,0.066188,0.068096,-0.040877,0.067553,-0.035680,0.093134,-0.028115,0.070485,0.052714,0.060768,-0.059337,-0.060383,-0.088482,0.052204,0.057898,-0.052930,-0.064668,-0.076554,0.006188,-0.080752,-0.054653,0.061772,0.084223,-0.015264,-0.034264,-0.082969,0.064493,-0.045631,0.027776,-0.021610,0.061397,-0.096151,0.007184,0.037133,0.006587,-0.042629,-0.061104,-0.045008,-0.036378,-0.042893,-0.063835,-0.050367,0.003728,0.022595,-0.005866,-0.034486,0.052833,-0.054716,-0.050817,-0.018723,0.071100,-0.027076,0.069523,0.018684,0.023263,-0.038151,-0.020998,0.048143,0.008673,0.074800,0.014647,-0.065626,0.120862,-0.020183,0.034883,0.019383,-0.128053,-0.049995,0.057253,-0.060028,-0.030201,0.004291,0.035400,-0.048186,0.009235,0.048681,-0.035821,0.050747,-0.094488,-0.037466,0.041805,0.089367,-0.047273,-0.028192,0.058658,-0.082337,0.002733,-0.058980,-0.064370,-0.017112,-0.012253,-0.023510,0.019539,-0.008512,-0.004581,-0.058151,-0.034106,0.028757,-0.059656,0.044554,-0.033982,-0.009663,-0.002616,-0.012164,0.018048,0.052853,-0.041034,-0.040566,-0.054692,-0.061545,0.029659,0.085421,0.056420,-0.029607,0.043360,0.057405,-0.030946,0.065672,0.004534,0.024049,0.062804,-0.040162,-0.060229,-0.064951,-0.047519,-0.068916,0.036946,0.015951,-0.026038,-0.058720,-0.041866,-0.007710,0.101009,-0.040098,-0.005335,0.047577,0.023763,-0.002431,0.031709,0.025012,0.018573,-0.032784,0.087172,-0.067739,-0.052579,0.013876,-0.056487,0.071549,-0.030634,0.065407,0.055548,-0.047788,0.056984,-0.054578,-0.026309,-0.001502,0.003553,0.023502,0.037263,-0.065122,-0.003780,-0.006991,0.040262,0.014069,0.002477,0.089288,0.012848,-0.012951,-0.040793,0.099930,0.033918,-0.053577,0.035380,-0.019360,-0.053224,-0.051774,-0.052262,-0.040525,-0.043103,0.038138,0.036570,-0.035359,-0.041915,0.042328,0.034480,0.051483,-0.097394,-0.072801,0.075454,-0.084328,-0.004500,0.030548,0.039575,-0.043761,-0.085080,0.036278,0.028949,-0.030944,0.004584,-0.029347,-0.018310,0.032665,-0.052470,-0.044237,0.014714,0.016143,-0.070779,0.020871,0.035204,-0.024469,0.071300,-0.029881,-0.023685,0.010325,0.065242,-0.062330,0.021950,0.085265,0.077098,0.068979,0.077064,0.000470,-0.007379,0.067449,-0.010152,0.069533,0.114299,-0.052543,0.008099,-0.033814,-0.039121,0.000907,0.046109,-0.018527,-0.066928,-0.008529,0.044927,0.002228,0.055057,NFLX,2020-12-31 21:00:00+00:00,52.55,54.55,52.31,54.07,54.07,53923000.0,False,0,54.07,52.29,52.08,50.05,50.89,51.04,49.91,49.42,50.78,50.09,49.80,50.18,58.63,57.98,56.52,55.68,56.19,52.33,53.86,53.24,53.90,54.82,53.94,55.22,55.08,54.79,55.91,56.36,55.76,55.65,55.73
2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2021-01-04 20:49:54+00:00,Pfizer,0.036805,-0.027506,-0.048388,-0.040726,0.040053,-0.006731,0.081135,0.008891,0.075858,0.014055,0.074672,0.029109,0.076591,-0.043322,-0.064973,0.068652,0.025357,-0.041616,-0.035701,-0.077821,0.000456,-0.021876,-0.039561,0.051064,0.057590,0.061622,-0.066996,0.015509,0.034123,-0.009054,-0.067450,-0.026688,0.032115,-0.095022,0.049261,0.017475,-0.039234,-0.072958,0.040455,-0.059622,-0.037896,0.029887,0.030661,0.095122,0.053451,0.061516,-0.029177,0.018639,-0.049888,-0.040357,-0.046010,0.072490,0.033571,0.054400,0.036722,-0.019873,-0.097126,-0.090899,-0.073045,0.034678,0.020068,-0.058582,0.024871,0.008448,0.042339,0.057344,0.031088,0.066256,-0.079391,0.008321,-0.074428,0.043484,0.020874,-0.026803,0.027917,0.054116,0.017360,-0.016600,0.032667,-0.008850,-0.080521,-0.055549,-0.026288,-0.000810,-0.022667,0.048786,0.042327,-0.054137,0.103502,-0.032193,-0.002719,0.028224,-0.073313,-0.062403,-0.047794,-0.068902,-0.090807,0.062189,0.087045,-0.029851,0.076648,-0.093838,0.050008,-0.013476,-0.054428,0.056168,-0.023001,-0.065126,0.092232,-0.077231,-0.001900,0.035070,0.024325,0.025107,-0.062669,-0.012852,-0.032900,-0.060606,0.039650,-0.031311,0.035329,-0.022410,-0.043565,-0.119826,-0.051872,-0.011683,0.003541,0.042145,0.060390,0.013529,0.032518,-0.000265,0.055520,0.021559,0.036222,0.102320,-0.061064,-0.029183,-0.002803,-0.017822,-0.043875,0.079351,-0.073118,0.059235,0.052028,0.082007,0.082527,-0.034164,0.056269,0.017795,0.030285,-0.103270,0.043168,0.018351,0.058859,-0.072924,-0.060295,-0.026471,0.035466,0.047334,-0.041739,-0.044487,-0.059543,0.018080,-0.063768,0.027510,0.039074,0.037864,-0.006257,-0.018784,-0.010361,0.085946,-0.068684,0.100764,-0.033956,0.027580,-0.065664,0.039798,0.078443,0.042805,-0.074347,-0.052344,-0.094733,-0.044154,-0.041340,0.001137,-0.041041,-0.006888,0.072732,-0.041070,-0.022663,0.054498,-0.068665,-0.050721,-0.075087,-0.006067,-0.030962,0.073286,0.071611,0.053888,-0.016479,-0.055896,0.044512,0.040838,0.029861,0.007483,-0.041284,0.085835,-0.025272,0.051915,0.034464,-0.094259,-0.051513,0.033495,-0.015682,-0.033285,0.010765,0.059418,-0.028976,0.044939,0.087140,-0.009401,0.030354,-0.051312,-0.026916,0.053288,0.074892,-0.054872,-0.039904,0.050897,-0.000941,-0.056355,-0.039955,-0.058512,-0.049086,-0.032905,-0.024052,0.043195,0.032334,-0.065705,-0.061025,-0.046714,0.060284,-0.063991,0.037242,-0.070329,-0.049430,0.019549,-0.045577,0.033325,0.058467,-0.073713,-0.076606,-0.038997,-0.024900,0.086982,0.022154,0.114401,-0.071691,0.013226,0.029465,0.024323,0.047010,0.057251,0.028921,0.016031,-0.009130,-0.012833,-0.083526,-0.080207,-0.094836,0.067800,0.002916,-0.011863,-0.057935,-0.014379,0.010808,0.092447,-0.048974,-0.069911,0.060663,0.010711,0.011420,0.050975,0.036483,-0.043400,-0.046667,0.113614,-0.058746,-0.029529,-0.043023,-0.050210,0.064698,-0.021284,0.068554,0.031574,-0.019458,0.063015,-0.061215,0.025430,0.028496,-0.033692,0.033615,0.021906,-0.079536,0.020031,0.000547,0.054006,0.042085,0.016515,0.038001,0.055986,-0.036938,-0.032942,0.034612,0.021597,-0.035925,0.056889,-0.032938,-0.091962,-0.048716,-0.050860,-0.019910,-0.050751,0.009988,0.046199,-0.043971,-0.078462,0.066558,0.014105,0.033329,-0.034367,-0.078884,0.057800,-0.060036,-0.025674,0.027141,-0.006239,-0.047979,-0.045784,-0.009838,0.035673,-0.022711,0.067075,-0.013000,-0.013152,0.031424,-0.052962,-0.014834,0.026812,0.081459,-0.101403,-0.009793,0.060702,-0.031667,0.067724,-0.055758,0.013436,0.040733,0.028071,-0.071255,-0.011857,0.045139,0.031231,0.062167,0.039153,-0.012582,0.022815,0.061133,0.000866,0.061504,0.104487,-0.015751,0.010918,-0.025938,-0.045824,-0.079215,0.041629,-0.035795,-0.002819,0.094213,0.021634,-0.008866,0.035121,PFE,2020-12-31 21:00:00+00:00,36.66,36.92,36.29,36.81,28.37,30796500.0,False,0,28.37,28.37,28.66,28.41,28.56,28.61,29.11,28.65,28.41,28.32,28.28,28.31,28.13,28.11,28.17,28.73,28.75,27.93,27.94,27.97,27.89,27.26,27.14,27.18,27.20,27.13,27.24,27.06,26.82,27.05,27.02

In [348]:
data_f = data_f.dropna(axis=0)

Отлично, данные готовы, можем делить их на X и y:

In [349]:
y = data_f[["company"] + [f"P{k}" for k in range(31)]]
X = data_f.drop(columns=["ticker", "webPublicationDate", "Date", "Open", "High", "Low", "Close", "Adj Close", "Volume", "is_summer", "q_idx"] + [f"P{k}" for k in range(31)])

In [350]:
y.head()

,company,P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30
0,Pfizer,28.37,28.37,28.66,28.41,28.56,28.61,29.11,28.65,28.41,28.32,28.28,28.31,28.13,28.11,28.17,28.73,28.75,27.93,27.94,27.97,27.89,27.26,27.14,27.18,27.20,27.13,27.24,27.06,26.82,27.05,27.02
1,Netflix,54.07,52.29,52.08,50.05,50.89,51.04,49.91,49.42,50.78,50.09,49.80,50.18,58.63,57.98,56.52,55.68,56.19,52.33,53.86,53.24,53.90,54.82,53.94,55.22,55.08,54.79,55.91,56.36,55.76,55.65,55.73
2,Pfizer,28.37,28.37,28.66,28.41,28.56,28.61,29.11,28.65,28.41,28.32,28.28,28.31,28.13,28.11,28.17,28.73,28.75,27.93,27.94,27.97,27.89,27.26,27.14,27.18,27.20,27.13,27.24,27.06,26.82,27.05,27.02
3,JPMorgan,109.49,110.09,115.26,119.04,119.17,120.95,122.85,122.97,123.69,121.47,120.94,119.13,118.13,117.22,115.76,115.28,112.02,113.99,112.73,113.57,117.06,118.40,121.13,120.89,122.78,122.29,122.36,122.02,123.76,126.73,127.13
4,JPMorgan,109.49,110.09,115.26,119.04,119.17,120.95,122.85,122.97,123.69,121.47,120.94,119.13,118.13,117.22,115.76,115.28,112.02,113.99,112.73,113.57,117.06,118.40,121.13,120.89,122.78,122.29,122.36,122.02,123.76,126.73,127.13

Но не забудем что в y мы работаем именно с измнением цены:

In [351]:
y[[f"P{i}" for i in range(1, 31)]] = np.log(y[[f"P{i}" for i in range(1, 31)]].div(y["P0"], axis=0))

In [352]:
y.head()

,company,P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30
0,Pfizer,28.37,0.000000,0.010170,0.001409,0.006675,0.008424,0.025750,0.009821,0.001409,-0.001764,-0.003177,-0.002117,-0.008496,-0.009207,-0.007075,0.012610,0.013306,-0.015631,-0.015273,-0.014200,-0.017064,-0.039912,-0.044324,-0.042851,-0.042115,-0.044692,-0.040646,-0.047276,-0.056184,-0.047645,-0.048755
1,Netflix,54.07,-0.033474,-0.037499,-0.077257,-0.060613,-0.057670,-0.080058,-0.089924,-0.062777,-0.076458,-0.082265,-0.074663,0.080967,0.069819,0.044315,0.029342,0.038459,-0.032710,-0.003891,-0.015470,-0.003149,0.013776,-0.002407,0.021046,0.018507,0.013228,0.033464,0.041480,0.030777,0.028803,0.030239
2,Pfizer,28.37,0.000000,0.010170,0.001409,0.006675,0.008424,0.025750,0.009821,0.001409,-0.001764,-0.003177,-0.002117,-0.008496,-0.009207,-0.007075,0.012610,0.013306,-0.015631,-0.015273,-0.014200,-0.017064,-0.039912,-0.044324,-0.042851,-0.042115,-0.044692,-0.040646,-0.047276,-0.056184,-0.047645,-0.048755
3,JPMorgan,109.49,0.005465,0.051357,0.083626,0.084718,0.099544,0.115131,0.116107,0.121945,0.103834,0.099461,0.084382,0.075952,0.068219,0.055686,0.051531,0.022844,0.040278,0.029162,0.036586,0.066853,0.078236,0.101031,0.099048,0.114561,0.110562,0.111134,0.108352,0.122511,0.146226,0.149377
4,JPMorgan,109.49,0.005465,0.051357,0.083626,0.084718,0.099544,0.115131,0.116107,0.121945,0.103834,0.099461,0.084382,0.075952,0.068219,0.055686,0.051531,0.022844,0.040278,0.029162,0.036586,0.066853,0.078236,0.101031,0.099048,0.114561,0.110562,0.111134,0.108352,0.122511,0.146226,0.149377

Попробуем поработать с компанией Apple.

In [353]:
X_apple = X[X["company"] == "Apple"].drop(columns=["company"])
y_apple = y[y["company"] == "Apple"].drop(columns=["company", "P0"])

In [378]:
y_apple_bin = (y_apple[[f"P{i}" for i in range(1, 31)]] > 0).astype(int)

In [385]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

for i in range(1, 31):
    X_apple_train, X_apple_test, y_apple_train, y_apple_test = train_test_split(X_apple, y_apple_bin[f"P{i}"], test_size=0.2, random_state=67)

    model = RandomForestClassifier(
        n_estimators=300,
        max_depth=6,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_apple_train, y_apple_train)

    pred = model.predict(X_apple_test)
    prob = model.predict_proba(X_apple_test)[:, 1]

    print(f"F1 для P{i}: {f1_score(y_apple_test, pred)}")
    print(f"ROC-AUC для P{i}: {roc_auc_score(y_apple_test, prob)}")
    print()

F1 для P1: 0.6778242677824268
ROC-AUC для P1: 0.4483810076956585

F1 для P2: 0.6885245901639344
ROC-AUC для P2: 0.5123579545454545

F1 для P3: 0.7096774193548387
ROC-AUC для P3: 0.4743720052272397

F1 для P4: 0.701195219123506
ROC-AUC для P4: 0.4691447655002178

F1 для P5: 0.6831275720164609
ROC-AUC для P5: 0.468013468013468

F1 для P6: 0.712
ROC-AUC для P6: 0.5373892841585596

F1 для P7: 0.6987951807228916
ROC-AUC для P7: 0.5596209912536443

F1 для P8: 0.660377358490566
ROC-AUC для P8: 0.5501725129384704

F1 для P9: 0.6188340807174888
ROC-AUC для P9: 0.43243243243243246

F1 для P10: 0.6829268292682927
ROC-AUC для P10: 0.5037682872764888

F1 для P11: 0.7258687258687259
ROC-AUC для P11: 0.4949494949494949

F1 для P12: 0.7518796992481203
ROC-AUC для P12: 0.5393801965230537

F1 для P13: 0.7715355805243446
ROC-AUC для P13: 0.5479938271604939

F1 для P14: 0.7777777777777778
ROC-AUC для P14: 0.5179598818224227

F1 для P15: 0.781021897810219
ROC-AUC для P15: 0.4858280986670752

F1 для P16: 0.7737226277372263
ROC-AUC для P16: 0.4770951432511108

F1 для P17: 0.732824427480916
ROC-AUC для P17: 0.5191040843214756

F1 для P18: 0.7372549019607844
ROC-AUC для P18: 0.522471087688479

F1 для P19: 0.7307692307692307
ROC-AUC для P19: 0.5514577259475218

F1 для P20: 0.7396226415094339
ROC-AUC для P20: 0.5633143024447372

F1 для P21: 0.703125
ROC-AUC для P21: 0.5328046142754145

F1 для P22: 0.7049180327868853
ROC-AUC для P22: 0.5234318673395819

F1 для P23: 0.6638655462184874
ROC-AUC для P23: 0.515068493150685

F1 для P24: 0.6942148760330579
ROC-AUC для P24: 0.5355685131195336

F1 для P25: 0.6887966804979253
ROC-AUC для P25: 0.5007986060694062

F1 для P26: 0.7114624505928854
ROC-AUC для P26: 0.5376093294460642

F1 для P27: 0.6831275720164609
ROC-AUC для P27: 0.5580020688636027

F1 для P28: 0.6721991701244814
ROC-AUC для P28: 0.579933207492377

F1 для P29: 0.703862660944206
ROC-AUC для P29: 0.5857142857142857

F1 для P30: 0.6396396396396397
ROC-AUC для P30: 0.5164333536214242

Наилучший F1 при задержке в 15 дней. Однако ROC-AUC оставляет желать лучшего - прогноз как у случайного угадывания.

Вывод: Модель в текущем виде не пригодна для практического использования. Нужно возвращаться к анализу данных и выбору алгоритма.