In [14]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [15]:
df = pd.read_csv("finhub+theguardian_raw_7.5k.csv", index_col=0)
df = df.dropna(subset=["fields.trailText"])
df.shape

(7353, 48)

In [16]:
df["fields.trailText"]

0       Google, Amazon, Apple and Samsung control oper...
1       CMA intends to force tech firms to make change...
2       National Association of Cider Makers says warm...
3       First penalties under landmark Digital Markets...
4       CMA examining impact of tech firms’ operating ...
                              ...
7374     Cisco, 3M share gains lead Dow's 160-point climb
7375    A key trading signal flashed for Caterpillar s...
7376    Caterpillar and Walmart have been highlighted ...
7377    Atlas Energy Solutions Inc. (NYSE:AESI) (&#34;...
7378    Macroeconomic and sector-specific issues vary ...
Name: fields.trailText, Length: 7353, dtype: str

In [17]:
df["fields.bodyText"]

0       The world’s largest broadcasters have pushed f...
1       A UK watchdog has said it intends to take acti...
2       “If you love cider, this is cider to the power...
3       The European Commission has fined Apple €500m ...
4       The UK’s competition watchdog has launched inv...
                              ...
7374                                                  NaN
7375                                                  NaN
7376                                                  NaN
7377                                                  NaN
7378                                                  NaN
Name: fields.bodyText, Length: 7353, dtype: str

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("intfloat/multilingual-e5-small")

texts = ["passage: " + x for x in df["fields.bodyText"]]

embeddings_full = model.encode(
    texts,
    normalize_embeddings=True,
    show_progress_bar=True
)

In [ ]:
model = SentenceTransformer("intfloat/multilingual-e5-small")

texts = ["passage: " + x for x in df["fields.trailText"]]

embeddings_short = model.encode(
    texts,
    normalize_embeddings=True,
    show_progress_bar=True
)

In [ ]:
np.save("embeddings_f.npy", embeddings_full)

In [ ]:
np.save("embeddings_s.npy", embeddings_short)

In [19]:
np_embeddings_full = np.load('embeddings_f.npy')
np_embeddings_short = np.load('embeddings_s.npy')

In [20]:
embeddings_full = pd.DataFrame(np_embeddings_full)
embeddings_short = pd.DataFrame(np_embeddings_short)

In [21]:
embeddings_full.shape

(5549, 384)

In [22]:

embeddings_short.shape

(7353, 384)

In [23]:
embeddings_full.columns = [f"emb_f_{i}" for i in range(embeddings_full.shape[1])]
embeddings_short.columns = [f"emb_s_{i}" for i in range(embeddings_short.shape[1])]

In [24]:
df = df[["webPublicationDate", "stocks", "company", "source"]]

In [190]:
data = pd.concat(
    [
        df.reset_index(drop=True),
        embeddings_full.reset_index(drop=True),
        embeddings_short.reset_index(drop=True)
    ],
    axis=1
)

In [191]:
mapping = {
    "AAPL": "Apple",
    "TSLA": "Tesla",
    "CAT": "Caterpillar",
    "JPM": "JPMorgan",
    "NFLX": "Netflix",
    "PFE": "Pfizer",
    "XOM": "Exxon",
    "WMT": "Walmart"
}

In [192]:
data.loc[data["company"].isna(), "company"] = data.loc[data["company"].isna(), "stocks"].str.split(";").apply(lambda x: ";".join(mapping[i] for i in x if i in mapping))

In [193]:
data

,webPublicationDate,stocks,company,source,emb_f_0,emb_f_1,emb_f_2,emb_f_3,emb_f_4,emb_f_5,emb_f_6,emb_f_7,emb_f_8,emb_f_9,emb_f_10,emb_f_11,emb_f_12,emb_f_13,emb_f_14,emb_f_15,emb_f_16,emb_f_17,emb_f_18,emb_f_19,emb_f_20,emb_f_21,emb_f_22,emb_f_23,emb_f_24,emb_f_25,emb_f_26,emb_f_27,emb_f_28,emb_f_29,emb_f_30,emb_f_31,emb_f_32,emb_f_33,emb_f_34,emb_f_35,emb_f_36,emb_f_37,emb_f_38,emb_f_39,emb_f_40,emb_f_41,emb_f_42,emb_f_43,emb_f_44,emb_f_45,emb_f_46,emb_f_47,emb_f_48,emb_f_49,emb_f_50,emb_f_51,emb_f_52,emb_f_53,emb_f_54,emb_f_55,emb_f_56,emb_f_57,emb_f_58,emb_f_59,emb_f_60,emb_f_61,emb_f_62,emb_f_63,emb_f_64,emb_f_65,emb_f_66,emb_f_67,emb_f_68,emb_f_69,emb_f_70,emb_f_71,emb_f_72,emb_f_73,emb_f_74,emb_f_75,emb_f_76,emb_f_77,emb_f_78,emb_f_79,emb_f_80,emb_f_81,emb_f_82,emb_f_83,emb_f_84,emb_f_85,emb_f_86,emb_f_87,emb_f_88,emb_f_89,emb_f_90,emb_f_91,emb_f_92,emb_f_93,emb_f_94,emb_f_95,emb_f_96,emb_f_97,emb_f_98,emb_f_99,emb_f_100,emb_f_101,emb_f_102,emb_f_103,emb_f_104,emb_f_105,emb_f_106,emb_f_107,emb_f_108,emb_f_109,emb_f_110,emb_f_111,emb_f_112,emb_f_113,emb_f_114,emb_f_115,emb_f_116,emb_f_117,emb_f_118,emb_f_119,emb_f_120,emb_f_121,emb_f_122,emb_f_123,emb_f_124,emb_f_125,emb_f_126,emb_f_127,emb_f_128,emb_f_129,emb_f_130,emb_f_131,emb_f_132,emb_f_133,emb_f_134,emb_f_135,emb_f_136,emb_f_137,emb_f_138,emb_f_139,emb_f_140,emb_f_141,emb_f_142,emb_f_143,emb_f_144,emb_f_145,emb_f_146,emb_f_147,emb_f_148,emb_f_149,emb_f_150,emb_f_151,emb_f_152,emb_f_153,emb_f_154,emb_f_155,emb_f_156,emb_f_157,emb_f_158,emb_f_159,emb_f_160,emb_f_161,emb_f_162,emb_f_163,emb_f_164,emb_f_165,emb_f_166,emb_f_167,emb_f_168,emb_f_169,emb_f_170,emb_f_171,emb_f_172,emb_f_173,emb_f_174,emb_f_175,emb_f_176,emb_f_177,emb_f_178,emb_f_179,emb_f_180,emb_f_181,emb_f_182,emb_f_183,emb_f_184,emb_f_185,emb_f_186,emb_f_187,emb_f_188,emb_f_189,emb_f_190,emb_f_191,emb_f_192,emb_f_193,emb_f_194,emb_f_195,emb_f_196,emb_f_197,emb_f_198,emb_f_199,emb_f_200,emb_f_201,emb_f_202,emb_f_203,emb_f_204,emb_f_205,emb_f_206,emb_f_207,emb_f_208,emb_f_209,emb_f_210,emb_f_211,emb_f_212,emb_f_213,emb_f_214,emb_f_215,emb_f_216,emb_f_217,emb_f_218,emb_f_219,emb_f_220,emb_f_221,emb_f_222,emb_f_223,emb_f_224,emb_f_225,emb_f_226,emb_f_227,emb_f_228,emb_f_229,emb_f_230,emb_f_231,emb_f_232,emb_f_233,emb_f_234,emb_f_235,emb_f_236,emb_f_237,emb_f_238,emb_f_239,emb_f_240,emb_f_241,emb_f_242,emb_f_243,emb_f_244,emb_f_245,emb_f_246,emb_f_247,emb_f_248,emb_f_249,emb_f_250,emb_f_251,emb_f_252,emb_f_253,emb_f_254,emb_f_255,emb_f_256,emb_f_257,emb_f_258,emb_f_259,emb_f_260,emb_f_261,emb_f_262,emb_f_263,emb_f_264,emb_f_265,emb_f_266,emb_f_267,emb_f_268,emb_f_269,emb_f_270,emb_f_271,emb_f_272,emb_f_273,emb_f_274,emb_f_275,emb_f_276,emb_f_277,emb_f_278,emb_f_279,emb_f_280,emb_f_281,emb_f_282,emb_f_283,emb_f_284,emb_f_285,emb_f_286,emb_f_287,emb_f_288,emb_f_289,emb_f_290,emb_f_291,emb_f_292,emb_f_293,emb_f_294,emb_f_295,emb_f_296,emb_f_297,emb_f_298,emb_f_299,emb_f_300,emb_f_301,emb_f_302,emb_f_303,emb_f_304,emb_f_305,emb_f_306,emb_f_307,emb_f_308,emb_f_309,emb_f_310,emb_f_311,emb_f_312,emb_f_313,emb_f_314,emb_f_315,emb_f_316,emb_f_317,emb_f_318,emb_f_319,emb_f_320,emb_f_321,emb_f_322,emb_f_323,emb_f_324,emb_f_325,emb_f_326,emb_f_327,emb_f_328,emb_f_329,emb_f_330,emb_f_331,emb_f_332,emb_f_333,emb_f_334,emb_f_335,emb_f_336,emb_f_337,emb_f_338,emb_f_339,emb_f_340,emb_f_341,emb_f_342,emb_f_343,emb_f_344,emb_f_345,emb_f_346,emb_f_347,emb_f_348,emb_f_349,emb_f_350,emb_f_351,emb_f_352,emb_f_353,emb_f_354,emb_f_355,emb_f_356,emb_f_357,emb_f_358,emb_f_359,emb_f_360,emb_f_361,emb_f_362,emb_f_363,emb_f_364,emb_f_365,emb_f_366,emb_f_367,emb_f_368,emb_f_369,emb_f_370,emb_f_371,emb_f_372,emb_f_373,emb_f_374,emb_f_375,emb_f_376,emb_f_377,emb_f_378,emb_f_379,emb_f_380,emb_f_381,emb_f_382,emb_f_383,emb_s_0,emb_s_1,emb_s_2,emb_s_3,emb_s_4,emb_s_5,emb_s_6,emb_s_7,emb_s_8,emb_s_9,emb_s_10,emb_s_11,emb_s_12,emb_s_13,emb_s_14,emb_s_15,emb_s_16,emb_s_17,emb_s_18,emb_s_19,emb_s_20,emb_s_21,emb_s_22,emb_s_23,emb_s_24,emb_s_25,emb_s_26,emb_s_27,emb_s_28,emb_s_29,emb_s_30,emb_s_31,emb_s_32,emb_s_33,emb_s_34,emb_s_35,emb_s_36,emb_s_37,emb_s_38,emb_s_39,emb_s_40,emb_s_41,emb_s_42,emb_s_43,emb_s_44,emb_s_45,emb_s_46,emb_s_47,emb_s_48,emb_s_49,emb_s_50,emb_s_51,emb_s_52,emb_s_53,emb_s_54,emb_s_55,emb_s_56,emb_s_57,emb_s_58,emb_s_59,emb_s_60,emb_s_61,emb_s_62,emb_s_63,emb_s_64,emb_s_65,emb_s_66,emb_s_67,emb_s_68,emb_s_69,emb_s_70,emb_s_71,emb_s_72,emb_s_73,emb_s_74,emb_s_75,emb_s_76,emb_s_77,emb_s_78,emb_s_79,emb_s_80,emb_s_81,emb_s_82,emb_s_83,emb_s_84,emb_s_85,emb_s_86,emb_s_87,emb_s_88,emb_s_89,emb_s_90,emb_s_91,emb_s_92,emb_s_93,emb_s_94,emb_s_95,emb_s_96,emb_s_97,emb_s_98,emb_s_99,emb_s_100,emb_s_101,emb_s_102,emb_s_103,emb_s_104,emb_s_105,emb_s_106,emb_s_107,emb_s_108,emb_s_109,emb_s_110,emb_s_111,emb_s_112,emb_s_113,emb_s_114,emb_s_115,emb_s_116,emb_s_117,emb_s_118,emb_s_119,emb_s_120,emb_s_121,emb_s_122,emb_s_123,emb_s_124,emb_s_125,emb_s_126,emb_s_127,emb_s_128,emb_s_129,emb_s_130,emb_s_131,emb_s_132,emb_s_133,emb_s_134,emb_s_135,emb_s_136,emb_s_137,emb_s_138,emb_s_139,emb_s_140,emb_s_141,emb_s_142,emb_s_143,emb_s_144,emb_s_145,emb_s_146,emb_s_147,emb_s_148,emb_s_149,emb_s_150,emb_s_151,emb_s_152,emb_s_153,emb_s_154,emb_s_155,emb_s_156,emb_s_157,emb_s_158,emb_s_159,emb_s_160,emb_s_161,emb_s_162,emb_s_163,emb_s_164,emb_s_165,emb_s_166,emb_s_167,emb_s_168,emb_s_169,emb_s_170,emb_s_171,emb_s_172,emb_s_173,emb_s_174,emb_s_175,emb_s_176,emb_s_177,emb_s_178,emb_s_179,emb_s_180,emb_s_181,emb_s_182,emb_s_183,emb_s_184,emb_s_185,emb_s_186,emb_s_187,emb_s_188,emb_s_189,emb_s_190,emb_s_191,emb_s_192,emb_s_193,emb_s_194,emb_s_195,emb_s_196,emb_s_197,emb_s_198,emb_s_199,emb_s_200,emb_s_201,emb_s_202,emb_s_203,emb_s_204,emb_s_205,emb_s_206,emb_s_207,emb_s_208,emb_s_209,emb_s_210,emb_s_211,emb_s_212,emb_s_213,emb_s_214,emb_s_215,emb_s_216,emb_s_217,emb_s_218,emb_s_219,emb_s_220,emb_s_221,emb_s_222,emb_s_223,emb_s_224,emb_s_225,emb_s_226,emb_s_227,emb_s_228,emb_s_229,emb_s_230,emb_s_231,emb_s_232,emb_s_233,emb_s_234,emb_s_235,emb_s_236,emb_s_237,emb_s_238,emb_s_239,emb_s_240,emb_s_241,emb_s_242,emb_s_243,emb_s_244,emb_s_245,emb_s_246,emb_s_247,emb_s_248,emb_s_249,emb_s_250,emb_s_251,emb_s_252,emb_s_253,emb_s_254,emb_s_255,emb_s_256,emb_s_257,emb_s_258,emb_s_259,emb_s_260,emb_s_261,emb_s_262,emb_s_263,emb_s_264,emb_s_265,emb_s_266,emb_s_267,emb_s_268,emb_s_269,emb_s_270,emb_s_271,emb_s_272,emb_s_273,emb_s_274,emb_s_275,emb_s_276,emb_s_277,emb_s_278,emb_s_279,emb_s_280,emb_s_281,emb_s_282,emb_s_283,emb_s_284,emb_s_285,emb_s_286,emb_s_287,emb_s_288,emb_s_289,emb_s_290,emb_s_291,emb_s_292,emb_s_293,emb_s_294,emb_s_295,emb_s_296,emb_s_297,emb_s_298,emb_s_299,emb_s_300,emb_s_301,emb_s_302,emb_s_303,emb_s_304,emb_s_305,emb_s_306,emb_s_307,emb_s_308,emb_s_309,emb_s_310,emb_s_311,emb_s_312,emb_s_313,emb_s_314,emb_s_315,emb_s_316,emb_s_317,emb_s_318,emb_s_319,emb_s_320,emb_s_321,emb_s_322,emb_s_323,emb_s_324,emb_s_325,emb_s_326,emb_s_327,emb_s_328,emb_s_329,emb_s_330,emb_s_331,emb_s_332,emb_s_333,emb_s_334,emb_s_335,emb_s_336,emb_s_337,emb_s_338,emb_s_339,emb_s_340,emb_s_341,emb_s_342,emb_s_343,emb_s_344,emb_s_345,emb_s_346,emb_s_347,emb_s_348,emb_s_349,emb_s_350,emb_s_351,emb_s_352,emb_s_353,emb_s_354,emb_s_355,emb_s_356,emb_s_357,emb_s_358,emb_s_359,emb_s_360,emb_s_361,emb_s_362,emb_s_363,emb_s_364,emb_s_365,emb_s_366,emb_s_367,emb_s_368,emb_s_369,emb_s_370,emb_s_371,emb_s_372,emb_s_373,emb_s_374,emb_s_375,emb_s_376,emb_s_377,emb_s_378,emb_s_379,emb_s_380,emb_s_381,emb_s_382,emb_s_383
0,2026-03-23T13:31:06Z,AMZN;AAPL;GOOG,Apple;JPMorgan;Netflix;Pfizer,The Guardian,0.038025,0.018858,-0.086595,0.008641,0.034031,-0.018835,0.076140,0.012036,0.033506,0.011971,0.063189,0.016846,0.076012,-0.084967,-0.045191,0.040121,0.061898,-0.002628,-0.024180,-0.058232,0.025985,-0.023125,-0.056735,0.033251,0.064188,0.080117,-0.064643,0.014658,-0.027111,-0.049215,-0.059584,-0.063907,0.061834,-0.099122,0.044907,0.019759,-0.036929,-0.049866,0.058166,-0.033384,-0.035382,0.026429,0.025998,0.103433,0.055798,0.024773,-0.017467,0.031075,-0.056646,-0.020733,-0.065451,0.031899,0.045822,0.057932,0.054153,-0.039517,-0.090263,-0.080082,-0.020314,-0.002660,0.092827,-0.051519,0.036129,-0.014263,0.040663,0.033581,-0.004201,0.033415,-0.060745,0.014824,-0.009569,0.043846,0.015037,-0.065885,0.031751,0.102630,0.049452,-0.019729,0.023484,0.011308,-0.059146,-0.077472,-0.029474,0.047105,-0.028209,0.081943,0.071144,-0.072979,0.081368,-0.023541,-0.024118,0.047241,-0.065265,-0.035430,-0.048655,-0.049407,-0.033535,0.096568,0.070078,-0.018527,0.082767,-0.074878,0.046550,-0.021118,-0.063131,0.019430,0.040776,-0.055604,0.085321,-0.074215,-0.028909,0.018009,0.069572,0.016697,-0.081627,-0.068889,-0.028755,-0.072625,0.012519,-0.044597,0.093571,-0.033167,-0.016155,-0.096866,-0.072974,-0.035678,0.016550,0.034578,0.063297,0.020400,0.015024,0.044000,0.056340,0.077235,0.081252,0.103822,-0.085244,-0.002350,-0.043159,-0.062273,-0.025932,0.095033,-0.035358,0.051496,0.056035,0.040303,0.051378,-0.028961,0.037197,-0.007587,0.035918,-0.060254,0.078566,0.034235,0.062392,-0.075872,-0.053853,-0.032895,0.033365,0.066921,-0.027530,-0.036516,-0.102985,0.014247,-0.028739,-0.022980,0.021429,0.064870,0.003385,-0.005851,-0.065104,0.047444,-0.039536,0.057797,0.012176,0.053917,-0.094062,-0.008078,0.057595,0.050228,-0.064663,-0.032880,-0.073867,-0.063811,-0.034164,-0.065423,-0.040367,0.063859,0.008450,-0.015013,0.024284,0.017185,-0.066683,-0.073007,-0.046892,0.071188,-0.052892,0.045286,0.020603,0.016777,-0.028692,-0.011352,0.048107,0.056427,0.016846,0.023313,-0.029326,0.067730,-0.037509,0.052975,0.067621,-0.068742,-0.074349,0.082270,-0.039638,-0.025498,0.021231,0.035030,-0.077371,0.030676,0.089377,-0.049328,0.047179,-0.072956,-0.005441,0.043417,0.080251,-0.047452,-0.053972,0.011236,-0.054727,-0.007871,-0.051056,-0.008326,-0.062684,-0.055155,-0.009197,0.060596,-0.000216,-0.038149,-0.075700,-0.015891,0.013155,-0.060592,0.071692,-0.032164,-0.054593,0.040430,0.021232,0.042799,0.047348,-0.058623,-0.070587,-0.003159,-0.044039,0.103689,0.067558,0.058313,-0.087304,0.038223,0.048917,-0.036565,0.045964,0.022143,0.047641,0.045015,-0.003066,-0.062033,-0.035443,-0.028948,-0.057692,0.036809,0.023672,0.003128,-0.054957,-0.045523,-0.010000,0.073081,-0.044362,-0.039034,0.045809,0.021007,0.022405,0.077515,0.060358,-0.021224,-0.015320,0.054028,-0.081312,-0.049697,-0.053018,-0.056819,0.063424,-0.021582,0.046387,0.056845,0.004724,0.062874,-0.041765,0.002014,-0.008127,-0.011316,0.035344,0.064695,-0.068760,0.012563,0.039127,0.043441,0.002915,0.023517,0.062380,0.050161,-0.030371,-0.025255,0.013294,0.069298,-0.033984,0.030053,-0.053445,-0.084558,-0.038507,-0.053299,-0.072722,-0.047565,-0.008606,0.040937,-0.037393,-0.038561,0.026209,-0.028136,0.013004,-0.038102,-0.030115,0.055816,-0.075088,-0.012603,0.014443,0.055649,-0.086399,-0.108251,0.007392,-0.012850,-0.034204,0.034605,-0.000295,-0.010119,0.033695,-0.067820,-0.021389,0.022009,0.055020,-0.094434,0.013761,0.056713,-0.049651,0.048126,-0.099841,-0.022538,0.077094,0.070519,-0.098684,-0.011535,0.026741,0.060796,0.073505,0.072355,-0.047605,0.001703,0.088197,-0.030249,0.029592,0.043072,-0.026665,0.007139,-0.053185,-0.053847,-0.034330,0.014471,-0.056053,-0.058262,0.029631,0.054520,0.027139,0.047965,0.040767,-0.004040,-0.046337,-0.014811,0.040611,-0.010620,0.044254,0.013120,0.036194,0.018884,0.031054,0.031754,0.129609,-0.062060,-0.056044,0.053686,0.057087,-0.020003,-0.012454,-0.055738,0.050742,-0.013561,-0.065082,0.029517,0.082369,0.065359,-0.044736,-0.005920,0.010175,-0.036621,-0.071598,-0.023848,0.036660,-0.070989,0.040069,-0.026920,-0.018506,-0.051732,0.027044,-0.042824,-0.028519,0.047341,0.026070,0.084268,0.039830,0.056819,-0.054161,0.024377,-0.041979,0.003022,-0.041287,0.045567,0.051195,0.057424,0.019930,-0.021579,-0.086711,-0.032562,-0.063368,-0.028123,0.036148,-0.029318,0.072835,0.026854,0.088820,0.026451,0.047715,0.071564,-0.097009,-0.003493,-0.035935,0.062983,0.027219,-0.071795,0.066632,0.036529,0.038189,-0.038420,0.026262,0.001615,-0.087280,-0.029053,-0.061329,0.058182,-0.048381,0.049201,0.037077,-0.084314,0.014356,-0.013517,-0.012782,0.027093,-0.036443,-0.067015,-0.110201,-0.092586,-0.051940,0.096052,0.052000,-0.008403,0.047236,-0.054892,0.021642,-0.034692,-0.033301,0.059758,0.003524,-0.084059,0.059620,-0.053642,-0.024931,-0.014200,0.079504,0.037866,-0.072228,-0.046220,-0.020936,-0.054228,0.006330,-0.020747,0.042204,-0.022134,-0.035083,-0.091877,-0.046878,-0.074446,0.038034,0.067828,0.012553,-0.009023,-0.015104,0.037852,0.033808,0.070706,0.069046,0.116860,-0.038927,-0.029981,-0.024866,-0.040821,-0.062569,0.098354,-0.007376,0.061076,0.065264,0.017928,0.053361,-0.039070,0.085992,0.015151,0.051412,-0.032651,0.106014,-0.011596,0.080549,-0.042238,-0.048191,0.007423,0.047633,0.066545,-0.041050,-0.038043,-0.074137,-0.033137,-0.044501,-0.015798,-0.017903,0.103386,-0.017347,-0.034986,-0.039236,0.079811,-0.000778,0.036736,0.010082,0.058886,-0.082035,0.050486,0.067481,0.054545,-0.042083,-0.052850,-0.086020,-0.041989,-0.046380,-0.032107,-0.020886,0.030079,-0.009112,0.003248,-0.049515,0.003059,-0.071004,-0.050848,-0.062620,0.039929,-0.084031,0.055318,0.065514,0.003238,-0.011861,-0.032650,0.032536,0.087276,-0.001354,0.027448,-0.094680,0.063133,-0.058522,0.055877,0.077698,-0.065921,-0.057338,0.060385,-0.018339,-0.030418,0.005494,0.038300,-0.046053,-0.005912,0.064156,-0.031830,0.034192,-0.070436,-0.052327,0.050217,0.079865,-0.068644,-0.058226,0.025113,-0.052526,-0.063865,-0.067269,-0.080222,-0.042596,-0.063483,-0.017006,0.062596,0.060179,-0.022693,-0.018367,-0.040721,-0.001501,-0.030196,0.040809,0.003728,-0.080379,0.037593,-0.005233,0.005013,0.062717,-0.094904,-0.014511,0.034535,-0.038529,0.015553,0.054461,0.100801,-0.062069,0.065487,0.011642,-0.060437,0.080241,0.055169,0.014928,0.022090,-0.027453,-0.032506,-0.055912,-0.045995,-0.036213,0.026336,0.019682,-0.040847,-0.059817,-0.066637,-0.012994,0.068549,-0.045934,0.011099,0.034099,0.017954,0.079103,0.058994,0.039454,0.002911,-0.021366,0.081629,-0.072629,-0.067441,-0.028045,-0.063753,0.005768,-0.051781,0.050276,0.027067,0.018209,0.117146,-0.026327,0.018740,-0.007092,-0.029028,0.012364,0.039105,-0.108621,0.045206,0.047720,0.055394,-0.019313,0.041532,0.028202,0.048321,-0.035827,-0.040251,0.037282,0.075855,0.009400,0.045396,-0.040603,-0.080909,-0.040211,-0.071061,-0.003528,-0.030475,-0.011443,0.008978,-0.052625,-0.032738,0.023790,0.002214,0.042078,-0.046329,0.002772,0.004949,-0.077081,0.028206,-0.015100,0.074825,-0.063524,-0.081832,0.007063,0.051127,-0.030501,0.070287,-0.038490,-0.025016,0.021127,-0.027734,-0.017951,0.022635,0.073952,-0.111178,-0.005855,0.049742,-0.066293,0.025009,-0.101077,-0.008237,0.085511,0.074662,-0.061105,-0.054935,-0.004085,0.083927,0.054774,0.045717,-0.045725,0.004560,0.078146,-0.031801,0.066601,0.006289,-0.026726,0.006637,-0.018801,-0.012216,-0.004009,0.051951,-0.047047,-0.068557,0.049680,0.044040,0.047342,0.106844

In [194]:
stocks = (data["stocks"].fillna("").str.get_dummies(sep=";"))[["AAPL", "TSLA", "CAT", "JPM", "NFLX", "PFE", "XOM", "WMT"]]

In [195]:
data = pd.concat([stocks, data], axis=1)

In [196]:
source = data["source"].str.get_dummies()

In [197]:
data = pd.concat([source, data], axis=1)

In [198]:
data = data.drop(columns=["stocks", "source"])

In [199]:
data.to_csv("data_model.csv", index=False)

In [176]:
common_cols = [c for c in data.columns if not c.startswith("emb_f_") and not c.startswith("emb_s_")]
f_cols = [c for c in data.columns if c.startswith("emb_f_")]
s_cols = [c for c in data.columns if c.startswith("emb_s_")]

data_f = data[common_cols + f_cols].copy()
data_s = data[common_cols + s_cols].copy()

In [179]:
data

,Benzinga,CNBC,ChartMill,DowJones,MarketWatch,SeekingAlpha,The Guardian,Yahoo,AAPL,TSLA,CAT,JPM,NFLX,PFE,XOM,WMT,webPublicationDate,company,emb_f_0,emb_f_1,emb_f_2,emb_f_3,emb_f_4,emb_f_5,emb_f_6,emb_f_7,emb_f_8,emb_f_9,emb_f_10,emb_f_11,emb_f_12,emb_f_13,emb_f_14,emb_f_15,emb_f_16,emb_f_17,emb_f_18,emb_f_19,emb_f_20,emb_f_21,emb_f_22,emb_f_23,emb_f_24,emb_f_25,emb_f_26,emb_f_27,emb_f_28,emb_f_29,emb_f_30,emb_f_31,emb_f_32,emb_f_33,emb_f_34,emb_f_35,emb_f_36,emb_f_37,emb_f_38,emb_f_39,emb_f_40,emb_f_41,emb_f_42,emb_f_43,emb_f_44,emb_f_45,emb_f_46,emb_f_47,emb_f_48,emb_f_49,emb_f_50,emb_f_51,emb_f_52,emb_f_53,emb_f_54,emb_f_55,emb_f_56,emb_f_57,emb_f_58,emb_f_59,emb_f_60,emb_f_61,emb_f_62,emb_f_63,emb_f_64,emb_f_65,emb_f_66,emb_f_67,emb_f_68,emb_f_69,emb_f_70,emb_f_71,emb_f_72,emb_f_73,emb_f_74,emb_f_75,emb_f_76,emb_f_77,emb_f_78,emb_f_79,emb_f_80,emb_f_81,emb_f_82,emb_f_83,emb_f_84,emb_f_85,emb_f_86,emb_f_87,emb_f_88,emb_f_89,emb_f_90,emb_f_91,emb_f_92,emb_f_93,emb_f_94,emb_f_95,emb_f_96,emb_f_97,emb_f_98,emb_f_99,emb_f_100,emb_f_101,emb_f_102,emb_f_103,emb_f_104,emb_f_105,emb_f_106,emb_f_107,emb_f_108,emb_f_109,emb_f_110,emb_f_111,emb_f_112,emb_f_113,emb_f_114,emb_f_115,emb_f_116,emb_f_117,emb_f_118,emb_f_119,emb_f_120,emb_f_121,emb_f_122,emb_f_123,emb_f_124,emb_f_125,emb_f_126,emb_f_127,emb_f_128,emb_f_129,emb_f_130,emb_f_131,emb_f_132,emb_f_133,emb_f_134,emb_f_135,emb_f_136,emb_f_137,emb_f_138,emb_f_139,emb_f_140,emb_f_141,emb_f_142,emb_f_143,emb_f_144,emb_f_145,emb_f_146,emb_f_147,emb_f_148,emb_f_149,emb_f_150,emb_f_151,emb_f_152,emb_f_153,emb_f_154,emb_f_155,emb_f_156,emb_f_157,emb_f_158,emb_f_159,emb_f_160,emb_f_161,emb_f_162,emb_f_163,emb_f_164,emb_f_165,emb_f_166,emb_f_167,emb_f_168,emb_f_169,emb_f_170,emb_f_171,emb_f_172,emb_f_173,emb_f_174,emb_f_175,emb_f_176,emb_f_177,emb_f_178,emb_f_179,emb_f_180,emb_f_181,emb_f_182,emb_f_183,emb_f_184,emb_f_185,emb_f_186,emb_f_187,emb_f_188,emb_f_189,emb_f_190,emb_f_191,emb_f_192,emb_f_193,emb_f_194,emb_f_195,emb_f_196,emb_f_197,emb_f_198,emb_f_199,emb_f_200,emb_f_201,emb_f_202,emb_f_203,emb_f_204,emb_f_205,emb_f_206,emb_f_207,emb_f_208,emb_f_209,emb_f_210,emb_f_211,emb_f_212,emb_f_213,emb_f_214,emb_f_215,emb_f_216,emb_f_217,emb_f_218,emb_f_219,emb_f_220,emb_f_221,emb_f_222,emb_f_223,emb_f_224,emb_f_225,emb_f_226,emb_f_227,emb_f_228,emb_f_229,emb_f_230,emb_f_231,emb_f_232,emb_f_233,emb_f_234,emb_f_235,emb_f_236,emb_f_237,emb_f_238,emb_f_239,emb_f_240,emb_f_241,emb_f_242,emb_f_243,emb_f_244,emb_f_245,emb_f_246,emb_f_247,emb_f_248,emb_f_249,emb_f_250,emb_f_251,emb_f_252,emb_f_253,emb_f_254,emb_f_255,emb_f_256,emb_f_257,emb_f_258,emb_f_259,emb_f_260,emb_f_261,emb_f_262,emb_f_263,emb_f_264,emb_f_265,emb_f_266,emb_f_267,emb_f_268,emb_f_269,emb_f_270,emb_f_271,emb_f_272,emb_f_273,emb_f_274,emb_f_275,emb_f_276,emb_f_277,emb_f_278,emb_f_279,emb_f_280,emb_f_281,emb_f_282,emb_f_283,emb_f_284,emb_f_285,emb_f_286,emb_f_287,emb_f_288,emb_f_289,emb_f_290,emb_f_291,emb_f_292,emb_f_293,emb_f_294,emb_f_295,emb_f_296,emb_f_297,emb_f_298,emb_f_299,emb_f_300,emb_f_301,emb_f_302,emb_f_303,emb_f_304,emb_f_305,emb_f_306,emb_f_307,emb_f_308,emb_f_309,emb_f_310,emb_f_311,emb_f_312,emb_f_313,emb_f_314,emb_f_315,emb_f_316,emb_f_317,emb_f_318,emb_f_319,emb_f_320,emb_f_321,emb_f_322,emb_f_323,emb_f_324,emb_f_325,emb_f_326,emb_f_327,emb_f_328,emb_f_329,emb_f_330,emb_f_331,emb_f_332,emb_f_333,emb_f_334,emb_f_335,emb_f_336,emb_f_337,emb_f_338,emb_f_339,emb_f_340,emb_f_341,emb_f_342,emb_f_343,emb_f_344,emb_f_345,emb_f_346,emb_f_347,emb_f_348,emb_f_349,emb_f_350,emb_f_351,emb_f_352,emb_f_353,emb_f_354,emb_f_355,emb_f_356,emb_f_357,emb_f_358,emb_f_359,emb_f_360,emb_f_361,emb_f_362,emb_f_363,emb_f_364,emb_f_365,emb_f_366,emb_f_367,emb_f_368,emb_f_369,emb_f_370,emb_f_371,emb_f_372,emb_f_373,emb_f_374,emb_f_375,emb_f_376,emb_f_377,emb_f_378,emb_f_379,emb_f_380,emb_f_381,emb_f_382,emb_f_383,emb_s_0,emb_s_1,emb_s_2,emb_s_3,emb_s_4,emb_s_5,emb_s_6,emb_s_7,emb_s_8,emb_s_9,emb_s_10,emb_s_11,emb_s_12,emb_s_13,emb_s_14,emb_s_15,emb_s_16,emb_s_17,emb_s_18,emb_s_19,emb_s_20,emb_s_21,emb_s_22,emb_s_23,emb_s_24,emb_s_25,emb_s_26,emb_s_27,emb_s_28,emb_s_29,emb_s_30,emb_s_31,emb_s_32,emb_s_33,emb_s_34,emb_s_35,emb_s_36,emb_s_37,emb_s_38,emb_s_39,emb_s_40,emb_s_41,emb_s_42,emb_s_43,emb_s_44,emb_s_45,emb_s_46,emb_s_47,emb_s_48,emb_s_49,emb_s_50,emb_s_51,emb_s_52,emb_s_53,emb_s_54,emb_s_55,emb_s_56,emb_s_57,emb_s_58,emb_s_59,emb_s_60,emb_s_61,emb_s_62,emb_s_63,emb_s_64,emb_s_65,emb_s_66,emb_s_67,emb_s_68,emb_s_69,emb_s_70,emb_s_71,emb_s_72,emb_s_73,emb_s_74,emb_s_75,emb_s_76,emb_s_77,emb_s_78,emb_s_79,emb_s_80,emb_s_81,emb_s_82,emb_s_83,emb_s_84,emb_s_85,emb_s_86,emb_s_87,emb_s_88,emb_s_89,emb_s_90,emb_s_91,emb_s_92,emb_s_93,emb_s_94,emb_s_95,emb_s_96,emb_s_97,emb_s_98,emb_s_99,emb_s_100,emb_s_101,emb_s_102,emb_s_103,emb_s_104,emb_s_105,emb_s_106,emb_s_107,emb_s_108,emb_s_109,emb_s_110,emb_s_111,emb_s_112,emb_s_113,emb_s_114,emb_s_115,emb_s_116,emb_s_117,emb_s_118,emb_s_119,emb_s_120,emb_s_121,emb_s_122,emb_s_123,emb_s_124,emb_s_125,emb_s_126,emb_s_127,emb_s_128,emb_s_129,emb_s_130,emb_s_131,emb_s_132,emb_s_133,emb_s_134,emb_s_135,emb_s_136,emb_s_137,emb_s_138,emb_s_139,emb_s_140,emb_s_141,emb_s_142,emb_s_143,emb_s_144,emb_s_145,emb_s_146,emb_s_147,emb_s_148,emb_s_149,emb_s_150,emb_s_151,emb_s_152,emb_s_153,emb_s_154,emb_s_155,emb_s_156,emb_s_157,emb_s_158,emb_s_159,emb_s_160,emb_s_161,emb_s_162,emb_s_163,emb_s_164,emb_s_165,emb_s_166,emb_s_167,emb_s_168,emb_s_169,emb_s_170,emb_s_171,emb_s_172,emb_s_173,emb_s_174,emb_s_175,emb_s_176,emb_s_177,emb_s_178,emb_s_179,emb_s_180,emb_s_181,emb_s_182,emb_s_183,emb_s_184,emb_s_185,emb_s_186,emb_s_187,emb_s_188,emb_s_189,emb_s_190,emb_s_191,emb_s_192,emb_s_193,emb_s_194,emb_s_195,emb_s_196,emb_s_197,emb_s_198,emb_s_199,emb_s_200,emb_s_201,emb_s_202,emb_s_203,emb_s_204,emb_s_205,emb_s_206,emb_s_207,emb_s_208,emb_s_209,emb_s_210,emb_s_211,emb_s_212,emb_s_213,emb_s_214,emb_s_215,emb_s_216,emb_s_217,emb_s_218,emb_s_219,emb_s_220,emb_s_221,emb_s_222,emb_s_223,emb_s_224,emb_s_225,emb_s_226,emb_s_227,emb_s_228,emb_s_229,emb_s_230,emb_s_231,emb_s_232,emb_s_233,emb_s_234,emb_s_235,emb_s_236,emb_s_237,emb_s_238,emb_s_239,emb_s_240,emb_s_241,emb_s_242,emb_s_243,emb_s_244,emb_s_245,emb_s_246,emb_s_247,emb_s_248,emb_s_249,emb_s_250,emb_s_251,emb_s_252,emb_s_253,emb_s_254,emb_s_255,emb_s_256,emb_s_257,emb_s_258,emb_s_259,emb_s_260,emb_s_261,emb_s_262,emb_s_263,emb_s_264,emb_s_265,emb_s_266,emb_s_267,emb_s_268,emb_s_269,emb_s_270,emb_s_271,emb_s_272,emb_s_273,emb_s_274,emb_s_275,emb_s_276,emb_s_277,emb_s_278,emb_s_279,emb_s_280,emb_s_281,emb_s_282,emb_s_283,emb_s_284,emb_s_285,emb_s_286,emb_s_287,emb_s_288,emb_s_289,emb_s_290,emb_s_291,emb_s_292,emb_s_293,emb_s_294,emb_s_295,emb_s_296,emb_s_297,emb_s_298,emb_s_299,emb_s_300,emb_s_301,emb_s_302,emb_s_303,emb_s_304,emb_s_305,emb_s_306,emb_s_307,emb_s_308,emb_s_309,emb_s_310,emb_s_311,emb_s_312,emb_s_313,emb_s_314,emb_s_315,emb_s_316,emb_s_317,emb_s_318,emb_s_319,emb_s_320,emb_s_321,emb_s_322,emb_s_323,emb_s_324,emb_s_325,emb_s_326,emb_s_327,emb_s_328,emb_s_329,emb_s_330,emb_s_331,emb_s_332,emb_s_333,emb_s_334,emb_s_335,emb_s_336,emb_s_337,emb_s_338,emb_s_339,emb_s_340,emb_s_341,emb_s_342,emb_s_343,emb_s_344,emb_s_345,emb_s_346,emb_s_347,emb_s_348,emb_s_349,emb_s_350,emb_s_351,emb_s_352,emb_s_353,emb_s_354,emb_s_355,emb_s_356,emb_s_357,emb_s_358,emb_s_359,emb_s_360,emb_s_361,emb_s_362,emb_s_363,emb_s_364,emb_s_365,emb_s_366,emb_s_367,emb_s_368,emb_s_369,emb_s_370,emb_s_371,emb_s_372,emb_s_373,emb_s_374,emb_s_375,emb_s_376,emb_s_377,emb_s_378,emb_s_379,emb_s_380,emb_s_381,emb_s_382,emb_s_383
0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2026-03-23T13:31:06Z,Apple;JPMorgan;Netflix;Pfizer,0.038025,0.018858,-0.086595,0.008641,0.034031,-0.018835,0.076140,0.012036,0.033506,0.011971,0.063189,0.016846,0.076012,-0.084967,-0.045191,0.040121,0.061898,-0.002628,-0.024180,-0.058232,0.025985,-0.023125,-0.056735,0.033251,0.064188,0.080117,-0.064643,0.014658,-0.027111,-0.049215,-0.059584,-0.063907,0.061834,-0.099122,0.044907,0.019759,-0.036929,-0.049866,0.058166,-0.033384,-0.035382,0.026429,0.025998,0.103433,0.055798,0.024773,-0.017467,0.031075,-0.056646,-0.020733,-0.065451,0.031899,0.045822,0.057932,0.054153,-0.039517,-0.090263,-0.080082,-0.020314,-0.002660,0.092827,-0.051519,0.036129,-0.014263,0.040663,0.033581,-0.004201,0.033415,-0.060745,0.014824,-0.009569,0.043846,0.015037,-0.065885,0.031751,0.102630,0.049452,-0.019729,0.023484,0.011308,-0.059146,-0.077472,-0.029474,0.047105,-0.028209,0.081943,0.071144,-0.072979,0.081368,-0.023541,-0.024118,0.047241,-0.065265,-0.035430,-0.048655,-0.049407,-0.033535,0.096568,0.070078,-0.018527,0.082767,-0.074878,0.046550,-0.021118,-0.063131,0.019430,0.040776,-0.055604,0.085321,-0.074215,-0.028909,0.018009,0.069572,0.016697,-0.081627,-0.068889,-0.028755,-0.072625,0.012519,-0.044597,0.093571,-0.033167,-0.016155,-0.096866,-0.072974,-0.035678,0.016550,0.034578,0.063297,0.020400,0.015024,0.044000,0.056340,0.077235,0.081252,0.103822,-0.085244,-0.002350,-0.043159,-0.062273,-0.025932,0.095033,-0.035358,0.051496,0.056035,0.040303,0.051378,-0.028961,0.037197,-0.007587,0.035918,-0.060254,0.078566,0.034235,0.062392,-0.075872,-0.053853,-0.032895,0.033365,0.066921,-0.027530,-0.036516,-0.102985,0.014247,-0.028739,-0.022980,0.021429,0.064870,0.003385,-0.005851,-0.065104,0.047444,-0.039536,0.057797,0.012176,0.053917,-0.094062,-0.008078,0.057595,0.050228,-0.064663,-0.032880,-0.073867,-0.063811,-0.034164,-0.065423,-0.040367,0.063859,0.008450,-0.015013,0.024284,0.017185,-0.066683,-0.073007,-0.046892,0.071188,-0.052892,0.045286,0.020603,0.016777,-0.028692,-0.011352,0.048107,0.056427,0.016846,0.023313,-0.029326,0.067730,-0.037509,0.052975,0.067621,-0.068742,-0.074349,0.082270,-0.039638,-0.025498,0.021231,0.035030,-0.077371,0.030676,0.089377,-0.049328,0.047179,-0.072956,-0.005441,0.043417,0.080251,-0.047452,-0.053972,0.011236,-0.054727,-0.007871,-0.051056,-0.008326,-0.062684,-0.055155,-0.009197,0.060596,-0.000216,-0.038149,-0.075700,-0.015891,0.013155,-0.060592,0.071692,-0.032164,-0.054593,0.040430,0.021232,0.042799,0.047348,-0.058623,-0.070587,-0.003159,-0.044039,0.103689,0.067558,0.058313,-0.087304,0.038223,0.048917,-0.036565,0.045964,0.022143,0.047641,0.045015,-0.003066,-0.062033,-0.035443,-0.028948,-0.057692,0.036809,0.023672,0.003128,-0.054957,-0.045523,-0.010000,0.073081,-0.044362,-0.039034,0.045809,0.021007,0.022405,0.077515,0.060358,-0.021224,-0.015320,0.054028,-0.081312,-0.049697,-0.053018,-0.056819,0.063424,-0.021582,0.046387,0.056845,0.004724,0.062874,-0.041765,0.002014,-0.008127,-0.011316,0.035344,0.064695,-0.068760,0.012563,0.039127,0.043441,0.002915,0.023517,0.062380,0.050161,-0.030371,-0.025255,0.013294,0.069298,-0.033984,0.030053,-0.053445,-0.084558,-0.038507,-0.053299,-0.072722,-0.047565,-0.008606,0.040937,-0.037393,-0.038561,0.026209,-0.028136,0.013004,-0.038102,-0.030115,0.055816,-0.075088,-0.012603,0.014443,0.055649,-0.086399,-0.108251,0.007392,-0.012850,-0.034204,0.034605,-0.000295,-0.010119,0.033695,-0.067820,-0.021389,0.022009,0.055020,-0.094434,0.013761,0.056713,-0.049651,0.048126,-0.099841,-0.022538,0.077094,0.070519,-0.098684,-0.011535,0.026741,0.060796,0.073505,0.072355,-0.047605,0.001703,0.088197,-0.030249,0.029592,0.043072,-0.026665,0.007139,-0.053185,-0.053847,-0.034330,0.014471,-0.056053,-0.058262,0.029631,0.054520,0.027139,0.047965,0.040767,-0.004040,-0.046337,-0.014811,0.040611,-0.010620,0.044254,0.013120,0.036194,0.018884,0.031054,0.031754,0.129609,-0.062060,-0.056044,0.053686,0.057087,-0.020003,-0.012454,-0.055738,0.050742,-0.013561,-0.065082,0.029517,0.082369,0.065359,-0.044736,-0.005920,0.010175,-0.036621,-0.071598,-0.023848,0.036660,-0.070989,0.040069,-0.026920,-0.018506,-0.051732,0.027044,-0.042824,-0.028519,0.047341,0.026070,0.084268,0.039830,0.056819,-0.054161,0.024377,-0.041979,0.003022,-0.041287,0.045567,0.051195,0.057424,0.019930,-0.021579,-0.086711,-0.032562,-0.063368,-0.028123,0.036148,-0.029318,0.072835,0.026854,0.088820,0.026451,0.047715,0.071564,-0.097009,-0.003493,-0.035935,0.062983,0.027219,-0.071795,0.066632,0.036529,0.038189,-0.038420,0.026262,0.001615,-0.087280,-0.029053,-0.061329,0.058182,-0.048381,0.049201,0.037077,-0.084314,0.014356,-0.013517,-0.012782,0.027093,-0.036443,-0.067015,-0.110201,-0.092586,-0.051940,0.096052,0.052000,-0.008403,0.047236,-0.054892,0.021642,-0.034692,-0.033301,0.059758,0.003524,-0.084059,0.059620,-0.053642,-0.024931,-0.014200,0.079504,0.037866,-0.072228,-0.046220,-0.020936,-0.054228,0.006330,-0.020747,0.042204,-0.022134,-0.035083,-0.091877,-0.046878,-0.074446,0.038034,0.067828,0.012553,-0.009023,-0.015104,0.037852,0.033808,0.070706,0.069046,0.116860,-0.038927,-0.029981,-0.024866,-0.040821,-0.062569,0.098354,-0.007376,0.061076,0.065264,0.017928,0.053361,-0.039070,0.085992,0.015151,0.051412,-0.032651,0.106014,-0.011596,0.080549,-0.042238,-0.048191,0.007423,0.047633,0.066545,-0.041050,-0.038043,-0.074137,-0.033137,-0.044501,-0.015798,-0.017903,0.103386,-0.017347,-0.034986,-0.039236,0.079811,-0.000778,0.036736,0.010082,0.058886,-0.082035,0.050486,0.067481,0.054545,-0.042083,-0.052850,-0.086020,-0.041989,-0.046380,-0.032107,-0.020886,0.030079,-0.009112,0.003248,-0.049515,0.003059,-0.071004,-0.050848,-0.062620,0.039929,-0.084031,0.055318,0.065514,0.003238,-0.011861,-0.032650,0.032536,0.087276,-0.001354,0.027448,-0.094680,0.063133,-0.058522,0.055877,0.077698,-0.065921,-0.057338,0.060385,-0.018339,-0.030418,0.005494,0.038300,-0.046053,-0.005912,0.064156,-0.031830,0.034192,-0.070436,-0.052327,0.050217,0.079865,-0.068644,-0.058226,0.025113,-0.052526,-0.063865,-0.067269,-0.080222,-0.042596,-0.063483,-0.017006,0.062596,0.060179,-0.022693,-0.018367,-0.040721,-0.001501,-0.030196,0.040809,0.003728,-0.080379,0.037593,-0.005233,0.005013,0.062717,-0.094904,-0.014511,0.034535,-0.038529,0.015553,0.054461,0.100801,-0.062069,0.065487,0.011642,-0.060437,0.080241,0.055169,0.014928,0.022090,-0.027453,-0.032506,-0.055912,-0.045995,-0.036213,0.026336,0.019682,-0.040847,-0.059817,-0.066637,-0.012994,0.068549,-0.045934,0.011099,0.034099,0.017954,0.079103,0.058994,0.039454,0.002911,-0.021366,0.081629,-0.072629,-0.067441,-0.028045,-0.063753,0.005768,-0.051781,0.050276,0.027067,0.018209,0.117146,-0.026327,0.018740,-0.007092,-0.029028,0.012364,0.039105,-0.108621,0.045206,0.047720,0.055394,-0.019313,0.041532,0.028202,0.048321,-0.035827,-0.040251,0.037282,0.075855,0.009400,0.045396,-0.040603,-0.080909,-0.040211,-0.071061,-0.003528,-0.030475,-0.011443,0.008978,-0.052625,-0.032738,0.023790,0.002214,0.042078,-0.046329,0.002772,0.004949,-0.077081,0.028206,-0.015100,0.074825,-0.063524,-0.081832,0.007063,0.051127,-0.030501,0.070287,-0.038490,-0.025016,0.021127,-0.027734,-0.017951,0.022635,0.073952,-0.111178,-0.005855,0.049742,-0.066293,0.025009,-0.101077,-0.008237,0.085511,0.074662,-0.061105,-0.054935,-0.004085,0.083927,0.054774,0.045717,-0.045725,0.004560,0.078146,-0.031801,0.066601,0.006289,-0.026726,0.006637,-0.018801,-0.012216,-0.004009,0.051951,-0.047047,-0.068557,0.049680,0.044040,0.047342,0.106844

In [177]:
data_f

,Benzinga,CNBC,ChartMill,DowJones,MarketWatch,SeekingAlpha,The Guardian,Yahoo,AAPL,TSLA,CAT,JPM,NFLX,PFE,XOM,WMT,webPublicationDate,company,emb_f_0,emb_f_1,emb_f_2,emb_f_3,emb_f_4,emb_f_5,emb_f_6,emb_f_7,emb_f_8,emb_f_9,emb_f_10,emb_f_11,emb_f_12,emb_f_13,emb_f_14,emb_f_15,emb_f_16,emb_f_17,emb_f_18,emb_f_19,emb_f_20,emb_f_21,emb_f_22,emb_f_23,emb_f_24,emb_f_25,emb_f_26,emb_f_27,emb_f_28,emb_f_29,emb_f_30,emb_f_31,emb_f_32,emb_f_33,emb_f_34,emb_f_35,emb_f_36,emb_f_37,emb_f_38,emb_f_39,emb_f_40,emb_f_41,emb_f_42,emb_f_43,emb_f_44,emb_f_45,emb_f_46,emb_f_47,emb_f_48,emb_f_49,emb_f_50,emb_f_51,emb_f_52,emb_f_53,emb_f_54,emb_f_55,emb_f_56,emb_f_57,emb_f_58,emb_f_59,emb_f_60,emb_f_61,emb_f_62,emb_f_63,emb_f_64,emb_f_65,emb_f_66,emb_f_67,emb_f_68,emb_f_69,emb_f_70,emb_f_71,emb_f_72,emb_f_73,emb_f_74,emb_f_75,emb_f_76,emb_f_77,emb_f_78,emb_f_79,emb_f_80,emb_f_81,emb_f_82,emb_f_83,emb_f_84,emb_f_85,emb_f_86,emb_f_87,emb_f_88,emb_f_89,emb_f_90,emb_f_91,emb_f_92,emb_f_93,emb_f_94,emb_f_95,emb_f_96,emb_f_97,emb_f_98,emb_f_99,emb_f_100,emb_f_101,emb_f_102,emb_f_103,emb_f_104,emb_f_105,emb_f_106,emb_f_107,emb_f_108,emb_f_109,emb_f_110,emb_f_111,emb_f_112,emb_f_113,emb_f_114,emb_f_115,emb_f_116,emb_f_117,emb_f_118,emb_f_119,emb_f_120,emb_f_121,emb_f_122,emb_f_123,emb_f_124,emb_f_125,emb_f_126,emb_f_127,emb_f_128,emb_f_129,emb_f_130,emb_f_131,emb_f_132,emb_f_133,emb_f_134,emb_f_135,emb_f_136,emb_f_137,emb_f_138,emb_f_139,emb_f_140,emb_f_141,emb_f_142,emb_f_143,emb_f_144,emb_f_145,emb_f_146,emb_f_147,emb_f_148,emb_f_149,emb_f_150,emb_f_151,emb_f_152,emb_f_153,emb_f_154,emb_f_155,emb_f_156,emb_f_157,emb_f_158,emb_f_159,emb_f_160,emb_f_161,emb_f_162,emb_f_163,emb_f_164,emb_f_165,emb_f_166,emb_f_167,emb_f_168,emb_f_169,emb_f_170,emb_f_171,emb_f_172,emb_f_173,emb_f_174,emb_f_175,emb_f_176,emb_f_177,emb_f_178,emb_f_179,emb_f_180,emb_f_181,emb_f_182,emb_f_183,emb_f_184,emb_f_185,emb_f_186,emb_f_187,emb_f_188,emb_f_189,emb_f_190,emb_f_191,emb_f_192,emb_f_193,emb_f_194,emb_f_195,emb_f_196,emb_f_197,emb_f_198,emb_f_199,emb_f_200,emb_f_201,emb_f_202,emb_f_203,emb_f_204,emb_f_205,emb_f_206,emb_f_207,emb_f_208,emb_f_209,emb_f_210,emb_f_211,emb_f_212,emb_f_213,emb_f_214,emb_f_215,emb_f_216,emb_f_217,emb_f_218,emb_f_219,emb_f_220,emb_f_221,emb_f_222,emb_f_223,emb_f_224,emb_f_225,emb_f_226,emb_f_227,emb_f_228,emb_f_229,emb_f_230,emb_f_231,emb_f_232,emb_f_233,emb_f_234,emb_f_235,emb_f_236,emb_f_237,emb_f_238,emb_f_239,emb_f_240,emb_f_241,emb_f_242,emb_f_243,emb_f_244,emb_f_245,emb_f_246,emb_f_247,emb_f_248,emb_f_249,emb_f_250,emb_f_251,emb_f_252,emb_f_253,emb_f_254,emb_f_255,emb_f_256,emb_f_257,emb_f_258,emb_f_259,emb_f_260,emb_f_261,emb_f_262,emb_f_263,emb_f_264,emb_f_265,emb_f_266,emb_f_267,emb_f_268,emb_f_269,emb_f_270,emb_f_271,emb_f_272,emb_f_273,emb_f_274,emb_f_275,emb_f_276,emb_f_277,emb_f_278,emb_f_279,emb_f_280,emb_f_281,emb_f_282,emb_f_283,emb_f_284,emb_f_285,emb_f_286,emb_f_287,emb_f_288,emb_f_289,emb_f_290,emb_f_291,emb_f_292,emb_f_293,emb_f_294,emb_f_295,emb_f_296,emb_f_297,emb_f_298,emb_f_299,emb_f_300,emb_f_301,emb_f_302,emb_f_303,emb_f_304,emb_f_305,emb_f_306,emb_f_307,emb_f_308,emb_f_309,emb_f_310,emb_f_311,emb_f_312,emb_f_313,emb_f_314,emb_f_315,emb_f_316,emb_f_317,emb_f_318,emb_f_319,emb_f_320,emb_f_321,emb_f_322,emb_f_323,emb_f_324,emb_f_325,emb_f_326,emb_f_327,emb_f_328,emb_f_329,emb_f_330,emb_f_331,emb_f_332,emb_f_333,emb_f_334,emb_f_335,emb_f_336,emb_f_337,emb_f_338,emb_f_339,emb_f_340,emb_f_341,emb_f_342,emb_f_343,emb_f_344,emb_f_345,emb_f_346,emb_f_347,emb_f_348,emb_f_349,emb_f_350,emb_f_351,emb_f_352,emb_f_353,emb_f_354,emb_f_355,emb_f_356,emb_f_357,emb_f_358,emb_f_359,emb_f_360,emb_f_361,emb_f_362,emb_f_363,emb_f_364,emb_f_365,emb_f_366,emb_f_367,emb_f_368,emb_f_369,emb_f_370,emb_f_371,emb_f_372,emb_f_373,emb_f_374,emb_f_375,emb_f_376,emb_f_377,emb_f_378,emb_f_379,emb_f_380,emb_f_381,emb_f_382,emb_f_383
0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2026-03-23T13:31:06Z,Apple;JPMorgan;Netflix;Pfizer,0.038025,0.018858,-0.086595,0.008641,0.034031,-0.018835,0.076140,0.012036,0.033506,0.011971,0.063189,0.016846,0.076012,-0.084967,-0.045191,0.040121,0.061898,-0.002628,-0.024180,-0.058232,0.025985,-0.023125,-0.056735,0.033251,0.064188,0.080117,-0.064643,0.014658,-0.027111,-0.049215,-0.059584,-0.063907,0.061834,-0.099122,0.044907,0.019759,-0.036929,-0.049866,0.058166,-0.033384,-0.035382,0.026429,0.025998,0.103433,0.055798,0.024773,-0.017467,0.031075,-0.056646,-0.020733,-0.065451,0.031899,0.045822,0.057932,0.054153,-0.039517,-0.090263,-0.080082,-0.020314,-0.002660,0.092827,-0.051519,0.036129,-0.014263,0.040663,0.033581,-0.004201,0.033415,-0.060745,0.014824,-0.009569,0.043846,0.015037,-0.065885,0.031751,0.102630,0.049452,-0.019729,0.023484,0.011308,-0.059146,-0.077472,-0.029474,0.047105,-0.028209,0.081943,0.071144,-0.072979,0.081368,-0.023541,-0.024118,0.047241,-0.065265,-0.035430,-0.048655,-0.049407,-0.033535,0.096568,0.070078,-0.018527,0.082767,-0.074878,0.046550,-0.021118,-0.063131,0.019430,0.040776,-0.055604,0.085321,-0.074215,-0.028909,0.018009,0.069572,0.016697,-0.081627,-0.068889,-0.028755,-0.072625,0.012519,-0.044597,0.093571,-0.033167,-0.016155,-0.096866,-0.072974,-0.035678,0.016550,0.034578,0.063297,0.020400,0.015024,0.044000,0.056340,0.077235,0.081252,0.103822,-0.085244,-0.002350,-0.043159,-0.062273,-0.025932,0.095033,-0.035358,0.051496,0.056035,0.040303,0.051378,-0.028961,0.037197,-0.007587,0.035918,-0.060254,0.078566,0.034235,0.062392,-0.075872,-0.053853,-0.032895,0.033365,0.066921,-0.027530,-0.036516,-0.102985,0.014247,-0.028739,-0.022980,0.021429,0.064870,0.003385,-0.005851,-0.065104,0.047444,-0.039536,0.057797,0.012176,0.053917,-0.094062,-0.008078,0.057595,0.050228,-0.064663,-0.032880,-0.073867,-0.063811,-0.034164,-0.065423,-0.040367,0.063859,0.008450,-0.015013,0.024284,0.017185,-0.066683,-0.073007,-0.046892,0.071188,-0.052892,0.045286,0.020603,0.016777,-0.028692,-0.011352,0.048107,0.056427,0.016846,0.023313,-0.029326,0.067730,-0.037509,0.052975,0.067621,-0.068742,-0.074349,0.082270,-0.039638,-0.025498,0.021231,0.035030,-0.077371,0.030676,0.089377,-0.049328,0.047179,-0.072956,-0.005441,0.043417,0.080251,-0.047452,-0.053972,0.011236,-0.054727,-0.007871,-0.051056,-0.008326,-0.062684,-0.055155,-0.009197,0.060596,-0.000216,-0.038149,-0.075700,-0.015891,0.013155,-0.060592,0.071692,-0.032164,-0.054593,0.040430,0.021232,0.042799,0.047348,-0.058623,-0.070587,-0.003159,-0.044039,0.103689,0.067558,0.058313,-0.087304,0.038223,0.048917,-0.036565,0.045964,0.022143,0.047641,0.045015,-0.003066,-0.062033,-0.035443,-0.028948,-0.057692,0.036809,0.023672,0.003128,-0.054957,-0.045523,-0.010000,0.073081,-0.044362,-0.039034,0.045809,0.021007,0.022405,0.077515,0.060358,-0.021224,-0.015320,0.054028,-0.081312,-0.049697,-0.053018,-0.056819,0.063424,-0.021582,0.046387,0.056845,0.004724,0.062874,-0.041765,0.002014,-0.008127,-0.011316,0.035344,0.064695,-0.068760,0.012563,0.039127,0.043441,0.002915,0.023517,0.062380,0.050161,-0.030371,-0.025255,0.013294,0.069298,-0.033984,0.030053,-0.053445,-0.084558,-0.038507,-0.053299,-0.072722,-0.047565,-0.008606,0.040937,-0.037393,-0.038561,0.026209,-0.028136,0.013004,-0.038102,-0.030115,0.055816,-0.075088,-0.012603,0.014443,0.055649,-0.086399,-0.108251,0.007392,-0.012850,-0.034204,0.034605,-0.000295,-0.010119,0.033695,-0.067820,-0.021389,0.022009,0.055020,-0.094434,0.013761,0.056713,-0.049651,0.048126,-0.099841,-0.022538,0.077094,0.070519,-0.098684,-0.011535,0.026741,0.060796,0.073505,0.072355,-0.047605,0.001703,0.088197,-0.030249,0.029592,0.043072,-0.026665,0.007139,-0.053185,-0.053847,-0.034330,0.014471,-0.056053,-0.058262,0.029631,0.054520,0.027139,0.047965
1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2025-07-23T10:56:43Z,Apple;JPMorgan;Netflix;Walmart,0.063344,-0.027066,-0.077756,-0.007702,0.047996,-0.012781,0.075448,0.040036,0.050231,-0.003585,0.053250,0.037678,0.072940,-0.066772,-0.072776,0.014891,0.036101,-0.026003,-0.002364,-0.058332,0.027617,-0.048223,-0.022559,0.053491,0.074854,0.080974,-0.053237,-0.002209,-0.017568,-0.058176,-0.054454,0.017713,0.059692,-0.067532,0.011322,0.010722,-0.064136,-0.026670,0.092824,-0.010815,-0.060009,0.008249,0.054248,0.087181,0.070467,0.072231,-0.044400,0.057658,-0.078463,-0.022624,-0.041246,0.043350,0.029149,0.090227,0.034398,-0.041394,-0.113025,-0.046834,-0.024755,0.015420,0.086966,-0.032214,0.033181,-0.001795,0.061823,0.023790,-0.004385,0.036800,-0.086708,-0.008151,-0.043502,0.056718,-0.030215,-0.094894,0.054222,0.089060,0.045321,-0.044411,0.006930,-0.063909,-0.076677,-0.010912,-0.055076,0.023341,-0.008475,0.044414,0.053424,-0.051679,0.074949,-0.037831,0.019857,0.047685,-0.034098,-0.017592,-0.044719,-0.075274,-0.039594,0.082321,0.028902,-0.042770,0.058999,-0.011621,0.039243,-0.044345,-0.016991,0.001523,-0.004682,-0.019764,0.058623,-0.067271,-0.047419,0.045758,0.097940,0.014345,-0.078316,-0.087435,-0.045580,-0.061486,0.079578,-0.041511,0.051861,-0.010323,-0.061025,-0.066659,-0.066315,-0.025181,0.035682,0.028692,0.060862,0.030583,0.013307,0.052936,0.094238,0.005493,0.048413,0.058744,-0.062454,-0.022591,-0.059648,-0.053568,-0.049826,0.096682,0.003626,0.086746,0.045703,0.023921,0.055147,-0.015017,0.091932,-0.029696,0.061346,-0.052417,0.027863,0.034696,0.087372,-0.033044,-0.073538,-0.055979,0.039502,0.036444,-0.071803,-0.046628,-0.070230,-0.023600,-0.035747,-0.048772,0.041333,0.069509,-0.018716,-0.002499,-0.090819,0.040672,-0.046789,0.026393,-0.022201,0.061757,-0.036505,0.018435,0.053017,0.054454,-0.057144,-0.051460,-0.047907,-0.051337,-0.002081,-0.030382,-0.040289,0.017360,-0.007910,-0.022142,-0.005797,0.059265,-0.053755,-0.058672,-0.053070,0.052950,-0.072515,0.025912,0.026659,0.016352,-0.016453,-0.067204,-0.001677,0.021946,0.026379,0.026991,-0.070491,0.068734,-0.059981,0.042474,0.090094,-0.052198,-0.060088,0.024873,-0.023520,-0.011492,0.031962,0.007952,-0.039503,0.033916,0.061987,-0.072416,0.034827,-0.091484,-0.026083,0.066637,0.076007,-0.035631,-0.048570,0.046002,-0.051374,-0.042497,-0.067649,-0.038282,-0.018445,-0.034292,-0.047557,0.062259,0.012822,-0.060935,-0.084561,-0.022568,-0.024342,-0.073306,0.054214,-0.010732,-0.046805,0.014289,-0.049139,0.002900,0.076238,-0.039865,-0.045386,-0.005450,-0.057898,0.092991,0.021867,0.073400,-0.063315,0.028287,0.050180,-0.008327,0.089652,0.043507,0.063870,0.004773,-0.002810,-0.035379,-0.041628,-0.038909,-0.093704,0.065510,0.035000,-0.028677,-0.025537,-0.042780,0.017206,0.058780,-0.082435,-0.027742,0.062520,0.003519,0.036911,0.063999,0.050685,0.025827,-0.018540,0.064197,-0.048473,-0.027399,-0.066597,-0.084143,0.044144,-0.044625,0.035794,0.087570,-0.015798,0.062863,-0.060773,0.016985,-0.007699,0.021886,0.028798,0.053301,-0.072346,0.017455,0.045710,0.073337,-0.000068,0.035286,0.047633,0.032687,-0.032032,-0.029040,0.050243,0.043173,-0.007165,0.006749,-0.043919,-0.071371,-0.028655,-0.061990,-0.013938,-0.030691,0.034577,0.064712,-0.012042,-0.029040,0.056466,-0.006866,0.043924,-0.058311,-0.042400,0.034405,-0.105581,-0.007263,0.026430,0.050088,-0.084768,-0.069116,-0.026524,0.005182,-0.050139,0.036027,-0.031458,-0.015586,0.012087,-0.059525,-0.058374,0.013943,0.060437,-0.090298,0.021981,0.003307,-0.054396,0.090397,-0.089755,-0.002986,0.080342,0.048168,-0.052339,-0.041117,0.078493,0.066876,0.079133,0.055653,-0.052663,0.013858,0.078780,-0.066019,0.062992,0.091551,-0.042436,0.019571,-0.003397,-0.032174,-0.055292,0.042096,-0.070391,-0.035049,0.034543,0.080313,0.042996,0.072699
2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2025-09-14T14:00:35Z,Apple;Exxon;Pfizer,0.014886,-0.047357,-0.056452,-0.016591,0.051266,-0.032599,0.065681,0.041382,0.049431,0.020378,0.018445,0.003411,0.053370,-0.094703,-0.041708,0.104508,0.040316,-0.055889,-0.012167,-0.101924,0.086739,0.005834,-0.020963,0.039627,0.042741,0.019948,-0.050720,-0.024801,0.053206,-0.055213,-0.082802,-0.040803,0.017866,-0.047742,0.067044,0.017197,-0.080163,-0.043159,0.078847,-0.010726,-0.040691,0.019738,0.044111,0.067377,0.029317,0.063999,-0.030625,0.028559,-0.029131,-0.055526,-0.117984,0.049488,0.002919,0.040245,0.018907,-0.051983,-0.056183,-0.094019,-0.063334,0.073396,0.099344,-0.056453,0.022341,0.033023,0.103429,0.044138,0.003086,-0.020429,-0.037099,-0.014356,-0.039550,0.071303,-0.013266,-0.048048,0.009868,0.023748,0.041390,-0.047876,0.034495,-0.040101,-0.046639,-0.011385,-0.046300,0.017176,-0.041821,0.061407,0.056017,-0.070304,0.064916,-0.037764,0.041692,0.018168,-0.043553,-0.076496,-0.039944,-0.071484,-0.070637,0.069771,0.058560,-0.023038,0.074760,-0.029058,0.034143,-0.039449,-0.029837,0.020054,0.047233,-0.047577,0.093309,-0.062716,-0.028710,0.057629,0.068918,0.029232,-0.031502,-0.082968,-0.023451,-0.058786,0.049384,-0.034995,0.083576,0.002649,-0.053581,-0.048232,-0.078742,-0.027159,0.049319,0.014932,-0.018612,0.025378,0.022009,0.061884,0.037352,0.027031,0.056644,0.064070,-0.051744,-0.055221,-0.005503,-0.066262,-0.078349,0.044886,-0.067280,0.080993,0.075707,0.077251,0.038735,-0.052648,0.084675,-0.017328,0.043742,-0.018451,0.039248,0.048395,0.057555,-0.080881,-0.101527,-0.058030,0.057166,0.021845,-0.084421,-0.071955,-0.043457,-0.013047,-0.017654,-0.048258,0.028365,0.073981,-0.038797,-0.018310,-0.064873,0.077896,-0.043403,0.043194,-0.037466,0.038873,-0.026033,0.009172,0.010416,0.020406,-0.038418,-0.057864,-0.054425,-0.029118,-0.033082,-0.051487,-0.074690,0.043423,0.065560,-0.037989,0.037166,0.073442,-0.035324,-0.049312,-0.030010,0.010060,-0.035022,0.045803,0.046004,0.046690,0.028173,-0.058164,0.047302,0.021590,0.065160,0.037423,-0.034100,0.072291,-0.036088,0.032645,0.057601,-0.082989,-0.047053,0.035977,-0.016176,-0.024541,-0.001655,0.100966,-0.086904,0.048386,0.048250,-0.030059,0.051355,-0.090625,-0.000414,0.069719,0.042136,-0.049079,-0.064747,0.048091,-0.072186,-0.054163,-0.093505,-0.038796,-0.003736,-0.004098,-0.053410,0.023604,0.061984,-0.026581,-0.045942,-0.027680,0.053410,-0.042284,0.027479,-0.033929,-0.012985,-0.005486,-0.050696,0.034131,0.023872,-0.036687,-0.032232,-0.021185,-0.031906,0.089928,0.054521,0.070662,-0.051495,0.034853,0.060060,-0.031157,0.125951,0.064195,0.035678,0.042779,-0.006912,-0.044660,-0.035794,-0.032873,-0.060019,0.073606,0.027726,-0.051636,-0.057022,0.006608,0.040531,0.080301,-0.027787,-0.052793,0.068582,0.034983,0.022222,0.038788,0.031066,0.027148,-0.033096,0.062844,-0.040106,-0.044728,-0.019103,-0.051635,0.057716,-0.036907,0.083149,0.041115,-0.034600,0.065124,-0.013590,0.021341,-0.029325,-0.030053,0.050832,0.076817,-0.045527,-0.037325,-0.013556,0.010146,-0.026179,0.016032,0.046680,0.076949,-0.028927,-0.031932,0.083946,0.023197,-0.077408,0.005949,-0.028339,-0.067813,0.005381,-0.064639,-0.018977,-0.055934,0.033917,0.069434,0.006602,-0.047521,0.012890,-0.000042,0.019805,-0.066722,-0.073675,0.039397,-0.080175,-0.021523,0.009746,0.059496,-0.082071,-0.048357,0.032316,-0.053157,-0.040640,0.083835,-0.001810,-0.006606,0.037937,-0.044167,-0.068995,-0.004317,0.050430,-0.088138,0.021357,0.044208,-0.042321,0.074449,-0.034165,-0.035603,0.058448,0.024723,-0.090083,-0.009884,0.076502,0.063435,0.065102,0.048138,-0.089089,0.024688,0.048745,-0.049345,0.075558,0.068133,-0.001009,0.064095,-0.030665,-0.042982,-0.049992,-0.001434,-0.060286,-0.070355,0.037051,0.035890,0.057964,0.059643
3,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2025-04-23T12:09:39Z,Apple;Netflix,0.061602,-0.007765,-0.051810,-0.026383,0.035488,-0.018301,0.064582,0.030092,0.031748,0.001156,0.034579,0.035777,0.062577,-0.087198,-0.001576,0.037503,0.038383,-0.006197,-0.025272,-0.086766,0.054465,-0.012305,-0.058864,0.035856,0.083286,0.035277,-0.007147,-0.032102,0.004922,-0.023803,-0.047300,-0.058447,0.049761,-0.059404,0.024835,0.013586,-0.064606,-0.034188,0.063471,-0.025723,-0.057936,0.047559,0.075318,0.091991,0.079021,0.018525,-0.036828,0.042918,-0.046470,-0.020411,-0.035053,0.050866,0.041400,0.048503,0.022158,-0.031946,-0.055107,-0.055940,-0.018514,-0.001432,0.093322,-0.024067,0.053134,-0.041270,0.047238,0.056613,0.048087,0.030056,-0.049654,0.003049,-0.016468,0.008525,0.002823,-0.060899,0.046631,0.046893,0.022569,-0.035921,0.011602,-0.075344,-0.088622,-0.043685,-0.032935,0.015234,0.001465,0.059201,0.029067,-0.068831,0.089392,-0.009839,0.029949,0.055558,-0.058143,-0.059960,-0.058789,-0.044935,-0.019247,0.091679,0.057330,-0.003032,0.089004,-0.051380,0.058648,-0.046360,-0.028290,0.014307,0.015492,-0.063587,0.070999,-0.051460,-0.033274,0.076890,0.088892,0.025191,-0.063623,-0.053814,-0.005619,-0.077591,0.041199,-0.082184,0.087700,-0.022182,-0.040679,-0.082903,-0.088823,-0.000509,0.008120,0.046707,0.054187,0.000127,0.011714,0.050976,0.094447,0.079445,0.068688,0.076578,-0.074220,0.017895,-0.043023,-0.047294,-0.053682,0.048926,-0.012579,0.078968,0.030717,0.058679,0.022796,-0.027138,0.067185,-0.053404,0.045159,-0.060421,0.069637,0.017742,0.065893,-0.106175,-0.091084,-0.040986,0.044934,0.035939,-0.072441,-0.018286,-0.061372,-0.012028,-0.055968,-0.045844,0.007044,0.040937,-0.029646,-0.015070,-0.089408,0.048721,-0.031323,0.094613,0.024636,0.065328,-0.053788,0.038740,0.069450,0.063423,-0.069772,-0.022657,-0.059588,-0.067134,0.013026,-0.049837,-0.038940,0.034980,0.006575,-0.079289,-0.027556,0.016052,-0.028651,-0.064539,-0.033332,0.073433,-0.072369,0.071442,0.022334,0.038223,-0.014848,-0.020806,0.008885,0.013077,0.020968,-0.010966,-0.061336,0.060520,-0.044174,0.068216,0.044932,-0.046284,-0.057375,0.081234,-0.020315,-0.010166,0.067919,0.042777,-0.096284,0.051991,0.076020,-0.041642,0.073564,-0.071568,-0.009189,0.059712,0.078425,-0.049498,-0.051222,0.060974,-0.065816,-0.021047,-0.066698,-0.000947,-0.069094,-0.039581,-0.048505,0.044090,-0.002988,-0.012490,-0.085068,-0.047988,0.006869,-0.084504,0.043471,-0.017743,-0.020489,0.013611,-0.004553,0.018437,0.071876,-0.048089,-0.062517,-0.024287,-0.027393,0.057246,0.038088,0.073587,-0.069068,0.045077,-0.019240,-0.000582,0.058905,0.053547,0.042282,-0.007813,-0.019859,-0.029165,-0.035214,-0.042394,-0.085475,0.046585,0.042670,-0.063350,-0.051370,-0.041791,0.015839,0.074699,-0.062404,-0.057014,0.074831,0.019385,0.050145,0.040370,0.070337,0.007845,-0.040116,0.122648,-0.081640,-0.029557,-0.038594,-0.049580,0.065919,-0.010602,0.026461,0.036816,0.019882,0.045305,-0.067069,0.016514,-0.015446,-0.008113,0.051093,0.070649,-0.077948,0.008201,0.024483,0.014751,0.024325,-0.003257,0.024139,0.013619,-0.046179,0.003470,0.019987,0.081950,-0.023991,0.009234,-0.065788,-0.044432,-0.041147,-0.068262,-0.032863,-0.027806,0.025152,0.047062,-0.030550,0.010602,0.004623,-0.009463,-0.005058,-0.058187,-0.027151,0.087434,-0.071228,0.004199,0.012870,0.024039,-0.129725,-0.063172,0.031464,0.013954,-0.038653,-0.001152,-0.010126,-0.015561,0.022755,-0.060506,-0.044986,0.048772,0.080184,-0.098442,0.047918,0.009951,-0.078116,0.065350,-0.049932,-0.027719,0.048884,0.056840,-0.088333,-0.002226,0.041192,0.104308,0.032819,0.033291,-0.018472,0.016632,0.089289,-0.078799,0.034820,0.093504,-0.006188,0.004460,-0.035258,-0.081374,-0.050513,0.058618,-0.081333,-0.068333,0.020050,0.034385,0.014027,0.072408

In [178]:
data_s

,Benzinga,CNBC,ChartMill,DowJones,MarketWatch,SeekingAlpha,The Guardian,Yahoo,AAPL,TSLA,CAT,JPM,NFLX,PFE,XOM,WMT,webPublicationDate,company,emb_s_0,emb_s_1,emb_s_2,emb_s_3,emb_s_4,emb_s_5,emb_s_6,emb_s_7,emb_s_8,emb_s_9,emb_s_10,emb_s_11,emb_s_12,emb_s_13,emb_s_14,emb_s_15,emb_s_16,emb_s_17,emb_s_18,emb_s_19,emb_s_20,emb_s_21,emb_s_22,emb_s_23,emb_s_24,emb_s_25,emb_s_26,emb_s_27,emb_s_28,emb_s_29,emb_s_30,emb_s_31,emb_s_32,emb_s_33,emb_s_34,emb_s_35,emb_s_36,emb_s_37,emb_s_38,emb_s_39,emb_s_40,emb_s_41,emb_s_42,emb_s_43,emb_s_44,emb_s_45,emb_s_46,emb_s_47,emb_s_48,emb_s_49,emb_s_50,emb_s_51,emb_s_52,emb_s_53,emb_s_54,emb_s_55,emb_s_56,emb_s_57,emb_s_58,emb_s_59,emb_s_60,emb_s_61,emb_s_62,emb_s_63,emb_s_64,emb_s_65,emb_s_66,emb_s_67,emb_s_68,emb_s_69,emb_s_70,emb_s_71,emb_s_72,emb_s_73,emb_s_74,emb_s_75,emb_s_76,emb_s_77,emb_s_78,emb_s_79,emb_s_80,emb_s_81,emb_s_82,emb_s_83,emb_s_84,emb_s_85,emb_s_86,emb_s_87,emb_s_88,emb_s_89,emb_s_90,emb_s_91,emb_s_92,emb_s_93,emb_s_94,emb_s_95,emb_s_96,emb_s_97,emb_s_98,emb_s_99,emb_s_100,emb_s_101,emb_s_102,emb_s_103,emb_s_104,emb_s_105,emb_s_106,emb_s_107,emb_s_108,emb_s_109,emb_s_110,emb_s_111,emb_s_112,emb_s_113,emb_s_114,emb_s_115,emb_s_116,emb_s_117,emb_s_118,emb_s_119,emb_s_120,emb_s_121,emb_s_122,emb_s_123,emb_s_124,emb_s_125,emb_s_126,emb_s_127,emb_s_128,emb_s_129,emb_s_130,emb_s_131,emb_s_132,emb_s_133,emb_s_134,emb_s_135,emb_s_136,emb_s_137,emb_s_138,emb_s_139,emb_s_140,emb_s_141,emb_s_142,emb_s_143,emb_s_144,emb_s_145,emb_s_146,emb_s_147,emb_s_148,emb_s_149,emb_s_150,emb_s_151,emb_s_152,emb_s_153,emb_s_154,emb_s_155,emb_s_156,emb_s_157,emb_s_158,emb_s_159,emb_s_160,emb_s_161,emb_s_162,emb_s_163,emb_s_164,emb_s_165,emb_s_166,emb_s_167,emb_s_168,emb_s_169,emb_s_170,emb_s_171,emb_s_172,emb_s_173,emb_s_174,emb_s_175,emb_s_176,emb_s_177,emb_s_178,emb_s_179,emb_s_180,emb_s_181,emb_s_182,emb_s_183,emb_s_184,emb_s_185,emb_s_186,emb_s_187,emb_s_188,emb_s_189,emb_s_190,emb_s_191,emb_s_192,emb_s_193,emb_s_194,emb_s_195,emb_s_196,emb_s_197,emb_s_198,emb_s_199,emb_s_200,emb_s_201,emb_s_202,emb_s_203,emb_s_204,emb_s_205,emb_s_206,emb_s_207,emb_s_208,emb_s_209,emb_s_210,emb_s_211,emb_s_212,emb_s_213,emb_s_214,emb_s_215,emb_s_216,emb_s_217,emb_s_218,emb_s_219,emb_s_220,emb_s_221,emb_s_222,emb_s_223,emb_s_224,emb_s_225,emb_s_226,emb_s_227,emb_s_228,emb_s_229,emb_s_230,emb_s_231,emb_s_232,emb_s_233,emb_s_234,emb_s_235,emb_s_236,emb_s_237,emb_s_238,emb_s_239,emb_s_240,emb_s_241,emb_s_242,emb_s_243,emb_s_244,emb_s_245,emb_s_246,emb_s_247,emb_s_248,emb_s_249,emb_s_250,emb_s_251,emb_s_252,emb_s_253,emb_s_254,emb_s_255,emb_s_256,emb_s_257,emb_s_258,emb_s_259,emb_s_260,emb_s_261,emb_s_262,emb_s_263,emb_s_264,emb_s_265,emb_s_266,emb_s_267,emb_s_268,emb_s_269,emb_s_270,emb_s_271,emb_s_272,emb_s_273,emb_s_274,emb_s_275,emb_s_276,emb_s_277,emb_s_278,emb_s_279,emb_s_280,emb_s_281,emb_s_282,emb_s_283,emb_s_284,emb_s_285,emb_s_286,emb_s_287,emb_s_288,emb_s_289,emb_s_290,emb_s_291,emb_s_292,emb_s_293,emb_s_294,emb_s_295,emb_s_296,emb_s_297,emb_s_298,emb_s_299,emb_s_300,emb_s_301,emb_s_302,emb_s_303,emb_s_304,emb_s_305,emb_s_306,emb_s_307,emb_s_308,emb_s_309,emb_s_310,emb_s_311,emb_s_312,emb_s_313,emb_s_314,emb_s_315,emb_s_316,emb_s_317,emb_s_318,emb_s_319,emb_s_320,emb_s_321,emb_s_322,emb_s_323,emb_s_324,emb_s_325,emb_s_326,emb_s_327,emb_s_328,emb_s_329,emb_s_330,emb_s_331,emb_s_332,emb_s_333,emb_s_334,emb_s_335,emb_s_336,emb_s_337,emb_s_338,emb_s_339,emb_s_340,emb_s_341,emb_s_342,emb_s_343,emb_s_344,emb_s_345,emb_s_346,emb_s_347,emb_s_348,emb_s_349,emb_s_350,emb_s_351,emb_s_352,emb_s_353,emb_s_354,emb_s_355,emb_s_356,emb_s_357,emb_s_358,emb_s_359,emb_s_360,emb_s_361,emb_s_362,emb_s_363,emb_s_364,emb_s_365,emb_s_366,emb_s_367,emb_s_368,emb_s_369,emb_s_370,emb_s_371,emb_s_372,emb_s_373,emb_s_374,emb_s_375,emb_s_376,emb_s_377,emb_s_378,emb_s_379,emb_s_380,emb_s_381,emb_s_382,emb_s_383
0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2026-03-23T13:31:06Z,Apple;JPMorgan;Netflix;Pfizer,0.040767,-0.004040,-0.046337,-0.014811,0.040611,-0.010620,0.044254,0.013120,0.036194,0.018884,0.031054,0.031754,0.129609,-0.062060,-0.056044,0.053686,0.057087,-0.020003,-0.012454,-0.055738,0.050742,-0.013561,-0.065082,0.029517,0.082369,0.065359,-0.044736,-0.005920,0.010175,-0.036621,-0.071598,-0.023848,0.036660,-0.070989,0.040069,-0.026920,-0.018506,-0.051732,0.027044,-0.042824,-0.028519,0.047341,0.026070,0.084268,0.039830,0.056819,-0.054161,0.024377,-0.041979,0.003022,-0.041287,0.045567,0.051195,0.057424,0.019930,-0.021579,-0.086711,-0.032562,-0.063368,-0.028123,0.036148,-0.029318,0.072835,0.026854,0.088820,0.026451,0.047715,0.071564,-0.097009,-0.003493,-0.035935,0.062983,0.027219,-0.071795,0.066632,0.036529,0.038189,-0.038420,0.026262,0.001615,-0.087280,-0.029053,-0.061329,0.058182,-0.048381,0.049201,0.037077,-0.084314,0.014356,-0.013517,-0.012782,0.027093,-0.036443,-0.067015,-0.110201,-0.092586,-0.051940,0.096052,0.052000,-0.008403,0.047236,-0.054892,0.021642,-0.034692,-0.033301,0.059758,0.003524,-0.084059,0.059620,-0.053642,-0.024931,-0.014200,0.079504,0.037866,-0.072228,-0.046220,-0.020936,-0.054228,0.006330,-0.020747,0.042204,-0.022134,-0.035083,-0.091877,-0.046878,-0.074446,0.038034,0.067828,0.012553,-0.009023,-0.015104,0.037852,0.033808,0.070706,0.069046,0.116860,-0.038927,-0.029981,-0.024866,-0.040821,-0.062569,0.098354,-0.007376,0.061076,0.065264,0.017928,0.053361,-0.039070,0.085992,0.015151,0.051412,-0.032651,0.106014,-0.011596,0.080549,-0.042238,-0.048191,0.007423,0.047633,0.066545,-0.041050,-0.038043,-0.074137,-0.033137,-0.044501,-0.015798,-0.017903,0.103386,-0.017347,-0.034986,-0.039236,0.079811,-0.000778,0.036736,0.010082,0.058886,-0.082035,0.050486,0.067481,0.054545,-0.042083,-0.052850,-0.086020,-0.041989,-0.046380,-0.032107,-0.020886,0.030079,-0.009112,0.003248,-0.049515,0.003059,-0.071004,-0.050848,-0.062620,0.039929,-0.084031,0.055318,0.065514,0.003238,-0.011861,-0.032650,0.032536,0.087276,-0.001354,0.027448,-0.094680,0.063133,-0.058522,0.055877,0.077698,-0.065921,-0.057338,0.060385,-0.018339,-0.030418,0.005494,0.038300,-0.046053,-0.005912,0.064156,-0.031830,0.034192,-0.070436,-0.052327,0.050217,0.079865,-0.068644,-0.058226,0.025113,-0.052526,-0.063865,-0.067269,-0.080222,-0.042596,-0.063483,-0.017006,0.062596,0.060179,-0.022693,-0.018367,-0.040721,-0.001501,-0.030196,0.040809,0.003728,-0.080379,0.037593,-0.005233,0.005013,0.062717,-0.094904,-0.014511,0.034535,-0.038529,0.015553,0.054461,0.100801,-0.062069,0.065487,0.011642,-0.060437,0.080241,0.055169,0.014928,0.022090,-0.027453,-0.032506,-0.055912,-0.045995,-0.036213,0.026336,0.019682,-0.040847,-0.059817,-0.066637,-0.012994,0.068549,-0.045934,0.011099,0.034099,0.017954,0.079103,0.058994,0.039454,0.002911,-0.021366,0.081629,-0.072629,-0.067441,-0.028045,-0.063753,0.005768,-0.051781,0.050276,0.027067,0.018209,0.117146,-0.026327,0.018740,-0.007092,-0.029028,0.012364,0.039105,-0.108621,0.045206,0.047720,0.055394,-0.019313,0.041532,0.028202,0.048321,-0.035827,-0.040251,0.037282,0.075855,0.009400,0.045396,-0.040603,-0.080909,-0.040211,-0.071061,-0.003528,-0.030475,-0.011443,0.008978,-0.052625,-0.032738,0.023790,0.002214,0.042078,-0.046329,0.002772,0.004949,-0.077081,0.028206,-0.015100,0.074825,-0.063524,-0.081832,0.007063,0.051127,-0.030501,0.070287,-0.038490,-0.025016,0.021127,-0.027734,-0.017951,0.022635,0.073952,-0.111178,-0.005855,0.049742,-0.066293,0.025009,-0.101077,-0.008237,0.085511,0.074662,-0.061105,-0.054935,-0.004085,0.083927,0.054774,0.045717,-0.045725,0.004560,0.078146,-0.031801,0.066601,0.006289,-0.026726,0.006637,-0.018801,-0.012216,-0.004009,0.051951,-0.047047,-0.068557,0.049680,0.044040,0.047342,0.106844
1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2025-07-23T10:56:43Z,Apple;JPMorgan;Netflix;Walmart,0.059280,-0.057381,-0.027981,-0.048788,0.061071,0.027902,-0.004932,0.013188,0.066587,0.028523,0.041525,-0.002865,0.116670,-0.063145,-0.042284,0.068170,0.031255,-0.052830,-0.018966,-0.032429,0.010176,-0.051244,-0.027382,0.085185,0.091082,0.082979,-0.045595,-0.007893,0.006642,-0.045666,-0.028982,-0.037867,0.043763,-0.054327,-0.020870,-0.015483,-0.049182,-0.037040,0.041256,-0.052323,-0.017977,0.025323,0.021771,0.091870,0.053889,0.027559,-0.044265,0.049308,-0.028537,-0.042006,-0.092406,0.082583,0.019919,0.036711,0.035367,-0.001990,-0.083350,-0.064722,-0.019457,0.025381,0.028678,-0.027125,0.048441,0.008930,0.102107,0.068121,0.025725,0.062993,-0.055853,-0.026076,-0.061614,0.060748,-0.006761,-0.060617,0.030745,0.069595,0.034374,-0.087713,0.017010,-0.044185,-0.069749,-0.032521,0.002293,0.025799,-0.065162,0.056987,0.044848,-0.060473,0.072275,-0.001074,0.013170,0.083045,-0.051794,-0.036815,-0.046651,-0.029845,-0.042694,0.066317,0.006836,-0.045045,0.075881,-0.008124,0.074611,-0.096351,-0.006696,0.051785,-0.021690,-0.039349,0.025246,-0.067471,-0.022209,0.020070,0.098677,0.015781,-0.023119,-0.075883,-0.015306,-0.051800,0.032666,-0.047628,0.043817,0.016957,-0.034614,-0.082614,-0.040763,-0.040383,0.038322,0.028479,0.054212,-0.057912,0.032788,0.050973,0.051739,0.027201,0.013887,0.110097,-0.070103,-0.061625,-0.079955,-0.021865,-0.076364,0.072708,0.004984,0.053848,0.076091,0.057991,0.078427,-0.008864,0.097575,-0.041250,0.087313,-0.057766,0.083233,0.029626,0.080730,-0.057477,-0.064139,0.004889,0.077274,0.022931,-0.077490,-0.002985,-0.065128,-0.064442,-0.047095,0.000301,0.023924,0.052189,-0.078117,-0.015821,-0.062732,0.047670,-0.031975,0.054887,-0.017435,0.067257,-0.068187,0.007578,0.078305,0.091452,-0.066699,-0.049763,-0.024448,-0.055806,-0.045663,-0.030757,-0.039055,0.011977,-0.016195,-0.001568,-0.007163,0.000382,-0.040303,-0.053827,-0.083639,0.053984,-0.029739,-0.003874,0.036183,0.017503,0.024581,-0.028636,0.012801,0.046395,-0.015819,0.040840,-0.053760,0.063704,-0.021115,0.023650,0.058300,-0.035151,-0.045784,0.041678,-0.036050,0.000414,-0.007971,0.051939,-0.020995,-0.017864,0.053463,-0.046217,0.102606,-0.069900,-0.041188,0.046581,0.069913,-0.075549,-0.066430,0.062908,-0.032657,-0.040065,-0.034012,-0.053448,-0.096286,-0.084372,0.008621,0.012372,0.012113,-0.031169,-0.089476,0.002430,-0.009091,-0.061957,0.074019,-0.054286,-0.053004,0.025438,-0.010974,0.014587,0.083911,-0.053089,-0.033315,0.028754,-0.059859,0.066900,0.080412,0.059776,-0.047477,0.038931,-0.006220,-0.007220,0.089035,0.035008,0.053773,-0.008527,-0.044405,-0.007093,-0.047824,-0.066415,-0.119973,0.024551,0.052859,-0.019545,-0.037023,-0.056992,-0.060047,0.057525,-0.071738,-0.047178,0.019965,0.029037,0.038018,0.067003,0.057344,0.011316,0.010309,0.062302,-0.022173,-0.045242,-0.068041,-0.049681,0.023249,-0.032828,0.080050,0.045975,0.014761,0.064600,-0.027769,0.050219,0.015492,-0.034038,0.039500,0.033001,-0.112426,0.021783,0.056455,0.044564,0.004514,0.015037,0.036755,0.030055,-0.079941,0.018864,0.051110,0.094701,0.030926,0.023013,-0.031396,-0.083536,-0.051133,-0.090182,-0.025837,-0.020337,0.048821,0.062665,-0.048162,-0.051936,0.021893,0.008603,0.020584,-0.073946,-0.066705,0.006661,-0.098378,0.017944,0.048021,0.028114,-0.045915,-0.065528,-0.002924,-0.005961,-0.037415,0.082413,-0.009392,-0.072369,0.035800,-0.047439,0.001725,0.027792,0.091319,-0.083402,0.010345,0.027168,-0.051709,0.056384,-0.091931,-0.003198,0.064337,0.061727,-0.050847,-0.009181,0.039151,0.087073,0.051364,0.052137,-0.043676,0.022774,0.048733,-0.053401,0.037629,0.043877,-0.034079,-0.001321,-0.039701,-0.002371,-0.025519,0.036129,-0.035528,-0.057406,0.016364,0.052667,0.043077,0.086587
2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2025-09-14T14:00:35Z,Apple;Exxon;Pfizer,0.021654,-0.044373,-0.026252,-0.049949,0.059014,-0.017337,0.045011,0.040794,0.045781,0.044233,0.017911,0.026637,0.051157,-0.052986,-0.040400,0.066073,0.010558,-0.053913,0.021686,-0.091170,0.080415,0.054485,-0.038386,0.042040,0.041486,-0.014369,0.017234,-0.039521,0.067364,-0.033649,-0.066141,-0.022112,0.047036,-0.057766,0.061697,-0.011614,-0.078875,-0.041731,0.035048,-0.028012,-0.008303,0.015355,0.065206,0.042108,0.028174,0.048899,-0.047956,0.035264,-0.016644,-0.033129,-0.128197,0.025155,0.003960,0.074836,0.005383,-0.048134,-0.045238,-0.103145,-0.066331,0.080756,0.055794,-0.037221,0.029348,-0.005839,0.097016,0.037643,0.018826,-0.002756,-0.088767,-0.014126,-0.038614,0.070903,0.015702,-0.053835,0.028755,0.017429,-0.005790,-0.057094,0.051320,-0.054580,-0.077754,0.002245,-0.008480,-0.000906,-0.057352,0.044167,0.035626,-0.090545,0.098843,-0.020079,0.058052,-0.015205,-0.055136,-0.036224,-0.066198,-0.025845,-0.053524,0.075279,0.033141,-0.038557,0.076272,-0.009042,0.048782,-0.016289,0.030517,0.032719,0.063305,-0.112885,0.077742,-0.038582,-0.029330,0.061268,0.097949,0.032259,-0.040376,-0.053437,-0.009291,-0.054872,0.065246,-0.052335,0.101367,-0.018504,-0.035983,-0.062577,-0.090814,-0.047966,0.061182,0.025329,-0.017334,0.038401,0.028328,0.071788,0.017499,0.016057,-0.005527,0.081600,-0.057855,-0.046653,0.012137,-0.043123,-0.068487,0.051321,-0.033532,0.063698,0.087589,0.087798,0.067860,-0.000905,0.085528,0.012538,0.021863,0.002542,0.050672,0.040047,0.084756,-0.075968,-0.093385,-0.042921,0.093481,0.008412,-0.052452,-0.076506,-0.041948,-0.025229,-0.038149,-0.101695,0.010793,0.066644,-0.017359,-0.005448,-0.058952,0.071932,-0.023928,0.081158,-0.012230,0.061087,-0.050793,0.054234,0.015595,0.039260,-0.016880,-0.034326,-0.006372,-0.005719,-0.060925,-0.002686,-0.071756,0.068750,0.033436,-0.057273,0.037692,0.044611,-0.036514,-0.049794,-0.037049,0.023257,-0.076273,0.034873,0.024927,0.007791,0.032560,-0.040533,0.029499,0.034392,0.021046,0.015855,-0.064427,0.052680,-0.050096,0.030224,0.082298,-0.058401,-0.065000,0.014641,-0.046261,-0.003336,-0.010008,0.100751,-0.106218,-0.014456,0.036485,-0.033124,0.027954,-0.089195,-0.043769,0.068118,0.010143,-0.043891,-0.052669,0.054914,-0.061287,-0.072078,-0.061046,-0.075551,-0.030127,-0.038657,-0.057914,-0.003586,0.029237,-0.035837,-0.008247,-0.046517,0.052124,-0.040927,0.035008,-0.081962,-0.030935,0.018849,-0.005990,0.028380,0.044549,-0.068926,-0.035511,-0.026595,0.015556,0.064919,0.035584,0.070623,-0.053501,0.051573,0.028415,-0.045962,0.117511,0.071440,0.022616,0.038326,-0.025927,-0.048354,-0.046409,-0.057937,-0.073748,0.074571,0.019716,-0.061182,-0.063590,-0.012674,0.028570,0.046253,-0.039205,-0.022315,0.046573,0.039803,0.041497,0.047280,0.022282,0.034340,-0.020848,0.050761,-0.022965,-0.026222,-0.021634,-0.031385,0.043514,-0.044571,0.039866,0.045409,-0.010941,0.095693,-0.011960,0.071144,-0.044338,-0.038206,0.043091,0.078324,-0.093297,0.005102,-0.062498,0.023630,-0.046434,-0.006771,0.039530,0.088778,-0.047053,-0.031762,0.070323,0.018015,-0.025064,0.026408,-0.028587,-0.065982,-0.000690,-0.048905,0.007064,-0.081903,0.039723,0.049282,-0.021088,-0.057172,0.017342,-0.044017,0.052592,-0.045420,-0.045566,0.015476,-0.049692,-0.008818,-0.014684,0.082152,-0.033160,-0.033271,0.020473,-0.007971,-0.034063,0.098368,-0.002120,-0.039981,0.060435,-0.061145,-0.032090,0.009489,0.051043,-0.106698,0.004465,0.067868,-0.048359,0.051420,-0.046279,-0.021243,0.091497,0.025620,-0.088587,0.029425,0.038231,0.084421,0.019395,0.043448,-0.077419,-0.003308,0.038234,-0.052747,0.104157,0.084803,-0.028142,0.037157,-0.051177,-0.037212,-0.030551,0.012940,-0.058390,-0.069346,0.021384,0.026293,0.080304,0.072608
3,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,2025-04-23T12:09:39Z,Apple;Netflix,0.052310,-0.015904,-0.032087,-0.017634,0.039773,-0.004176,0.019059,0.067205,0.070732,-0.021923,0.032265,0.013762,0.084923,-0.065357,-0.047672,0.061858,0.029973,-0.036503,-0.006710,-0.039479,0.068914,-0.039273,-0.024193,0.036006,0.072338,0.018894,0.007974,-0.022148,0.005651,-0.042340,-0.042627,-0.039028,0.038047,-0.059028,0.041229,-0.020069,-0.037851,-0.027828,0.068047,-0.041226,-0.013869,0.046121,0.067583,0.077569,0.043695,0.025588,-0.043779,0.049635,-0.028483,-0.036477,-0.055551,0.067298,0.015068,0.061521,0.022114,-0.019079,-0.060566,-0.059511,-0.036324,-0.020749,0.053422,-0.050642,0.071892,-0.033722,0.080648,0.064996,0.059270,0.028539,-0.102592,0.007219,-0.058270,0.052406,-0.002582,-0.072928,0.070464,0.039449,0.000210,-0.077220,-0.022231,-0.063808,-0.135799,-0.038274,-0.022664,0.064531,-0.042277,0.042139,0.025339,-0.062199,0.097243,0.005367,0.072864,0.022762,-0.050954,-0.064973,-0.043460,-0.025620,-0.017485,0.095311,0.049161,0.007791,0.112275,-0.033633,0.012573,-0.021627,-0.035606,0.019896,0.019192,-0.062222,0.083505,-0.060656,-0.045712,0.041504,0.117653,0.002671,-0.066632,-0.025154,-0.013236,-0.064546,-0.002673,-0.053512,0.065390,0.004114,-0.052780,-0.091895,-0.036810,-0.033512,0.066877,0.049724,0.014189,-0.067070,-0.031927,0.057051,0.068912,0.078848,0.078314,0.077209,-0.069445,-0.008276,-0.070547,-0.063824,-0.016598,0.083985,0.023471,0.061098,0.026327,0.048587,0.071190,-0.013853,0.092122,-0.045148,0.084506,-0.055245,0.072459,0.009582,0.071465,-0.078768,-0.114145,-0.028454,0.051166,0.003698,-0.067779,-0.015950,-0.045285,-0.017373,-0.047429,-0.031242,0.014955,0.067499,-0.023651,-0.034116,-0.034284,0.047316,-0.006292,0.078190,0.004733,0.043370,-0.047521,0.070826,0.050101,0.087415,-0.064756,-0.037940,-0.043008,-0.057137,-0.023830,-0.036886,-0.031009,0.020038,-0.041439,-0.047212,-0.036157,-0.020031,-0.043806,-0.028691,-0.069324,0.017913,-0.046171,0.064908,0.001949,0.059561,0.026740,-0.018008,0.040626,0.022830,0.030961,0.011801,-0.057996,0.063802,-0.022458,0.070401,0.050284,-0.016999,-0.048671,0.037805,-0.053108,0.004714,0.028216,0.050996,-0.074558,0.036126,0.041933,-0.065440,0.096809,-0.080241,-0.018143,0.072639,0.087053,-0.061736,-0.074559,0.031788,-0.052703,-0.027632,-0.055200,-0.051575,-0.073527,-0.013041,-0.022331,0.061937,0.004099,-0.017499,-0.056719,-0.060045,-0.026432,-0.081766,0.035784,-0.004819,-0.044847,0.021762,0.008289,0.026840,0.052909,-0.031187,-0.025835,-0.000970,-0.026201,0.028661,0.057685,0.046692,-0.037390,0.062522,-0.013954,-0.045234,0.070417,0.031372,0.052508,0.012956,-0.020974,-0.034056,-0.047024,-0.039818,-0.089461,0.011473,0.053670,-0.067535,-0.085891,-0.061470,-0.018687,0.033833,-0.069298,-0.062477,0.077148,0.025667,0.078208,0.007339,0.066103,-0.025630,-0.030694,0.087930,-0.056397,-0.066202,-0.064268,-0.069196,0.044843,-0.066360,0.036971,0.026876,0.020451,0.103152,-0.031575,0.035608,0.005493,-0.017236,0.062160,0.059852,-0.087888,0.048754,0.014252,0.018713,0.037708,0.016457,0.054653,0.012170,-0.035086,-0.004570,0.007604,0.107936,-0.001238,0.019530,-0.071506,-0.032073,-0.037493,-0.079188,-0.003536,-0.031776,0.048121,0.057565,-0.039131,-0.037623,0.006024,-0.007533,0.025280,-0.075851,-0.024102,0.050881,-0.065683,0.005898,0.009070,0.024278,-0.090319,-0.060190,0.013057,0.080397,-0.031364,0.040494,-0.059801,-0.046806,0.019373,-0.020493,-0.016645,0.041901,0.091140,-0.106819,0.012861,0.032416,-0.062112,0.039206,-0.048696,0.009416,0.039996,0.049745,-0.086738,-0.011925,0.027007,0.093845,0.045020,0.047720,-0.023941,0.007533,0.072005,-0.074519,0.012933,0.075977,-0.015650,-0.025973,-0.022802,-0.064005,-0.047109,0.049824,-0.042198,-0.063234,0.050466,0.047539,-0.010733,0.078279